// Code generated by ent, DO NOT EDIT.

package prescriptionline

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the prescriptionline type in the database.
	Label = "prescription_line"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldPrescriptionID holds the string denoting the prescription_id field in the database.
	FieldPrescriptionID = "prescription_id"
	// FieldInventoryItemSku holds the string denoting the inventory_item_sku field in the database.
	FieldInventoryItemSku = "inventory_item_sku"
	// FieldDrugName holds the string denoting the drug_name field in the database.
	FieldDrugName = "drug_name"
	// FieldDosage holds the string denoting the dosage field in the database.
	FieldDosage = "dosage"
	// FieldForm holds the string denoting the form field in the database.
	FieldForm = "form"
	// FieldInstructions holds the string denoting the instructions field in the database.
	FieldInstructions = "instructions"
	// FieldQuantityPrescribed holds the string denoting the quantity_prescribed field in the database.
	FieldQuantityPrescribed = "quantity_prescribed"
	// FieldQuantityDispensed holds the string denoting the quantity_dispensed field in the database.
	FieldQuantityDispensed = "quantity_dispensed"
	// FieldUnitPrice holds the string denoting the unit_price field in the database.
	FieldUnitPrice = "unit_price"
	// FieldLotNumber holds the string denoting the lot_number field in the database.
	FieldLotNumber = "lot_number"
	// FieldExpiryDate holds the string denoting the expiry_date field in the database.
	FieldExpiryDate = "expiry_date"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgePrescription holds the string denoting the prescription edge name in mutations.
	EdgePrescription = "prescription"
	// Table holds the table name of the prescriptionline in the database.
	Table = "prescription_lines"
	// PrescriptionTable is the table that holds the prescription relation/edge.
	PrescriptionTable = "prescription_lines"
	// PrescriptionInverseTable is the table name for the Prescription entity.
	// It exists in this package in order to avoid circular dependency with the "prescription" package.
	PrescriptionInverseTable = "prescriptions"
	// PrescriptionColumn is the table column denoting the prescription relation/edge.
	PrescriptionColumn = "prescription_id"
)

// Columns holds all SQL columns for prescriptionline fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldPrescriptionID,
	FieldInventoryItemSku,
	FieldDrugName,
	FieldDosage,
	FieldForm,
	FieldInstructions,
	FieldQuantityPrescribed,
	FieldQuantityDispensed,
	FieldUnitPrice,
	FieldLotNumber,
	FieldExpiryDate,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DrugNameValidator is a validator for the "drug_name" field. It is called by the builders before save.
	DrugNameValidator func(string) error
	// QuantityPrescribedValidator is a validator for the "quantity_prescribed" field. It is called by the builders before save.
	QuantityPrescribedValidator func(float64) error
	// DefaultQuantityDispensed holds the default value on creation for the "quantity_dispensed" field.
	DefaultQuantityDispensed float64
	// DefaultUnitPrice holds the default value on creation for the "unit_price" field.
	DefaultUnitPrice float64
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending            Status = "pending"
	StatusDispensed          Status = "dispensed"
	StatusPartiallyDispensed Status = "partially_dispensed"
	StatusCancelled          Status = "cancelled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusDispensed, StatusPartiallyDispensed, StatusCancelled:
		return nil
	default:
		return fmt.Errorf("prescriptionline: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the PrescriptionLine queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByPrescriptionID orders the results by the prescription_id field.
func ByPrescriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrescriptionID, opts...).ToFunc()
}

// ByInventoryItemSku orders the results by the inventory_item_sku field.
func ByInventoryItemSku(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInventoryItemSku, opts...).ToFunc()
}

// ByDrugName orders the results by the drug_name field.
func ByDrugName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDrugName, opts...).ToFunc()
}

// ByDosage orders the results by the dosage field.
func ByDosage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDosage, opts...).ToFunc()
}

// ByForm orders the results by the form field.
func ByForm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldForm, opts...).ToFunc()
}

// ByInstructions orders the results by the instructions field.
func ByInstructions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstructions, opts...).ToFunc()
}

// ByQuantityPrescribed orders the results by the quantity_prescribed field.
func ByQuantityPrescribed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantityPrescribed, opts...).ToFunc()
}

// ByQuantityDispensed orders the results by the quantity_dispensed field.
func ByQuantityDispensed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantityDispensed, opts...).ToFunc()
}

// ByUnitPrice orders the results by the unit_price field.
func ByUnitPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitPrice, opts...).ToFunc()
}

// ByLotNumber orders the results by the lot_number field.
func ByLotNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLotNumber, opts...).ToFunc()
}

// ByExpiryDate orders the results by the expiry_date field.
func ByExpiryDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiryDate, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPrescriptionField orders the results by prescription field.
func ByPrescriptionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrescriptionStep(), sql.OrderByField(field, opts...))
	}
}
func newPrescriptionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrescriptionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PrescriptionTable, PrescriptionColumn),
	)
}
