// Code generated by ent, DO NOT EDIT.

package bed

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/hospital-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldEQ(FieldTenantID, v))
}

// WardID applies equality check predicate on the "ward_id" field. It's identical to WardIDEQ.
func WardID(v uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldEQ(FieldWardID, v))
}

// BedNumber applies equality check predicate on the "bed_number" field. It's identical to BedNumberEQ.
func BedNumber(v string) predicate.Bed {
	return predicate.Bed(sql.FieldEQ(FieldBedNumber, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Bed {
	return predicate.Bed(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Bed {
	return predicate.Bed(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldLTE(FieldTenantID, v))
}

// WardIDEQ applies the EQ predicate on the "ward_id" field.
func WardIDEQ(v uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldEQ(FieldWardID, v))
}

// WardIDNEQ applies the NEQ predicate on the "ward_id" field.
func WardIDNEQ(v uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldNEQ(FieldWardID, v))
}

// WardIDIn applies the In predicate on the "ward_id" field.
func WardIDIn(vs ...uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldIn(FieldWardID, vs...))
}

// WardIDNotIn applies the NotIn predicate on the "ward_id" field.
func WardIDNotIn(vs ...uuid.UUID) predicate.Bed {
	return predicate.Bed(sql.FieldNotIn(FieldWardID, vs...))
}

// BedNumberEQ applies the EQ predicate on the "bed_number" field.
func BedNumberEQ(v string) predicate.Bed {
	return predicate.Bed(sql.FieldEQ(FieldBedNumber, v))
}

// BedNumberNEQ applies the NEQ predicate on the "bed_number" field.
func BedNumberNEQ(v string) predicate.Bed {
	return predicate.Bed(sql.FieldNEQ(FieldBedNumber, v))
}

// BedNumberIn applies the In predicate on the "bed_number" field.
func BedNumberIn(vs ...string) predicate.Bed {
	return predicate.Bed(sql.FieldIn(FieldBedNumber, vs...))
}

// BedNumberNotIn applies the NotIn predicate on the "bed_number" field.
func BedNumberNotIn(vs ...string) predicate.Bed {
	return predicate.Bed(sql.FieldNotIn(FieldBedNumber, vs...))
}

// BedNumberGT applies the GT predicate on the "bed_number" field.
func BedNumberGT(v string) predicate.Bed {
	return predicate.Bed(sql.FieldGT(FieldBedNumber, v))
}

// BedNumberGTE applies the GTE predicate on the "bed_number" field.
func BedNumberGTE(v string) predicate.Bed {
	return predicate.Bed(sql.FieldGTE(FieldBedNumber, v))
}

// BedNumberLT applies the LT predicate on the "bed_number" field.
func BedNumberLT(v string) predicate.Bed {
	return predicate.Bed(sql.FieldLT(FieldBedNumber, v))
}

// BedNumberLTE applies the LTE predicate on the "bed_number" field.
func BedNumberLTE(v string) predicate.Bed {
	return predicate.Bed(sql.FieldLTE(FieldBedNumber, v))
}

// BedNumberContains applies the Contains predicate on the "bed_number" field.
func BedNumberContains(v string) predicate.Bed {
	return predicate.Bed(sql.FieldContains(FieldBedNumber, v))
}

// BedNumberHasPrefix applies the HasPrefix predicate on the "bed_number" field.
func BedNumberHasPrefix(v string) predicate.Bed {
	return predicate.Bed(sql.FieldHasPrefix(FieldBedNumber, v))
}

// BedNumberHasSuffix applies the HasSuffix predicate on the "bed_number" field.
func BedNumberHasSuffix(v string) predicate.Bed {
	return predicate.Bed(sql.FieldHasSuffix(FieldBedNumber, v))
}

// BedNumberEqualFold applies the EqualFold predicate on the "bed_number" field.
func BedNumberEqualFold(v string) predicate.Bed {
	return predicate.Bed(sql.FieldEqualFold(FieldBedNumber, v))
}

// BedNumberContainsFold applies the ContainsFold predicate on the "bed_number" field.
func BedNumberContainsFold(v string) predicate.Bed {
	return predicate.Bed(sql.FieldContainsFold(FieldBedNumber, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Bed {
	return predicate.Bed(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Bed {
	return predicate.Bed(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Bed {
	return predicate.Bed(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Bed {
	return predicate.Bed(sql.FieldNotIn(FieldStatus, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Bed {
	return predicate.Bed(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Bed {
	return predicate.Bed(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Bed {
	return predicate.Bed(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Bed {
	return predicate.Bed(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Bed {
	return predicate.Bed(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Bed {
	return predicate.Bed(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Bed {
	return predicate.Bed(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Bed {
	return predicate.Bed(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Bed {
	return predicate.Bed(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Bed {
	return predicate.Bed(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Bed {
	return predicate.Bed(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Bed {
	return predicate.Bed(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Bed {
	return predicate.Bed(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Bed {
	return predicate.Bed(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Bed {
	return predicate.Bed(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Bed {
	return predicate.Bed(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasWard applies the HasEdge predicate on the "ward" edge.
func HasWard() predicate.Bed {
	return predicate.Bed(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WardTable, WardColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWardWith applies the HasEdge predicate on the "ward" edge with a given conditions (other predicates).
func HasWardWith(preds ...predicate.Ward) predicate.Bed {
	return predicate.Bed(func(s *sql.Selector) {
		step := newWardStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAdmissions applies the HasEdge predicate on the "admissions" edge.
func HasAdmissions() predicate.Bed {
	return predicate.Bed(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AdmissionsTable, AdmissionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAdmissionsWith applies the HasEdge predicate on the "admissions" edge with a given conditions (other predicates).
func HasAdmissionsWith(preds ...predicate.Admission) predicate.Bed {
	return predicate.Bed(func(s *sql.Selector) {
		step := newAdmissionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Bed) predicate.Bed {
	return predicate.Bed(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Bed) predicate.Bed {
	return predicate.Bed(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Bed) predicate.Bed {
	return predicate.Bed(sql.NotPredicates(p))
}
