// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/hospital-service/internal/ent/admission"
	"github.com/bengobox/hospital-service/internal/ent/bed"
	"github.com/bengobox/hospital-service/internal/ent/medicationadministration"
	"github.com/bengobox/hospital-service/internal/ent/patientvisit"
	"github.com/google/uuid"
)

// AdmissionCreate is the builder for creating a Admission entity.
type AdmissionCreate struct {
	config
	mutation *AdmissionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *AdmissionCreate) SetTenantID(v uuid.UUID) *AdmissionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetOutletID sets the "outlet_id" field.
func (_c *AdmissionCreate) SetOutletID(v uuid.UUID) *AdmissionCreate {
	_c.mutation.SetOutletID(v)
	return _c
}

// SetPatientVisitID sets the "patient_visit_id" field.
func (_c *AdmissionCreate) SetPatientVisitID(v uuid.UUID) *AdmissionCreate {
	_c.mutation.SetPatientVisitID(v)
	return _c
}

// SetPatientID sets the "patient_id" field.
func (_c *AdmissionCreate) SetPatientID(v uuid.UUID) *AdmissionCreate {
	_c.mutation.SetPatientID(v)
	return _c
}

// SetAdmissionNumber sets the "admission_number" field.
func (_c *AdmissionCreate) SetAdmissionNumber(v string) *AdmissionCreate {
	_c.mutation.SetAdmissionNumber(v)
	return _c
}

// SetWardID sets the "ward_id" field.
func (_c *AdmissionCreate) SetWardID(v uuid.UUID) *AdmissionCreate {
	_c.mutation.SetWardID(v)
	return _c
}

// SetBedID sets the "bed_id" field.
func (_c *AdmissionCreate) SetBedID(v uuid.UUID) *AdmissionCreate {
	_c.mutation.SetBedID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AdmissionCreate) SetStatus(v admission.Status) *AdmissionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AdmissionCreate) SetNillableStatus(v *admission.Status) *AdmissionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAdmittedBy sets the "admitted_by" field.
func (_c *AdmissionCreate) SetAdmittedBy(v uuid.UUID) *AdmissionCreate {
	_c.mutation.SetAdmittedBy(v)
	return _c
}

// SetNillableAdmittedBy sets the "admitted_by" field if the given value is not nil.
func (_c *AdmissionCreate) SetNillableAdmittedBy(v *uuid.UUID) *AdmissionCreate {
	if v != nil {
		_c.SetAdmittedBy(*v)
	}
	return _c
}

// SetAdmittedAt sets the "admitted_at" field.
func (_c *AdmissionCreate) SetAdmittedAt(v time.Time) *AdmissionCreate {
	_c.mutation.SetAdmittedAt(v)
	return _c
}

// SetNillableAdmittedAt sets the "admitted_at" field if the given value is not nil.
func (_c *AdmissionCreate) SetNillableAdmittedAt(v *time.Time) *AdmissionCreate {
	if v != nil {
		_c.SetAdmittedAt(*v)
	}
	return _c
}

// SetDischargedAt sets the "discharged_at" field.
func (_c *AdmissionCreate) SetDischargedAt(v time.Time) *AdmissionCreate {
	_c.mutation.SetDischargedAt(v)
	return _c
}

// SetNillableDischargedAt sets the "discharged_at" field if the given value is not nil.
func (_c *AdmissionCreate) SetNillableDischargedAt(v *time.Time) *AdmissionCreate {
	if v != nil {
		_c.SetDischargedAt(*v)
	}
	return _c
}

// SetDischargedBy sets the "discharged_by" field.
func (_c *AdmissionCreate) SetDischargedBy(v uuid.UUID) *AdmissionCreate {
	_c.mutation.SetDischargedBy(v)
	return _c
}

// SetNillableDischargedBy sets the "discharged_by" field if the given value is not nil.
func (_c *AdmissionCreate) SetNillableDischargedBy(v *uuid.UUID) *AdmissionCreate {
	if v != nil {
		_c.SetDischargedBy(*v)
	}
	return _c
}

// SetDischargeSummary sets the "discharge_summary" field.
func (_c *AdmissionCreate) SetDischargeSummary(v string) *AdmissionCreate {
	_c.mutation.SetDischargeSummary(v)
	return _c
}

// SetNillableDischargeSummary sets the "discharge_summary" field if the given value is not nil.
func (_c *AdmissionCreate) SetNillableDischargeSummary(v *string) *AdmissionCreate {
	if v != nil {
		_c.SetDischargeSummary(*v)
	}
	return _c
}

// SetWardChargePosted sets the "ward_charge_posted" field.
func (_c *AdmissionCreate) SetWardChargePosted(v bool) *AdmissionCreate {
	_c.mutation.SetWardChargePosted(v)
	return _c
}

// SetNillableWardChargePosted sets the "ward_charge_posted" field if the given value is not nil.
func (_c *AdmissionCreate) SetNillableWardChargePosted(v *bool) *AdmissionCreate {
	if v != nil {
		_c.SetWardChargePosted(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdmissionCreate) SetCreatedAt(v time.Time) *AdmissionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdmissionCreate) SetNillableCreatedAt(v *time.Time) *AdmissionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AdmissionCreate) SetUpdatedAt(v time.Time) *AdmissionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AdmissionCreate) SetNillableUpdatedAt(v *time.Time) *AdmissionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AdmissionCreate) SetID(v uuid.UUID) *AdmissionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AdmissionCreate) SetNillableID(v *uuid.UUID) *AdmissionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetVisitID sets the "visit" edge to the PatientVisit entity by ID.
func (_c *AdmissionCreate) SetVisitID(id uuid.UUID) *AdmissionCreate {
	_c.mutation.SetVisitID(id)
	return _c
}

// SetVisit sets the "visit" edge to the PatientVisit entity.
func (_c *AdmissionCreate) SetVisit(v *PatientVisit) *AdmissionCreate {
	return _c.SetVisitID(v.ID)
}

// SetBed sets the "bed" edge to the Bed entity.
func (_c *AdmissionCreate) SetBed(v *Bed) *AdmissionCreate {
	return _c.SetBedID(v.ID)
}

// AddMedicationAdministrationIDs adds the "medication_administrations" edge to the MedicationAdministration entity by IDs.
func (_c *AdmissionCreate) AddMedicationAdministrationIDs(ids ...uuid.UUID) *AdmissionCreate {
	_c.mutation.AddMedicationAdministrationIDs(ids...)
	return _c
}

// AddMedicationAdministrations adds the "medication_administrations" edges to the MedicationAdministration entity.
func (_c *AdmissionCreate) AddMedicationAdministrations(v ...*MedicationAdministration) *AdmissionCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMedicationAdministrationIDs(ids...)
}

// Mutation returns the AdmissionMutation object of the builder.
func (_c *AdmissionCreate) Mutation() *AdmissionMutation {
	return _c.mutation
}

// Save creates the Admission in the database.
func (_c *AdmissionCreate) Save(ctx context.Context) (*Admission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdmissionCreate) SaveX(ctx context.Context) *Admission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdmissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdmissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdmissionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := admission.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AdmittedAt(); !ok {
		v := admission.DefaultAdmittedAt()
		_c.mutation.SetAdmittedAt(v)
	}
	if _, ok := _c.mutation.WardChargePosted(); !ok {
		v := admission.DefaultWardChargePosted
		_c.mutation.SetWardChargePosted(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := admission.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := admission.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := admission.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdmissionCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Admission.tenant_id"`)}
	}
	if _, ok := _c.mutation.OutletID(); !ok {
		return &ValidationError{Name: "outlet_id", err: errors.New(`ent: missing required field "Admission.outlet_id"`)}
	}
	if _, ok := _c.mutation.PatientVisitID(); !ok {
		return &ValidationError{Name: "patient_visit_id", err: errors.New(`ent: missing required field "Admission.patient_visit_id"`)}
	}
	if _, ok := _c.mutation.PatientID(); !ok {
		return &ValidationError{Name: "patient_id", err: errors.New(`ent: missing required field "Admission.patient_id"`)}
	}
	if _, ok := _c.mutation.AdmissionNumber(); !ok {
		return &ValidationError{Name: "admission_number", err: errors.New(`ent: missing required field "Admission.admission_number"`)}
	}
	if v, ok := _c.mutation.AdmissionNumber(); ok {
		if err := admission.AdmissionNumberValidator(v); err != nil {
			return &ValidationError{Name: "admission_number", err: fmt.Errorf(`ent: validator failed for field "Admission.admission_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WardID(); !ok {
		return &ValidationError{Name: "ward_id", err: errors.New(`ent: missing required field "Admission.ward_id"`)}
	}
	if _, ok := _c.mutation.BedID(); !ok {
		return &ValidationError{Name: "bed_id", err: errors.New(`ent: missing required field "Admission.bed_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Admission.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := admission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Admission.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AdmittedAt(); !ok {
		return &ValidationError{Name: "admitted_at", err: errors.New(`ent: missing required field "Admission.admitted_at"`)}
	}
	if _, ok := _c.mutation.WardChargePosted(); !ok {
		return &ValidationError{Name: "ward_charge_posted", err: errors.New(`ent: missing required field "Admission.ward_charge_posted"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Admission.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Admission.updated_at"`)}
	}
	if len(_c.mutation.VisitIDs()) == 0 {
		return &ValidationError{Name: "visit", err: errors.New(`ent: missing required edge "Admission.visit"`)}
	}
	if len(_c.mutation.BedIDs()) == 0 {
		return &ValidationError{Name: "bed", err: errors.New(`ent: missing required edge "Admission.bed"`)}
	}
	return nil
}

func (_c *AdmissionCreate) sqlSave(ctx context.Context) (*Admission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdmissionCreate) createSpec() (*Admission, *sqlgraph.CreateSpec) {
	var (
		_node = &Admission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(admission.Table, sqlgraph.NewFieldSpec(admission.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(admission.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.OutletID(); ok {
		_spec.SetField(admission.FieldOutletID, field.TypeUUID, value)
		_node.OutletID = value
	}
	if value, ok := _c.mutation.PatientID(); ok {
		_spec.SetField(admission.FieldPatientID, field.TypeUUID, value)
		_node.PatientID = value
	}
	if value, ok := _c.mutation.AdmissionNumber(); ok {
		_spec.SetField(admission.FieldAdmissionNumber, field.TypeString, value)
		_node.AdmissionNumber = value
	}
	if value, ok := _c.mutation.WardID(); ok {
		_spec.SetField(admission.FieldWardID, field.TypeUUID, value)
		_node.WardID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(admission.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AdmittedBy(); ok {
		_spec.SetField(admission.FieldAdmittedBy, field.TypeUUID, value)
		_node.AdmittedBy = &value
	}
	if value, ok := _c.mutation.AdmittedAt(); ok {
		_spec.SetField(admission.FieldAdmittedAt, field.TypeTime, value)
		_node.AdmittedAt = value
	}
	if value, ok := _c.mutation.DischargedAt(); ok {
		_spec.SetField(admission.FieldDischargedAt, field.TypeTime, value)
		_node.DischargedAt = &value
	}
	if value, ok := _c.mutation.DischargedBy(); ok {
		_spec.SetField(admission.FieldDischargedBy, field.TypeUUID, value)
		_node.DischargedBy = &value
	}
	if value, ok := _c.mutation.DischargeSummary(); ok {
		_spec.SetField(admission.FieldDischargeSummary, field.TypeString, value)
		_node.DischargeSummary = value
	}
	if value, ok := _c.mutation.WardChargePosted(); ok {
		_spec.SetField(admission.FieldWardChargePosted, field.TypeBool, value)
		_node.WardChargePosted = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(admission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(admission.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.VisitIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   admission.VisitTable,
			Columns: []string{admission.VisitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patientvisit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PatientVisitID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   admission.BedTable,
			Columns: []string{admission.BedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bed.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BedID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MedicationAdministrationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   admission.MedicationAdministrationsTable,
			Columns: []string{admission.MedicationAdministrationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(medicationadministration.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Admission.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdmissionUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *AdmissionCreate) OnConflict(opts ...sql.ConflictOption) *AdmissionUpsertOne {
	_c.conflict = opts
	return &AdmissionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Admission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdmissionCreate) OnConflictColumns(columns ...string) *AdmissionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdmissionUpsertOne{
		create: _c,
	}
}

type (
	// AdmissionUpsertOne is the builder for "upsert"-ing
	//  one Admission node.
	AdmissionUpsertOne struct {
		create *AdmissionCreate
	}

	// AdmissionUpsert is the "OnConflict" setter.
	AdmissionUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *AdmissionUpsert) SetTenantID(v uuid.UUID) *AdmissionUpsert {
	u.Set(admission.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *AdmissionUpsert) UpdateTenantID() *AdmissionUpsert {
	u.SetExcluded(admission.FieldTenantID)
	return u
}

// SetOutletID sets the "outlet_id" field.
func (u *AdmissionUpsert) SetOutletID(v uuid.UUID) *AdmissionUpsert {
	u.Set(admission.FieldOutletID, v)
	return u
}

// UpdateOutletID sets the "outlet_id" field to the value that was provided on create.
func (u *AdmissionUpsert) UpdateOutletID() *AdmissionUpsert {
	u.SetExcluded(admission.FieldOutletID)
	return u
}

// SetPatientVisitID sets the "patient_visit_id" field.
func (u *AdmissionUpsert) SetPatientVisitID(v uuid.UUID) *AdmissionUpsert {
	u.Set(admission.FieldPatientVisitID, v)
	return u
}

// UpdatePatientVisitID sets the "patient_visit_id" field to the value that was provided on create.
func (u *AdmissionUpsert) UpdatePatientVisitID() *AdmissionUpsert {
	u.SetExcluded(admission.FieldPatientVisitID)
	return u
}

// SetPatientID sets the "patient_id" field.
func (u *AdmissionUpsert) SetPatientID(v uuid.UUID) *AdmissionUpsert {
	u.Set(admission.FieldPatientID, v)
	return u
}

// UpdatePatientID sets the "patient_id" field to the value that was provided on create.
func (u *AdmissionUpsert) UpdatePatientID() *AdmissionUpsert {
	u.SetExcluded(admission.FieldPatientID)
	return u
}

// SetAdmissionNumber sets the "admission_number" field.
func (u *AdmissionUpsert) SetAdmissionNumber(v string) *AdmissionUpsert {
	u.Set(admission.FieldAdmissionNumber, v)
	return u
}

// UpdateAdmissionNumber sets the "admission_number" field to the value that was provided on create.
func (u *AdmissionUpsert) UpdateAdmissionNumber() *AdmissionUpsert {
	u.SetExcluded(admission.FieldAdmissionNumber)
	return u
}

// SetWardID sets the "ward_id" field.
func (u *AdmissionUpsert) SetWardID(v uuid.UUID) *AdmissionUpsert {
	u.Set(admission.FieldWardID, v)
	return u
}

// UpdateWardID sets the "ward_id" field to the value that was provided on create.
func (u *AdmissionUpsert) UpdateWardID() *AdmissionUpsert {
	u.SetExcluded(admission.FieldWardID)
	return u
}

// SetBedID sets the "bed_id" field.
func (u *AdmissionUpsert) SetBedID(v uuid.UUID) *AdmissionUpsert {
	u.Set(admission.FieldBedID, v)
	return u
}

// UpdateBedID sets the "bed_id" field to the value that was provided on create.
func (u *AdmissionUpsert) UpdateBedID() *AdmissionUpsert {
	u.SetExcluded(admission.FieldBedID)
	return u
}

// SetStatus sets the "status" field.
func (u *AdmissionUpsert) SetStatus(v admission.Status) *AdmissionUpsert {
	u.Set(admission.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AdmissionUpsert) UpdateStatus() *AdmissionUpsert {
	u.SetExcluded(admission.FieldStatus)
	return u
}

// SetAdmittedBy sets the "admitted_by" field.
func (u *AdmissionUpsert) SetAdmittedBy(v uuid.UUID) *AdmissionUpsert {
	u.Set(admission.FieldAdmittedBy, v)
	return u
}

// UpdateAdmittedBy sets the "admitted_by" field to the value that was provided on create.
func (u *AdmissionUpsert) UpdateAdmittedBy() *AdmissionUpsert {
	u.SetExcluded(admission.FieldAdmittedBy)
	return u
}

// ClearAdmittedBy clears the value of the "admitted_by" field.
func (u *AdmissionUpsert) ClearAdmittedBy() *AdmissionUpsert {
	u.SetNull(admission.FieldAdmittedBy)
	return u
}

// SetDischargedAt sets the "discharged_at" field.
func (u *AdmissionUpsert) SetDischargedAt(v time.Time) *AdmissionUpsert {
	u.Set(admission.FieldDischargedAt, v)
	return u
}

// UpdateDischargedAt sets the "discharged_at" field to the value that was provided on create.
func (u *AdmissionUpsert) UpdateDischargedAt() *AdmissionUpsert {
	u.SetExcluded(admission.FieldDischargedAt)
	return u
}

// ClearDischargedAt clears the value of the "discharged_at" field.
func (u *AdmissionUpsert) ClearDischargedAt() *AdmissionUpsert {
	u.SetNull(admission.FieldDischargedAt)
	return u
}

// SetDischargedBy sets the "discharged_by" field.
func (u *AdmissionUpsert) SetDischargedBy(v uuid.UUID) *AdmissionUpsert {
	u.Set(admission.FieldDischargedBy, v)
	return u
}

// UpdateDischargedBy sets the "discharged_by" field to the value that was provided on create.
func (u *AdmissionUpsert) UpdateDischargedBy() *AdmissionUpsert {
	u.SetExcluded(admission.FieldDischargedBy)
	return u
}

// ClearDischargedBy clears the value of the "discharged_by" field.
func (u *AdmissionUpsert) ClearDischargedBy() *AdmissionUpsert {
	u.SetNull(admission.FieldDischargedBy)
	return u
}

// SetDischargeSummary sets the "discharge_summary" field.
func (u *AdmissionUpsert) SetDischargeSummary(v string) *AdmissionUpsert {
	u.Set(admission.FieldDischargeSummary, v)
	return u
}

// UpdateDischargeSummary sets the "discharge_summary" field to the value that was provided on create.
func (u *AdmissionUpsert) UpdateDischargeSummary() *AdmissionUpsert {
	u.SetExcluded(admission.FieldDischargeSummary)
	return u
}

// ClearDischargeSummary clears the value of the "discharge_summary" field.
func (u *AdmissionUpsert) ClearDischargeSummary() *AdmissionUpsert {
	u.SetNull(admission.FieldDischargeSummary)
	return u
}

// SetWardChargePosted sets the "ward_charge_posted" field.
func (u *AdmissionUpsert) SetWardChargePosted(v bool) *AdmissionUpsert {
	u.Set(admission.FieldWardChargePosted, v)
	return u
}

// UpdateWardChargePosted sets the "ward_charge_posted" field to the value that was provided on create.
func (u *AdmissionUpsert) UpdateWardChargePosted() *AdmissionUpsert {
	u.SetExcluded(admission.FieldWardChargePosted)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AdmissionUpsert) SetUpdatedAt(v time.Time) *AdmissionUpsert {
	u.Set(admission.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdmissionUpsert) UpdateUpdatedAt() *AdmissionUpsert {
	u.SetExcluded(admission.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Admission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(admission.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AdmissionUpsertOne) UpdateNewValues() *AdmissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(admission.FieldID)
		}
		if _, exists := u.create.mutation.AdmittedAt(); exists {
			s.SetIgnore(admission.FieldAdmittedAt)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(admission.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Admission.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AdmissionUpsertOne) Ignore() *AdmissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdmissionUpsertOne) DoNothing() *AdmissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdmissionCreate.OnConflict
// documentation for more info.
func (u *AdmissionUpsertOne) Update(set func(*AdmissionUpsert)) *AdmissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdmissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *AdmissionUpsertOne) SetTenantID(v uuid.UUID) *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *AdmissionUpsertOne) UpdateTenantID() *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateTenantID()
	})
}

// SetOutletID sets the "outlet_id" field.
func (u *AdmissionUpsertOne) SetOutletID(v uuid.UUID) *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetOutletID(v)
	})
}

// UpdateOutletID sets the "outlet_id" field to the value that was provided on create.
func (u *AdmissionUpsertOne) UpdateOutletID() *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateOutletID()
	})
}

// SetPatientVisitID sets the "patient_visit_id" field.
func (u *AdmissionUpsertOne) SetPatientVisitID(v uuid.UUID) *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetPatientVisitID(v)
	})
}

// UpdatePatientVisitID sets the "patient_visit_id" field to the value that was provided on create.
func (u *AdmissionUpsertOne) UpdatePatientVisitID() *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdatePatientVisitID()
	})
}

// SetPatientID sets the "patient_id" field.
func (u *AdmissionUpsertOne) SetPatientID(v uuid.UUID) *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetPatientID(v)
	})
}

// UpdatePatientID sets the "patient_id" field to the value that was provided on create.
func (u *AdmissionUpsertOne) UpdatePatientID() *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdatePatientID()
	})
}

// SetAdmissionNumber sets the "admission_number" field.
func (u *AdmissionUpsertOne) SetAdmissionNumber(v string) *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetAdmissionNumber(v)
	})
}

// UpdateAdmissionNumber sets the "admission_number" field to the value that was provided on create.
func (u *AdmissionUpsertOne) UpdateAdmissionNumber() *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateAdmissionNumber()
	})
}

// SetWardID sets the "ward_id" field.
func (u *AdmissionUpsertOne) SetWardID(v uuid.UUID) *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetWardID(v)
	})
}

// UpdateWardID sets the "ward_id" field to the value that was provided on create.
func (u *AdmissionUpsertOne) UpdateWardID() *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateWardID()
	})
}

// SetBedID sets the "bed_id" field.
func (u *AdmissionUpsertOne) SetBedID(v uuid.UUID) *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetBedID(v)
	})
}

// UpdateBedID sets the "bed_id" field to the value that was provided on create.
func (u *AdmissionUpsertOne) UpdateBedID() *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateBedID()
	})
}

// SetStatus sets the "status" field.
func (u *AdmissionUpsertOne) SetStatus(v admission.Status) *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AdmissionUpsertOne) UpdateStatus() *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateStatus()
	})
}

// SetAdmittedBy sets the "admitted_by" field.
func (u *AdmissionUpsertOne) SetAdmittedBy(v uuid.UUID) *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetAdmittedBy(v)
	})
}

// UpdateAdmittedBy sets the "admitted_by" field to the value that was provided on create.
func (u *AdmissionUpsertOne) UpdateAdmittedBy() *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateAdmittedBy()
	})
}

// ClearAdmittedBy clears the value of the "admitted_by" field.
func (u *AdmissionUpsertOne) ClearAdmittedBy() *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.ClearAdmittedBy()
	})
}

// SetDischargedAt sets the "discharged_at" field.
func (u *AdmissionUpsertOne) SetDischargedAt(v time.Time) *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetDischargedAt(v)
	})
}

// UpdateDischargedAt sets the "discharged_at" field to the value that was provided on create.
func (u *AdmissionUpsertOne) UpdateDischargedAt() *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateDischargedAt()
	})
}

// ClearDischargedAt clears the value of the "discharged_at" field.
func (u *AdmissionUpsertOne) ClearDischargedAt() *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.ClearDischargedAt()
	})
}

// SetDischargedBy sets the "discharged_by" field.
func (u *AdmissionUpsertOne) SetDischargedBy(v uuid.UUID) *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetDischargedBy(v)
	})
}

// UpdateDischargedBy sets the "discharged_by" field to the value that was provided on create.
func (u *AdmissionUpsertOne) UpdateDischargedBy() *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateDischargedBy()
	})
}

// ClearDischargedBy clears the value of the "discharged_by" field.
func (u *AdmissionUpsertOne) ClearDischargedBy() *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.ClearDischargedBy()
	})
}

// SetDischargeSummary sets the "discharge_summary" field.
func (u *AdmissionUpsertOne) SetDischargeSummary(v string) *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetDischargeSummary(v)
	})
}

// UpdateDischargeSummary sets the "discharge_summary" field to the value that was provided on create.
func (u *AdmissionUpsertOne) UpdateDischargeSummary() *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateDischargeSummary()
	})
}

// ClearDischargeSummary clears the value of the "discharge_summary" field.
func (u *AdmissionUpsertOne) ClearDischargeSummary() *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.ClearDischargeSummary()
	})
}

// SetWardChargePosted sets the "ward_charge_posted" field.
func (u *AdmissionUpsertOne) SetWardChargePosted(v bool) *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetWardChargePosted(v)
	})
}

// UpdateWardChargePosted sets the "ward_charge_posted" field to the value that was provided on create.
func (u *AdmissionUpsertOne) UpdateWardChargePosted() *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateWardChargePosted()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AdmissionUpsertOne) SetUpdatedAt(v time.Time) *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdmissionUpsertOne) UpdateUpdatedAt() *AdmissionUpsertOne {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AdmissionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdmissionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdmissionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AdmissionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AdmissionUpsertOne.ID is not supported by MySQL driver. Use AdmissionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AdmissionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AdmissionCreateBulk is the builder for creating many Admission entities in bulk.
type AdmissionCreateBulk struct {
	config
	err      error
	builders []*AdmissionCreate
	conflict []sql.ConflictOption
}

// Save creates the Admission entities in the database.
func (_c *AdmissionCreateBulk) Save(ctx context.Context) ([]*Admission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Admission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdmissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdmissionCreateBulk) SaveX(ctx context.Context) []*Admission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdmissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdmissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Admission.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdmissionUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *AdmissionCreateBulk) OnConflict(opts ...sql.ConflictOption) *AdmissionUpsertBulk {
	_c.conflict = opts
	return &AdmissionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Admission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdmissionCreateBulk) OnConflictColumns(columns ...string) *AdmissionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdmissionUpsertBulk{
		create: _c,
	}
}

// AdmissionUpsertBulk is the builder for "upsert"-ing
// a bulk of Admission nodes.
type AdmissionUpsertBulk struct {
	create *AdmissionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Admission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(admission.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AdmissionUpsertBulk) UpdateNewValues() *AdmissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(admission.FieldID)
			}
			if _, exists := b.mutation.AdmittedAt(); exists {
				s.SetIgnore(admission.FieldAdmittedAt)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(admission.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Admission.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AdmissionUpsertBulk) Ignore() *AdmissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdmissionUpsertBulk) DoNothing() *AdmissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdmissionCreateBulk.OnConflict
// documentation for more info.
func (u *AdmissionUpsertBulk) Update(set func(*AdmissionUpsert)) *AdmissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdmissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *AdmissionUpsertBulk) SetTenantID(v uuid.UUID) *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *AdmissionUpsertBulk) UpdateTenantID() *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateTenantID()
	})
}

// SetOutletID sets the "outlet_id" field.
func (u *AdmissionUpsertBulk) SetOutletID(v uuid.UUID) *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetOutletID(v)
	})
}

// UpdateOutletID sets the "outlet_id" field to the value that was provided on create.
func (u *AdmissionUpsertBulk) UpdateOutletID() *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateOutletID()
	})
}

// SetPatientVisitID sets the "patient_visit_id" field.
func (u *AdmissionUpsertBulk) SetPatientVisitID(v uuid.UUID) *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetPatientVisitID(v)
	})
}

// UpdatePatientVisitID sets the "patient_visit_id" field to the value that was provided on create.
func (u *AdmissionUpsertBulk) UpdatePatientVisitID() *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdatePatientVisitID()
	})
}

// SetPatientID sets the "patient_id" field.
func (u *AdmissionUpsertBulk) SetPatientID(v uuid.UUID) *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetPatientID(v)
	})
}

// UpdatePatientID sets the "patient_id" field to the value that was provided on create.
func (u *AdmissionUpsertBulk) UpdatePatientID() *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdatePatientID()
	})
}

// SetAdmissionNumber sets the "admission_number" field.
func (u *AdmissionUpsertBulk) SetAdmissionNumber(v string) *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetAdmissionNumber(v)
	})
}

// UpdateAdmissionNumber sets the "admission_number" field to the value that was provided on create.
func (u *AdmissionUpsertBulk) UpdateAdmissionNumber() *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateAdmissionNumber()
	})
}

// SetWardID sets the "ward_id" field.
func (u *AdmissionUpsertBulk) SetWardID(v uuid.UUID) *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetWardID(v)
	})
}

// UpdateWardID sets the "ward_id" field to the value that was provided on create.
func (u *AdmissionUpsertBulk) UpdateWardID() *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateWardID()
	})
}

// SetBedID sets the "bed_id" field.
func (u *AdmissionUpsertBulk) SetBedID(v uuid.UUID) *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetBedID(v)
	})
}

// UpdateBedID sets the "bed_id" field to the value that was provided on create.
func (u *AdmissionUpsertBulk) UpdateBedID() *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateBedID()
	})
}

// SetStatus sets the "status" field.
func (u *AdmissionUpsertBulk) SetStatus(v admission.Status) *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AdmissionUpsertBulk) UpdateStatus() *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateStatus()
	})
}

// SetAdmittedBy sets the "admitted_by" field.
func (u *AdmissionUpsertBulk) SetAdmittedBy(v uuid.UUID) *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetAdmittedBy(v)
	})
}

// UpdateAdmittedBy sets the "admitted_by" field to the value that was provided on create.
func (u *AdmissionUpsertBulk) UpdateAdmittedBy() *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateAdmittedBy()
	})
}

// ClearAdmittedBy clears the value of the "admitted_by" field.
func (u *AdmissionUpsertBulk) ClearAdmittedBy() *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.ClearAdmittedBy()
	})
}

// SetDischargedAt sets the "discharged_at" field.
func (u *AdmissionUpsertBulk) SetDischargedAt(v time.Time) *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetDischargedAt(v)
	})
}

// UpdateDischargedAt sets the "discharged_at" field to the value that was provided on create.
func (u *AdmissionUpsertBulk) UpdateDischargedAt() *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateDischargedAt()
	})
}

// ClearDischargedAt clears the value of the "discharged_at" field.
func (u *AdmissionUpsertBulk) ClearDischargedAt() *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.ClearDischargedAt()
	})
}

// SetDischargedBy sets the "discharged_by" field.
func (u *AdmissionUpsertBulk) SetDischargedBy(v uuid.UUID) *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetDischargedBy(v)
	})
}

// UpdateDischargedBy sets the "discharged_by" field to the value that was provided on create.
func (u *AdmissionUpsertBulk) UpdateDischargedBy() *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateDischargedBy()
	})
}

// ClearDischargedBy clears the value of the "discharged_by" field.
func (u *AdmissionUpsertBulk) ClearDischargedBy() *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.ClearDischargedBy()
	})
}

// SetDischargeSummary sets the "discharge_summary" field.
func (u *AdmissionUpsertBulk) SetDischargeSummary(v string) *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetDischargeSummary(v)
	})
}

// UpdateDischargeSummary sets the "discharge_summary" field to the value that was provided on create.
func (u *AdmissionUpsertBulk) UpdateDischargeSummary() *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateDischargeSummary()
	})
}

// ClearDischargeSummary clears the value of the "discharge_summary" field.
func (u *AdmissionUpsertBulk) ClearDischargeSummary() *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.ClearDischargeSummary()
	})
}

// SetWardChargePosted sets the "ward_charge_posted" field.
func (u *AdmissionUpsertBulk) SetWardChargePosted(v bool) *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetWardChargePosted(v)
	})
}

// UpdateWardChargePosted sets the "ward_charge_posted" field to the value that was provided on create.
func (u *AdmissionUpsertBulk) UpdateWardChargePosted() *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateWardChargePosted()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AdmissionUpsertBulk) SetUpdatedAt(v time.Time) *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdmissionUpsertBulk) UpdateUpdatedAt() *AdmissionUpsertBulk {
	return u.Update(func(s *AdmissionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AdmissionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AdmissionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdmissionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdmissionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
