// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/hospital-service/internal/ent/admission"
	"github.com/bengobox/hospital-service/internal/ent/bed"
	"github.com/bengobox/hospital-service/internal/ent/patientvisit"
	"github.com/bengobox/hospital-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// AdmissionQuery is the builder for querying Admission entities.
type AdmissionQuery struct {
	config
	ctx        *QueryContext
	order      []admission.OrderOption
	inters     []Interceptor
	predicates []predicate.Admission
	withVisit  *PatientVisitQuery
	withBed    *BedQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AdmissionQuery builder.
func (_q *AdmissionQuery) Where(ps ...predicate.Admission) *AdmissionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AdmissionQuery) Limit(limit int) *AdmissionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AdmissionQuery) Offset(offset int) *AdmissionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AdmissionQuery) Unique(unique bool) *AdmissionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AdmissionQuery) Order(o ...admission.OrderOption) *AdmissionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryVisit chains the current query on the "visit" edge.
func (_q *AdmissionQuery) QueryVisit() *PatientVisitQuery {
	query := (&PatientVisitClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(admission.Table, admission.FieldID, selector),
			sqlgraph.To(patientvisit.Table, patientvisit.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, admission.VisitTable, admission.VisitColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBed chains the current query on the "bed" edge.
func (_q *AdmissionQuery) QueryBed() *BedQuery {
	query := (&BedClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(admission.Table, admission.FieldID, selector),
			sqlgraph.To(bed.Table, bed.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, admission.BedTable, admission.BedColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Admission entity from the query.
// Returns a *NotFoundError when no Admission was found.
func (_q *AdmissionQuery) First(ctx context.Context) (*Admission, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{admission.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AdmissionQuery) FirstX(ctx context.Context) *Admission {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Admission ID from the query.
// Returns a *NotFoundError when no Admission ID was found.
func (_q *AdmissionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{admission.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AdmissionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Admission entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Admission entity is found.
// Returns a *NotFoundError when no Admission entities are found.
func (_q *AdmissionQuery) Only(ctx context.Context) (*Admission, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{admission.Label}
	default:
		return nil, &NotSingularError{admission.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AdmissionQuery) OnlyX(ctx context.Context) *Admission {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Admission ID in the query.
// Returns a *NotSingularError when more than one Admission ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AdmissionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{admission.Label}
	default:
		err = &NotSingularError{admission.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AdmissionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Admissions.
func (_q *AdmissionQuery) All(ctx context.Context) ([]*Admission, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Admission, *AdmissionQuery]()
	return withInterceptors[[]*Admission](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AdmissionQuery) AllX(ctx context.Context) []*Admission {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Admission IDs.
func (_q *AdmissionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(admission.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AdmissionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AdmissionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AdmissionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AdmissionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AdmissionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AdmissionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AdmissionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AdmissionQuery) Clone() *AdmissionQuery {
	if _q == nil {
		return nil
	}
	return &AdmissionQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]admission.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.Admission{}, _q.predicates...),
		withVisit:  _q.withVisit.Clone(),
		withBed:    _q.withBed.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithVisit tells the query-builder to eager-load the nodes that are connected to
// the "visit" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AdmissionQuery) WithVisit(opts ...func(*PatientVisitQuery)) *AdmissionQuery {
	query := (&PatientVisitClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withVisit = query
	return _q
}

// WithBed tells the query-builder to eager-load the nodes that are connected to
// the "bed" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AdmissionQuery) WithBed(opts ...func(*BedQuery)) *AdmissionQuery {
	query := (&BedClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBed = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID uuid.UUID `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Admission.Query().
//		GroupBy(admission.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AdmissionQuery) GroupBy(field string, fields ...string) *AdmissionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AdmissionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = admission.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID uuid.UUID `json:"tenant_id,omitempty"`
//	}
//
//	client.Admission.Query().
//		Select(admission.FieldTenantID).
//		Scan(ctx, &v)
func (_q *AdmissionQuery) Select(fields ...string) *AdmissionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AdmissionSelect{AdmissionQuery: _q}
	sbuild.label = admission.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AdmissionSelect configured with the given aggregations.
func (_q *AdmissionQuery) Aggregate(fns ...AggregateFunc) *AdmissionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AdmissionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !admission.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AdmissionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Admission, error) {
	var (
		nodes       = []*Admission{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withVisit != nil,
			_q.withBed != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Admission).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Admission{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withVisit; query != nil {
		if err := _q.loadVisit(ctx, query, nodes, nil,
			func(n *Admission, e *PatientVisit) { n.Edges.Visit = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withBed; query != nil {
		if err := _q.loadBed(ctx, query, nodes, nil,
			func(n *Admission, e *Bed) { n.Edges.Bed = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AdmissionQuery) loadVisit(ctx context.Context, query *PatientVisitQuery, nodes []*Admission, init func(*Admission), assign func(*Admission, *PatientVisit)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Admission)
	for i := range nodes {
		fk := nodes[i].PatientVisitID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(patientvisit.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "patient_visit_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AdmissionQuery) loadBed(ctx context.Context, query *BedQuery, nodes []*Admission, init func(*Admission), assign func(*Admission, *Bed)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Admission)
	for i := range nodes {
		fk := nodes[i].BedID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(bed.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "bed_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *AdmissionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AdmissionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(admission.Table, admission.Columns, sqlgraph.NewFieldSpec(admission.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, admission.FieldID)
		for i := range fields {
			if fields[i] != admission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withVisit != nil {
			_spec.Node.AddColumnOnce(admission.FieldPatientVisitID)
		}
		if _q.withBed != nil {
			_spec.Node.AddColumnOnce(admission.FieldBedID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AdmissionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(admission.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = admission.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *AdmissionQuery) ForUpdate(opts ...sql.LockOption) *AdmissionQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *AdmissionQuery) ForShare(opts ...sql.LockOption) *AdmissionQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// AdmissionGroupBy is the group-by builder for Admission entities.
type AdmissionGroupBy struct {
	selector
	build *AdmissionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AdmissionGroupBy) Aggregate(fns ...AggregateFunc) *AdmissionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AdmissionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdmissionQuery, *AdmissionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AdmissionGroupBy) sqlScan(ctx context.Context, root *AdmissionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AdmissionSelect is the builder for selecting fields of Admission entities.
type AdmissionSelect struct {
	*AdmissionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AdmissionSelect) Aggregate(fns ...AggregateFunc) *AdmissionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AdmissionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdmissionQuery, *AdmissionSelect](ctx, _s.AdmissionQuery, _s, _s.inters, v)
}

func (_s *AdmissionSelect) sqlScan(ctx context.Context, root *AdmissionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
