// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/hospital-service/internal/ent/billablecharge"
	"github.com/bengobox/hospital-service/internal/ent/patientaccount"
	"github.com/google/uuid"
)

// BillableCharge is the model entity for the BillableCharge schema.
type BillableCharge struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// PatientAccountID holds the value of the "patient_account_id" field.
	PatientAccountID uuid.UUID `json:"patient_account_id,omitempty"`
	// Nil = a free-form charge not tied to a BillableItemCatalog row
	BillableItemID *uuid.UUID `json:"billable_item_id,omitempty"`
	// records|triage|consultation|lab|pharmacy|theatre|inpatient — which department billed this
	SourceModule string `json:"source_module,omitempty"`
	// The LabOrder/Prescription/Admission/etc. that generated this charge
	SourceReferenceID *uuid.UUID `json:"source_reference_id,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// Status holds the value of the "status" field.
	Status billablecharge.Status `json:"status,omitempty"`
	// TreasuryInvoiceID holds the value of the "treasury_invoice_id" field.
	TreasuryInvoiceID *uuid.UUID `json:"treasury_invoice_id,omitempty"`
	// TreasuryPaymentIntentID holds the value of the "treasury_payment_intent_id" field.
	TreasuryPaymentIntentID *uuid.UUID `json:"treasury_payment_intent_id,omitempty"`
	// CreatedByUserID holds the value of the "created_by_user_id" field.
	CreatedByUserID *uuid.UUID `json:"created_by_user_id,omitempty"`
	// PaidAt holds the value of the "paid_at" field.
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BillableChargeQuery when eager-loading is set.
	Edges        BillableChargeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BillableChargeEdges holds the relations/edges for other nodes in the graph.
type BillableChargeEdges struct {
	// Account holds the value of the account edge.
	Account *PatientAccount `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BillableChargeEdges) AccountOrErr() (*PatientAccount, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: patientaccount.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BillableCharge) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case billablecharge.FieldBillableItemID, billablecharge.FieldSourceReferenceID, billablecharge.FieldTreasuryInvoiceID, billablecharge.FieldTreasuryPaymentIntentID, billablecharge.FieldCreatedByUserID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case billablecharge.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case billablecharge.FieldSourceModule, billablecharge.FieldDescription, billablecharge.FieldStatus:
			values[i] = new(sql.NullString)
		case billablecharge.FieldPaidAt, billablecharge.FieldCreatedAt, billablecharge.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case billablecharge.FieldID, billablecharge.FieldTenantID, billablecharge.FieldPatientAccountID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BillableCharge fields.
func (_m *BillableCharge) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case billablecharge.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case billablecharge.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case billablecharge.FieldPatientAccountID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field patient_account_id", values[i])
			} else if value != nil {
				_m.PatientAccountID = *value
			}
		case billablecharge.FieldBillableItemID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field billable_item_id", values[i])
			} else if value.Valid {
				_m.BillableItemID = new(uuid.UUID)
				*_m.BillableItemID = *value.S.(*uuid.UUID)
			}
		case billablecharge.FieldSourceModule:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_module", values[i])
			} else if value.Valid {
				_m.SourceModule = value.String
			}
		case billablecharge.FieldSourceReferenceID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field source_reference_id", values[i])
			} else if value.Valid {
				_m.SourceReferenceID = new(uuid.UUID)
				*_m.SourceReferenceID = *value.S.(*uuid.UUID)
			}
		case billablecharge.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case billablecharge.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case billablecharge.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = billablecharge.Status(value.String)
			}
		case billablecharge.FieldTreasuryInvoiceID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field treasury_invoice_id", values[i])
			} else if value.Valid {
				_m.TreasuryInvoiceID = new(uuid.UUID)
				*_m.TreasuryInvoiceID = *value.S.(*uuid.UUID)
			}
		case billablecharge.FieldTreasuryPaymentIntentID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field treasury_payment_intent_id", values[i])
			} else if value.Valid {
				_m.TreasuryPaymentIntentID = new(uuid.UUID)
				*_m.TreasuryPaymentIntentID = *value.S.(*uuid.UUID)
			}
		case billablecharge.FieldCreatedByUserID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_user_id", values[i])
			} else if value.Valid {
				_m.CreatedByUserID = new(uuid.UUID)
				*_m.CreatedByUserID = *value.S.(*uuid.UUID)
			}
		case billablecharge.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		case billablecharge.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case billablecharge.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BillableCharge.
// This includes values selected through modifiers, order, etc.
func (_m *BillableCharge) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the BillableCharge entity.
func (_m *BillableCharge) QueryAccount() *PatientAccountQuery {
	return NewBillableChargeClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this BillableCharge.
// Note that you need to call BillableCharge.Unwrap() before calling this method if this BillableCharge
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BillableCharge) Update() *BillableChargeUpdateOne {
	return NewBillableChargeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BillableCharge entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BillableCharge) Unwrap() *BillableCharge {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BillableCharge is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BillableCharge) String() string {
	var builder strings.Builder
	builder.WriteString("BillableCharge(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("patient_account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PatientAccountID))
	builder.WriteString(", ")
	if v := _m.BillableItemID; v != nil {
		builder.WriteString("billable_item_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("source_module=")
	builder.WriteString(_m.SourceModule)
	builder.WriteString(", ")
	if v := _m.SourceReferenceID; v != nil {
		builder.WriteString("source_reference_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.TreasuryInvoiceID; v != nil {
		builder.WriteString("treasury_invoice_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TreasuryPaymentIntentID; v != nil {
		builder.WriteString("treasury_payment_intent_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreatedByUserID; v != nil {
		builder.WriteString("created_by_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BillableCharges is a parsable slice of BillableCharge.
type BillableCharges []*BillableCharge
