// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/hospital-service/internal/ent/diagnosiscatalogentry"
	"github.com/google/uuid"
)

// DiagnosisCatalogEntryCreate is the builder for creating a DiagnosisCatalogEntry entity.
type DiagnosisCatalogEntryCreate struct {
	config
	mutation *DiagnosisCatalogEntryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *DiagnosisCatalogEntryCreate) SetTenantID(v uuid.UUID) *DiagnosisCatalogEntryCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *DiagnosisCatalogEntryCreate) SetCode(v string) *DiagnosisCatalogEntryCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *DiagnosisCatalogEntryCreate) SetName(v string) *DiagnosisCatalogEntryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *DiagnosisCatalogEntryCreate) SetCategory(v string) *DiagnosisCatalogEntryCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *DiagnosisCatalogEntryCreate) SetNillableCategory(v *string) *DiagnosisCatalogEntryCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *DiagnosisCatalogEntryCreate) SetIsActive(v bool) *DiagnosisCatalogEntryCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *DiagnosisCatalogEntryCreate) SetNillableIsActive(v *bool) *DiagnosisCatalogEntryCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DiagnosisCatalogEntryCreate) SetCreatedAt(v time.Time) *DiagnosisCatalogEntryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DiagnosisCatalogEntryCreate) SetNillableCreatedAt(v *time.Time) *DiagnosisCatalogEntryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DiagnosisCatalogEntryCreate) SetUpdatedAt(v time.Time) *DiagnosisCatalogEntryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DiagnosisCatalogEntryCreate) SetNillableUpdatedAt(v *time.Time) *DiagnosisCatalogEntryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DiagnosisCatalogEntryCreate) SetID(v uuid.UUID) *DiagnosisCatalogEntryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DiagnosisCatalogEntryCreate) SetNillableID(v *uuid.UUID) *DiagnosisCatalogEntryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the DiagnosisCatalogEntryMutation object of the builder.
func (_c *DiagnosisCatalogEntryCreate) Mutation() *DiagnosisCatalogEntryMutation {
	return _c.mutation
}

// Save creates the DiagnosisCatalogEntry in the database.
func (_c *DiagnosisCatalogEntryCreate) Save(ctx context.Context) (*DiagnosisCatalogEntry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DiagnosisCatalogEntryCreate) SaveX(ctx context.Context) *DiagnosisCatalogEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiagnosisCatalogEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiagnosisCatalogEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DiagnosisCatalogEntryCreate) defaults() {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := diagnosiscatalogentry.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := diagnosiscatalogentry.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := diagnosiscatalogentry.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := diagnosiscatalogentry.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DiagnosisCatalogEntryCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "DiagnosisCatalogEntry.tenant_id"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "DiagnosisCatalogEntry.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := diagnosiscatalogentry.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "DiagnosisCatalogEntry.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DiagnosisCatalogEntry.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := diagnosiscatalogentry.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DiagnosisCatalogEntry.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "DiagnosisCatalogEntry.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DiagnosisCatalogEntry.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DiagnosisCatalogEntry.updated_at"`)}
	}
	return nil
}

func (_c *DiagnosisCatalogEntryCreate) sqlSave(ctx context.Context) (*DiagnosisCatalogEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DiagnosisCatalogEntryCreate) createSpec() (*DiagnosisCatalogEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &DiagnosisCatalogEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(diagnosiscatalogentry.Table, sqlgraph.NewFieldSpec(diagnosiscatalogentry.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(diagnosiscatalogentry.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(diagnosiscatalogentry.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(diagnosiscatalogentry.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(diagnosiscatalogentry.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(diagnosiscatalogentry.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(diagnosiscatalogentry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(diagnosiscatalogentry.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DiagnosisCatalogEntry.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DiagnosisCatalogEntryUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *DiagnosisCatalogEntryCreate) OnConflict(opts ...sql.ConflictOption) *DiagnosisCatalogEntryUpsertOne {
	_c.conflict = opts
	return &DiagnosisCatalogEntryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DiagnosisCatalogEntry.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DiagnosisCatalogEntryCreate) OnConflictColumns(columns ...string) *DiagnosisCatalogEntryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DiagnosisCatalogEntryUpsertOne{
		create: _c,
	}
}

type (
	// DiagnosisCatalogEntryUpsertOne is the builder for "upsert"-ing
	//  one DiagnosisCatalogEntry node.
	DiagnosisCatalogEntryUpsertOne struct {
		create *DiagnosisCatalogEntryCreate
	}

	// DiagnosisCatalogEntryUpsert is the "OnConflict" setter.
	DiagnosisCatalogEntryUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *DiagnosisCatalogEntryUpsert) SetTenantID(v uuid.UUID) *DiagnosisCatalogEntryUpsert {
	u.Set(diagnosiscatalogentry.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *DiagnosisCatalogEntryUpsert) UpdateTenantID() *DiagnosisCatalogEntryUpsert {
	u.SetExcluded(diagnosiscatalogentry.FieldTenantID)
	return u
}

// SetCode sets the "code" field.
func (u *DiagnosisCatalogEntryUpsert) SetCode(v string) *DiagnosisCatalogEntryUpsert {
	u.Set(diagnosiscatalogentry.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *DiagnosisCatalogEntryUpsert) UpdateCode() *DiagnosisCatalogEntryUpsert {
	u.SetExcluded(diagnosiscatalogentry.FieldCode)
	return u
}

// SetName sets the "name" field.
func (u *DiagnosisCatalogEntryUpsert) SetName(v string) *DiagnosisCatalogEntryUpsert {
	u.Set(diagnosiscatalogentry.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DiagnosisCatalogEntryUpsert) UpdateName() *DiagnosisCatalogEntryUpsert {
	u.SetExcluded(diagnosiscatalogentry.FieldName)
	return u
}

// SetCategory sets the "category" field.
func (u *DiagnosisCatalogEntryUpsert) SetCategory(v string) *DiagnosisCatalogEntryUpsert {
	u.Set(diagnosiscatalogentry.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *DiagnosisCatalogEntryUpsert) UpdateCategory() *DiagnosisCatalogEntryUpsert {
	u.SetExcluded(diagnosiscatalogentry.FieldCategory)
	return u
}

// ClearCategory clears the value of the "category" field.
func (u *DiagnosisCatalogEntryUpsert) ClearCategory() *DiagnosisCatalogEntryUpsert {
	u.SetNull(diagnosiscatalogentry.FieldCategory)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *DiagnosisCatalogEntryUpsert) SetIsActive(v bool) *DiagnosisCatalogEntryUpsert {
	u.Set(diagnosiscatalogentry.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *DiagnosisCatalogEntryUpsert) UpdateIsActive() *DiagnosisCatalogEntryUpsert {
	u.SetExcluded(diagnosiscatalogentry.FieldIsActive)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DiagnosisCatalogEntryUpsert) SetUpdatedAt(v time.Time) *DiagnosisCatalogEntryUpsert {
	u.Set(diagnosiscatalogentry.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DiagnosisCatalogEntryUpsert) UpdateUpdatedAt() *DiagnosisCatalogEntryUpsert {
	u.SetExcluded(diagnosiscatalogentry.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DiagnosisCatalogEntry.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(diagnosiscatalogentry.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DiagnosisCatalogEntryUpsertOne) UpdateNewValues() *DiagnosisCatalogEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(diagnosiscatalogentry.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(diagnosiscatalogentry.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DiagnosisCatalogEntry.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DiagnosisCatalogEntryUpsertOne) Ignore() *DiagnosisCatalogEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DiagnosisCatalogEntryUpsertOne) DoNothing() *DiagnosisCatalogEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DiagnosisCatalogEntryCreate.OnConflict
// documentation for more info.
func (u *DiagnosisCatalogEntryUpsertOne) Update(set func(*DiagnosisCatalogEntryUpsert)) *DiagnosisCatalogEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DiagnosisCatalogEntryUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *DiagnosisCatalogEntryUpsertOne) SetTenantID(v uuid.UUID) *DiagnosisCatalogEntryUpsertOne {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *DiagnosisCatalogEntryUpsertOne) UpdateTenantID() *DiagnosisCatalogEntryUpsertOne {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.UpdateTenantID()
	})
}

// SetCode sets the "code" field.
func (u *DiagnosisCatalogEntryUpsertOne) SetCode(v string) *DiagnosisCatalogEntryUpsertOne {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *DiagnosisCatalogEntryUpsertOne) UpdateCode() *DiagnosisCatalogEntryUpsertOne {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *DiagnosisCatalogEntryUpsertOne) SetName(v string) *DiagnosisCatalogEntryUpsertOne {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DiagnosisCatalogEntryUpsertOne) UpdateName() *DiagnosisCatalogEntryUpsertOne {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.UpdateName()
	})
}

// SetCategory sets the "category" field.
func (u *DiagnosisCatalogEntryUpsertOne) SetCategory(v string) *DiagnosisCatalogEntryUpsertOne {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *DiagnosisCatalogEntryUpsertOne) UpdateCategory() *DiagnosisCatalogEntryUpsertOne {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.UpdateCategory()
	})
}

// ClearCategory clears the value of the "category" field.
func (u *DiagnosisCatalogEntryUpsertOne) ClearCategory() *DiagnosisCatalogEntryUpsertOne {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.ClearCategory()
	})
}

// SetIsActive sets the "is_active" field.
func (u *DiagnosisCatalogEntryUpsertOne) SetIsActive(v bool) *DiagnosisCatalogEntryUpsertOne {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *DiagnosisCatalogEntryUpsertOne) UpdateIsActive() *DiagnosisCatalogEntryUpsertOne {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.UpdateIsActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DiagnosisCatalogEntryUpsertOne) SetUpdatedAt(v time.Time) *DiagnosisCatalogEntryUpsertOne {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DiagnosisCatalogEntryUpsertOne) UpdateUpdatedAt() *DiagnosisCatalogEntryUpsertOne {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DiagnosisCatalogEntryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DiagnosisCatalogEntryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DiagnosisCatalogEntryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DiagnosisCatalogEntryUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DiagnosisCatalogEntryUpsertOne.ID is not supported by MySQL driver. Use DiagnosisCatalogEntryUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DiagnosisCatalogEntryUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DiagnosisCatalogEntryCreateBulk is the builder for creating many DiagnosisCatalogEntry entities in bulk.
type DiagnosisCatalogEntryCreateBulk struct {
	config
	err      error
	builders []*DiagnosisCatalogEntryCreate
	conflict []sql.ConflictOption
}

// Save creates the DiagnosisCatalogEntry entities in the database.
func (_c *DiagnosisCatalogEntryCreateBulk) Save(ctx context.Context) ([]*DiagnosisCatalogEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DiagnosisCatalogEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DiagnosisCatalogEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DiagnosisCatalogEntryCreateBulk) SaveX(ctx context.Context) []*DiagnosisCatalogEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiagnosisCatalogEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiagnosisCatalogEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DiagnosisCatalogEntry.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DiagnosisCatalogEntryUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *DiagnosisCatalogEntryCreateBulk) OnConflict(opts ...sql.ConflictOption) *DiagnosisCatalogEntryUpsertBulk {
	_c.conflict = opts
	return &DiagnosisCatalogEntryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DiagnosisCatalogEntry.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DiagnosisCatalogEntryCreateBulk) OnConflictColumns(columns ...string) *DiagnosisCatalogEntryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DiagnosisCatalogEntryUpsertBulk{
		create: _c,
	}
}

// DiagnosisCatalogEntryUpsertBulk is the builder for "upsert"-ing
// a bulk of DiagnosisCatalogEntry nodes.
type DiagnosisCatalogEntryUpsertBulk struct {
	create *DiagnosisCatalogEntryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DiagnosisCatalogEntry.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(diagnosiscatalogentry.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DiagnosisCatalogEntryUpsertBulk) UpdateNewValues() *DiagnosisCatalogEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(diagnosiscatalogentry.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(diagnosiscatalogentry.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DiagnosisCatalogEntry.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DiagnosisCatalogEntryUpsertBulk) Ignore() *DiagnosisCatalogEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DiagnosisCatalogEntryUpsertBulk) DoNothing() *DiagnosisCatalogEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DiagnosisCatalogEntryCreateBulk.OnConflict
// documentation for more info.
func (u *DiagnosisCatalogEntryUpsertBulk) Update(set func(*DiagnosisCatalogEntryUpsert)) *DiagnosisCatalogEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DiagnosisCatalogEntryUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *DiagnosisCatalogEntryUpsertBulk) SetTenantID(v uuid.UUID) *DiagnosisCatalogEntryUpsertBulk {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *DiagnosisCatalogEntryUpsertBulk) UpdateTenantID() *DiagnosisCatalogEntryUpsertBulk {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.UpdateTenantID()
	})
}

// SetCode sets the "code" field.
func (u *DiagnosisCatalogEntryUpsertBulk) SetCode(v string) *DiagnosisCatalogEntryUpsertBulk {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *DiagnosisCatalogEntryUpsertBulk) UpdateCode() *DiagnosisCatalogEntryUpsertBulk {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *DiagnosisCatalogEntryUpsertBulk) SetName(v string) *DiagnosisCatalogEntryUpsertBulk {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DiagnosisCatalogEntryUpsertBulk) UpdateName() *DiagnosisCatalogEntryUpsertBulk {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.UpdateName()
	})
}

// SetCategory sets the "category" field.
func (u *DiagnosisCatalogEntryUpsertBulk) SetCategory(v string) *DiagnosisCatalogEntryUpsertBulk {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *DiagnosisCatalogEntryUpsertBulk) UpdateCategory() *DiagnosisCatalogEntryUpsertBulk {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.UpdateCategory()
	})
}

// ClearCategory clears the value of the "category" field.
func (u *DiagnosisCatalogEntryUpsertBulk) ClearCategory() *DiagnosisCatalogEntryUpsertBulk {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.ClearCategory()
	})
}

// SetIsActive sets the "is_active" field.
func (u *DiagnosisCatalogEntryUpsertBulk) SetIsActive(v bool) *DiagnosisCatalogEntryUpsertBulk {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *DiagnosisCatalogEntryUpsertBulk) UpdateIsActive() *DiagnosisCatalogEntryUpsertBulk {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.UpdateIsActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DiagnosisCatalogEntryUpsertBulk) SetUpdatedAt(v time.Time) *DiagnosisCatalogEntryUpsertBulk {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DiagnosisCatalogEntryUpsertBulk) UpdateUpdatedAt() *DiagnosisCatalogEntryUpsertBulk {
	return u.Update(func(s *DiagnosisCatalogEntryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DiagnosisCatalogEntryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DiagnosisCatalogEntryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DiagnosisCatalogEntryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DiagnosisCatalogEntryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
