// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/hospital-service/internal/ent/hospitalpermission"
	"github.com/bengobox/hospital-service/internal/ent/hospitalrole"
	"github.com/bengobox/hospital-service/internal/ent/predicate"
	"github.com/bengobox/hospital-service/internal/ent/rolepermission"
	"github.com/bengobox/hospital-service/internal/ent/userroleassignment"
	"github.com/google/uuid"
)

// HospitalRoleUpdate is the builder for updating HospitalRole entities.
type HospitalRoleUpdate struct {
	config
	hooks    []Hook
	mutation *HospitalRoleMutation
}

// Where appends a list predicates to the HospitalRoleUpdate builder.
func (_u *HospitalRoleUpdate) Where(ps ...predicate.HospitalRole) *HospitalRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *HospitalRoleUpdate) SetTenantID(v uuid.UUID) *HospitalRoleUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *HospitalRoleUpdate) SetNillableTenantID(v *uuid.UUID) *HospitalRoleUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *HospitalRoleUpdate) ClearTenantID() *HospitalRoleUpdate {
	_u.mutation.ClearTenantID()
	return _u
}

// SetRoleCode sets the "role_code" field.
func (_u *HospitalRoleUpdate) SetRoleCode(v string) *HospitalRoleUpdate {
	_u.mutation.SetRoleCode(v)
	return _u
}

// SetNillableRoleCode sets the "role_code" field if the given value is not nil.
func (_u *HospitalRoleUpdate) SetNillableRoleCode(v *string) *HospitalRoleUpdate {
	if v != nil {
		_u.SetRoleCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *HospitalRoleUpdate) SetName(v string) *HospitalRoleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HospitalRoleUpdate) SetNillableName(v *string) *HospitalRoleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *HospitalRoleUpdate) SetDescription(v string) *HospitalRoleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *HospitalRoleUpdate) SetNillableDescription(v *string) *HospitalRoleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *HospitalRoleUpdate) ClearDescription() *HospitalRoleUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetIsSystemRole sets the "is_system_role" field.
func (_u *HospitalRoleUpdate) SetIsSystemRole(v bool) *HospitalRoleUpdate {
	_u.mutation.SetIsSystemRole(v)
	return _u
}

// SetNillableIsSystemRole sets the "is_system_role" field if the given value is not nil.
func (_u *HospitalRoleUpdate) SetNillableIsSystemRole(v *bool) *HospitalRoleUpdate {
	if v != nil {
		_u.SetIsSystemRole(*v)
	}
	return _u
}

// SetClonedFromRoleID sets the "cloned_from_role_id" field.
func (_u *HospitalRoleUpdate) SetClonedFromRoleID(v uuid.UUID) *HospitalRoleUpdate {
	_u.mutation.SetClonedFromRoleID(v)
	return _u
}

// SetNillableClonedFromRoleID sets the "cloned_from_role_id" field if the given value is not nil.
func (_u *HospitalRoleUpdate) SetNillableClonedFromRoleID(v *uuid.UUID) *HospitalRoleUpdate {
	if v != nil {
		_u.SetClonedFromRoleID(*v)
	}
	return _u
}

// ClearClonedFromRoleID clears the value of the "cloned_from_role_id" field.
func (_u *HospitalRoleUpdate) ClearClonedFromRoleID() *HospitalRoleUpdate {
	_u.mutation.ClearClonedFromRoleID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HospitalRoleUpdate) SetUpdatedAt(v time.Time) *HospitalRoleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPermissionIDs adds the "permissions" edge to the HospitalPermission entity by IDs.
func (_u *HospitalRoleUpdate) AddPermissionIDs(ids ...uuid.UUID) *HospitalRoleUpdate {
	_u.mutation.AddPermissionIDs(ids...)
	return _u
}

// AddPermissions adds the "permissions" edges to the HospitalPermission entity.
func (_u *HospitalRoleUpdate) AddPermissions(v ...*HospitalPermission) *HospitalRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionIDs(ids...)
}

// AddUserAssignmentIDs adds the "user_assignments" edge to the UserRoleAssignment entity by IDs.
func (_u *HospitalRoleUpdate) AddUserAssignmentIDs(ids ...uuid.UUID) *HospitalRoleUpdate {
	_u.mutation.AddUserAssignmentIDs(ids...)
	return _u
}

// AddUserAssignments adds the "user_assignments" edges to the UserRoleAssignment entity.
func (_u *HospitalRoleUpdate) AddUserAssignments(v ...*UserRoleAssignment) *HospitalRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserAssignmentIDs(ids...)
}

// AddRolePermissionIDs adds the "role_permissions" edge to the RolePermission entity by IDs.
func (_u *HospitalRoleUpdate) AddRolePermissionIDs(ids ...int) *HospitalRoleUpdate {
	_u.mutation.AddRolePermissionIDs(ids...)
	return _u
}

// AddRolePermissions adds the "role_permissions" edges to the RolePermission entity.
func (_u *HospitalRoleUpdate) AddRolePermissions(v ...*RolePermission) *HospitalRoleUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRolePermissionIDs(ids...)
}

// Mutation returns the HospitalRoleMutation object of the builder.
func (_u *HospitalRoleUpdate) Mutation() *HospitalRoleMutation {
	return _u.mutation
}

// ClearPermissions clears all "permissions" edges to the HospitalPermission entity.
func (_u *HospitalRoleUpdate) ClearPermissions() *HospitalRoleUpdate {
	_u.mutation.ClearPermissions()
	return _u
}

// RemovePermissionIDs removes the "permissions" edge to HospitalPermission entities by IDs.
func (_u *HospitalRoleUpdate) RemovePermissionIDs(ids ...uuid.UUID) *HospitalRoleUpdate {
	_u.mutation.RemovePermissionIDs(ids...)
	return _u
}

// RemovePermissions removes "permissions" edges to HospitalPermission entities.
func (_u *HospitalRoleUpdate) RemovePermissions(v ...*HospitalPermission) *HospitalRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionIDs(ids...)
}

// ClearUserAssignments clears all "user_assignments" edges to the UserRoleAssignment entity.
func (_u *HospitalRoleUpdate) ClearUserAssignments() *HospitalRoleUpdate {
	_u.mutation.ClearUserAssignments()
	return _u
}

// RemoveUserAssignmentIDs removes the "user_assignments" edge to UserRoleAssignment entities by IDs.
func (_u *HospitalRoleUpdate) RemoveUserAssignmentIDs(ids ...uuid.UUID) *HospitalRoleUpdate {
	_u.mutation.RemoveUserAssignmentIDs(ids...)
	return _u
}

// RemoveUserAssignments removes "user_assignments" edges to UserRoleAssignment entities.
func (_u *HospitalRoleUpdate) RemoveUserAssignments(v ...*UserRoleAssignment) *HospitalRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserAssignmentIDs(ids...)
}

// ClearRolePermissions clears all "role_permissions" edges to the RolePermission entity.
func (_u *HospitalRoleUpdate) ClearRolePermissions() *HospitalRoleUpdate {
	_u.mutation.ClearRolePermissions()
	return _u
}

// RemoveRolePermissionIDs removes the "role_permissions" edge to RolePermission entities by IDs.
func (_u *HospitalRoleUpdate) RemoveRolePermissionIDs(ids ...int) *HospitalRoleUpdate {
	_u.mutation.RemoveRolePermissionIDs(ids...)
	return _u
}

// RemoveRolePermissions removes "role_permissions" edges to RolePermission entities.
func (_u *HospitalRoleUpdate) RemoveRolePermissions(v ...*RolePermission) *HospitalRoleUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRolePermissionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HospitalRoleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HospitalRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HospitalRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HospitalRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HospitalRoleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := hospitalrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HospitalRoleUpdate) check() error {
	if v, ok := _u.mutation.RoleCode(); ok {
		if err := hospitalrole.RoleCodeValidator(v); err != nil {
			return &ValidationError{Name: "role_code", err: fmt.Errorf(`ent: validator failed for field "HospitalRole.role_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := hospitalrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "HospitalRole.name": %w`, err)}
		}
	}
	return nil
}

func (_u *HospitalRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hospitalrole.Table, hospitalrole.Columns, sqlgraph.NewFieldSpec(hospitalrole.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(hospitalrole.FieldTenantID, field.TypeUUID, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(hospitalrole.FieldTenantID, field.TypeUUID)
	}
	if value, ok := _u.mutation.RoleCode(); ok {
		_spec.SetField(hospitalrole.FieldRoleCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(hospitalrole.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(hospitalrole.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(hospitalrole.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.IsSystemRole(); ok {
		_spec.SetField(hospitalrole.FieldIsSystemRole, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ClonedFromRoleID(); ok {
		_spec.SetField(hospitalrole.FieldClonedFromRoleID, field.TypeUUID, value)
	}
	if _u.mutation.ClonedFromRoleIDCleared() {
		_spec.ClearField(hospitalrole.FieldClonedFromRoleID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(hospitalrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   hospitalrole.PermissionsTable,
			Columns: hospitalrole.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hospitalpermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !_u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   hospitalrole.PermissionsTable,
			Columns: hospitalrole.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hospitalpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   hospitalrole.PermissionsTable,
			Columns: hospitalrole.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hospitalpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hospitalrole.UserAssignmentsTable,
			Columns: []string{hospitalrole.UserAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserAssignmentsIDs(); len(nodes) > 0 && !_u.mutation.UserAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hospitalrole.UserAssignmentsTable,
			Columns: []string{hospitalrole.UserAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserAssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hospitalrole.UserAssignmentsTable,
			Columns: []string{hospitalrole.UserAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hospitalrole.RolePermissionsTable,
			Columns: []string{hospitalrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolePermissionsIDs(); len(nodes) > 0 && !_u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hospitalrole.RolePermissionsTable,
			Columns: []string{hospitalrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hospitalrole.RolePermissionsTable,
			Columns: []string{hospitalrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hospitalrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HospitalRoleUpdateOne is the builder for updating a single HospitalRole entity.
type HospitalRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HospitalRoleMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *HospitalRoleUpdateOne) SetTenantID(v uuid.UUID) *HospitalRoleUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *HospitalRoleUpdateOne) SetNillableTenantID(v *uuid.UUID) *HospitalRoleUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *HospitalRoleUpdateOne) ClearTenantID() *HospitalRoleUpdateOne {
	_u.mutation.ClearTenantID()
	return _u
}

// SetRoleCode sets the "role_code" field.
func (_u *HospitalRoleUpdateOne) SetRoleCode(v string) *HospitalRoleUpdateOne {
	_u.mutation.SetRoleCode(v)
	return _u
}

// SetNillableRoleCode sets the "role_code" field if the given value is not nil.
func (_u *HospitalRoleUpdateOne) SetNillableRoleCode(v *string) *HospitalRoleUpdateOne {
	if v != nil {
		_u.SetRoleCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *HospitalRoleUpdateOne) SetName(v string) *HospitalRoleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HospitalRoleUpdateOne) SetNillableName(v *string) *HospitalRoleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *HospitalRoleUpdateOne) SetDescription(v string) *HospitalRoleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *HospitalRoleUpdateOne) SetNillableDescription(v *string) *HospitalRoleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *HospitalRoleUpdateOne) ClearDescription() *HospitalRoleUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetIsSystemRole sets the "is_system_role" field.
func (_u *HospitalRoleUpdateOne) SetIsSystemRole(v bool) *HospitalRoleUpdateOne {
	_u.mutation.SetIsSystemRole(v)
	return _u
}

// SetNillableIsSystemRole sets the "is_system_role" field if the given value is not nil.
func (_u *HospitalRoleUpdateOne) SetNillableIsSystemRole(v *bool) *HospitalRoleUpdateOne {
	if v != nil {
		_u.SetIsSystemRole(*v)
	}
	return _u
}

// SetClonedFromRoleID sets the "cloned_from_role_id" field.
func (_u *HospitalRoleUpdateOne) SetClonedFromRoleID(v uuid.UUID) *HospitalRoleUpdateOne {
	_u.mutation.SetClonedFromRoleID(v)
	return _u
}

// SetNillableClonedFromRoleID sets the "cloned_from_role_id" field if the given value is not nil.
func (_u *HospitalRoleUpdateOne) SetNillableClonedFromRoleID(v *uuid.UUID) *HospitalRoleUpdateOne {
	if v != nil {
		_u.SetClonedFromRoleID(*v)
	}
	return _u
}

// ClearClonedFromRoleID clears the value of the "cloned_from_role_id" field.
func (_u *HospitalRoleUpdateOne) ClearClonedFromRoleID() *HospitalRoleUpdateOne {
	_u.mutation.ClearClonedFromRoleID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HospitalRoleUpdateOne) SetUpdatedAt(v time.Time) *HospitalRoleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPermissionIDs adds the "permissions" edge to the HospitalPermission entity by IDs.
func (_u *HospitalRoleUpdateOne) AddPermissionIDs(ids ...uuid.UUID) *HospitalRoleUpdateOne {
	_u.mutation.AddPermissionIDs(ids...)
	return _u
}

// AddPermissions adds the "permissions" edges to the HospitalPermission entity.
func (_u *HospitalRoleUpdateOne) AddPermissions(v ...*HospitalPermission) *HospitalRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionIDs(ids...)
}

// AddUserAssignmentIDs adds the "user_assignments" edge to the UserRoleAssignment entity by IDs.
func (_u *HospitalRoleUpdateOne) AddUserAssignmentIDs(ids ...uuid.UUID) *HospitalRoleUpdateOne {
	_u.mutation.AddUserAssignmentIDs(ids...)
	return _u
}

// AddUserAssignments adds the "user_assignments" edges to the UserRoleAssignment entity.
func (_u *HospitalRoleUpdateOne) AddUserAssignments(v ...*UserRoleAssignment) *HospitalRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserAssignmentIDs(ids...)
}

// AddRolePermissionIDs adds the "role_permissions" edge to the RolePermission entity by IDs.
func (_u *HospitalRoleUpdateOne) AddRolePermissionIDs(ids ...int) *HospitalRoleUpdateOne {
	_u.mutation.AddRolePermissionIDs(ids...)
	return _u
}

// AddRolePermissions adds the "role_permissions" edges to the RolePermission entity.
func (_u *HospitalRoleUpdateOne) AddRolePermissions(v ...*RolePermission) *HospitalRoleUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRolePermissionIDs(ids...)
}

// Mutation returns the HospitalRoleMutation object of the builder.
func (_u *HospitalRoleUpdateOne) Mutation() *HospitalRoleMutation {
	return _u.mutation
}

// ClearPermissions clears all "permissions" edges to the HospitalPermission entity.
func (_u *HospitalRoleUpdateOne) ClearPermissions() *HospitalRoleUpdateOne {
	_u.mutation.ClearPermissions()
	return _u
}

// RemovePermissionIDs removes the "permissions" edge to HospitalPermission entities by IDs.
func (_u *HospitalRoleUpdateOne) RemovePermissionIDs(ids ...uuid.UUID) *HospitalRoleUpdateOne {
	_u.mutation.RemovePermissionIDs(ids...)
	return _u
}

// RemovePermissions removes "permissions" edges to HospitalPermission entities.
func (_u *HospitalRoleUpdateOne) RemovePermissions(v ...*HospitalPermission) *HospitalRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionIDs(ids...)
}

// ClearUserAssignments clears all "user_assignments" edges to the UserRoleAssignment entity.
func (_u *HospitalRoleUpdateOne) ClearUserAssignments() *HospitalRoleUpdateOne {
	_u.mutation.ClearUserAssignments()
	return _u
}

// RemoveUserAssignmentIDs removes the "user_assignments" edge to UserRoleAssignment entities by IDs.
func (_u *HospitalRoleUpdateOne) RemoveUserAssignmentIDs(ids ...uuid.UUID) *HospitalRoleUpdateOne {
	_u.mutation.RemoveUserAssignmentIDs(ids...)
	return _u
}

// RemoveUserAssignments removes "user_assignments" edges to UserRoleAssignment entities.
func (_u *HospitalRoleUpdateOne) RemoveUserAssignments(v ...*UserRoleAssignment) *HospitalRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserAssignmentIDs(ids...)
}

// ClearRolePermissions clears all "role_permissions" edges to the RolePermission entity.
func (_u *HospitalRoleUpdateOne) ClearRolePermissions() *HospitalRoleUpdateOne {
	_u.mutation.ClearRolePermissions()
	return _u
}

// RemoveRolePermissionIDs removes the "role_permissions" edge to RolePermission entities by IDs.
func (_u *HospitalRoleUpdateOne) RemoveRolePermissionIDs(ids ...int) *HospitalRoleUpdateOne {
	_u.mutation.RemoveRolePermissionIDs(ids...)
	return _u
}

// RemoveRolePermissions removes "role_permissions" edges to RolePermission entities.
func (_u *HospitalRoleUpdateOne) RemoveRolePermissions(v ...*RolePermission) *HospitalRoleUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRolePermissionIDs(ids...)
}

// Where appends a list predicates to the HospitalRoleUpdate builder.
func (_u *HospitalRoleUpdateOne) Where(ps ...predicate.HospitalRole) *HospitalRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HospitalRoleUpdateOne) Select(field string, fields ...string) *HospitalRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated HospitalRole entity.
func (_u *HospitalRoleUpdateOne) Save(ctx context.Context) (*HospitalRole, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HospitalRoleUpdateOne) SaveX(ctx context.Context) *HospitalRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HospitalRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HospitalRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HospitalRoleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := hospitalrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HospitalRoleUpdateOne) check() error {
	if v, ok := _u.mutation.RoleCode(); ok {
		if err := hospitalrole.RoleCodeValidator(v); err != nil {
			return &ValidationError{Name: "role_code", err: fmt.Errorf(`ent: validator failed for field "HospitalRole.role_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := hospitalrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "HospitalRole.name": %w`, err)}
		}
	}
	return nil
}

func (_u *HospitalRoleUpdateOne) sqlSave(ctx context.Context) (_node *HospitalRole, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hospitalrole.Table, hospitalrole.Columns, sqlgraph.NewFieldSpec(hospitalrole.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HospitalRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hospitalrole.FieldID)
		for _, f := range fields {
			if !hospitalrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hospitalrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(hospitalrole.FieldTenantID, field.TypeUUID, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(hospitalrole.FieldTenantID, field.TypeUUID)
	}
	if value, ok := _u.mutation.RoleCode(); ok {
		_spec.SetField(hospitalrole.FieldRoleCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(hospitalrole.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(hospitalrole.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(hospitalrole.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.IsSystemRole(); ok {
		_spec.SetField(hospitalrole.FieldIsSystemRole, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ClonedFromRoleID(); ok {
		_spec.SetField(hospitalrole.FieldClonedFromRoleID, field.TypeUUID, value)
	}
	if _u.mutation.ClonedFromRoleIDCleared() {
		_spec.ClearField(hospitalrole.FieldClonedFromRoleID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(hospitalrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   hospitalrole.PermissionsTable,
			Columns: hospitalrole.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hospitalpermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !_u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   hospitalrole.PermissionsTable,
			Columns: hospitalrole.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hospitalpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   hospitalrole.PermissionsTable,
			Columns: hospitalrole.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hospitalpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hospitalrole.UserAssignmentsTable,
			Columns: []string{hospitalrole.UserAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserAssignmentsIDs(); len(nodes) > 0 && !_u.mutation.UserAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hospitalrole.UserAssignmentsTable,
			Columns: []string{hospitalrole.UserAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserAssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hospitalrole.UserAssignmentsTable,
			Columns: []string{hospitalrole.UserAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hospitalrole.RolePermissionsTable,
			Columns: []string{hospitalrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolePermissionsIDs(); len(nodes) > 0 && !_u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hospitalrole.RolePermissionsTable,
			Columns: []string{hospitalrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hospitalrole.RolePermissionsTable,
			Columns: []string{hospitalrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &HospitalRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hospitalrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
