// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/hospital-service/internal/ent/laborder"
	"github.com/bengobox/hospital-service/internal/ent/laborderline"
	"github.com/google/uuid"
)

// LabOrderLineCreate is the builder for creating a LabOrderLine entity.
type LabOrderLineCreate struct {
	config
	mutation *LabOrderLineMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *LabOrderLineCreate) SetTenantID(v uuid.UUID) *LabOrderLineCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetLabOrderID sets the "lab_order_id" field.
func (_c *LabOrderLineCreate) SetLabOrderID(v uuid.UUID) *LabOrderLineCreate {
	_c.mutation.SetLabOrderID(v)
	return _c
}

// SetTestCode sets the "test_code" field.
func (_c *LabOrderLineCreate) SetTestCode(v string) *LabOrderLineCreate {
	_c.mutation.SetTestCode(v)
	return _c
}

// SetTestName sets the "test_name" field.
func (_c *LabOrderLineCreate) SetTestName(v string) *LabOrderLineCreate {
	_c.mutation.SetTestName(v)
	return _c
}

// SetPrice sets the "price" field.
func (_c *LabOrderLineCreate) SetPrice(v float64) *LabOrderLineCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_c *LabOrderLineCreate) SetNillablePrice(v *float64) *LabOrderLineCreate {
	if v != nil {
		_c.SetPrice(*v)
	}
	return _c
}

// SetSpecimenType sets the "specimen_type" field.
func (_c *LabOrderLineCreate) SetSpecimenType(v string) *LabOrderLineCreate {
	_c.mutation.SetSpecimenType(v)
	return _c
}

// SetNillableSpecimenType sets the "specimen_type" field if the given value is not nil.
func (_c *LabOrderLineCreate) SetNillableSpecimenType(v *string) *LabOrderLineCreate {
	if v != nil {
		_c.SetSpecimenType(*v)
	}
	return _c
}

// SetSpecimenCollectedAt sets the "specimen_collected_at" field.
func (_c *LabOrderLineCreate) SetSpecimenCollectedAt(v time.Time) *LabOrderLineCreate {
	_c.mutation.SetSpecimenCollectedAt(v)
	return _c
}

// SetNillableSpecimenCollectedAt sets the "specimen_collected_at" field if the given value is not nil.
func (_c *LabOrderLineCreate) SetNillableSpecimenCollectedAt(v *time.Time) *LabOrderLineCreate {
	if v != nil {
		_c.SetSpecimenCollectedAt(*v)
	}
	return _c
}

// SetSpecimenCollectedBy sets the "specimen_collected_by" field.
func (_c *LabOrderLineCreate) SetSpecimenCollectedBy(v uuid.UUID) *LabOrderLineCreate {
	_c.mutation.SetSpecimenCollectedBy(v)
	return _c
}

// SetNillableSpecimenCollectedBy sets the "specimen_collected_by" field if the given value is not nil.
func (_c *LabOrderLineCreate) SetNillableSpecimenCollectedBy(v *uuid.UUID) *LabOrderLineCreate {
	if v != nil {
		_c.SetSpecimenCollectedBy(*v)
	}
	return _c
}

// SetSpecimenID sets the "specimen_id" field.
func (_c *LabOrderLineCreate) SetSpecimenID(v string) *LabOrderLineCreate {
	_c.mutation.SetSpecimenID(v)
	return _c
}

// SetNillableSpecimenID sets the "specimen_id" field if the given value is not nil.
func (_c *LabOrderLineCreate) SetNillableSpecimenID(v *string) *LabOrderLineCreate {
	if v != nil {
		_c.SetSpecimenID(*v)
	}
	return _c
}

// SetResultValue sets the "result_value" field.
func (_c *LabOrderLineCreate) SetResultValue(v string) *LabOrderLineCreate {
	_c.mutation.SetResultValue(v)
	return _c
}

// SetNillableResultValue sets the "result_value" field if the given value is not nil.
func (_c *LabOrderLineCreate) SetNillableResultValue(v *string) *LabOrderLineCreate {
	if v != nil {
		_c.SetResultValue(*v)
	}
	return _c
}

// SetUnit sets the "unit" field.
func (_c *LabOrderLineCreate) SetUnit(v string) *LabOrderLineCreate {
	_c.mutation.SetUnit(v)
	return _c
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (_c *LabOrderLineCreate) SetNillableUnit(v *string) *LabOrderLineCreate {
	if v != nil {
		_c.SetUnit(*v)
	}
	return _c
}

// SetReferenceRange sets the "reference_range" field.
func (_c *LabOrderLineCreate) SetReferenceRange(v string) *LabOrderLineCreate {
	_c.mutation.SetReferenceRange(v)
	return _c
}

// SetNillableReferenceRange sets the "reference_range" field if the given value is not nil.
func (_c *LabOrderLineCreate) SetNillableReferenceRange(v *string) *LabOrderLineCreate {
	if v != nil {
		_c.SetReferenceRange(*v)
	}
	return _c
}

// SetFlag sets the "flag" field.
func (_c *LabOrderLineCreate) SetFlag(v laborderline.Flag) *LabOrderLineCreate {
	_c.mutation.SetFlag(v)
	return _c
}

// SetNillableFlag sets the "flag" field if the given value is not nil.
func (_c *LabOrderLineCreate) SetNillableFlag(v *laborderline.Flag) *LabOrderLineCreate {
	if v != nil {
		_c.SetFlag(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *LabOrderLineCreate) SetNotes(v string) *LabOrderLineCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *LabOrderLineCreate) SetNillableNotes(v *string) *LabOrderLineCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetResultedBy sets the "resulted_by" field.
func (_c *LabOrderLineCreate) SetResultedBy(v uuid.UUID) *LabOrderLineCreate {
	_c.mutation.SetResultedBy(v)
	return _c
}

// SetNillableResultedBy sets the "resulted_by" field if the given value is not nil.
func (_c *LabOrderLineCreate) SetNillableResultedBy(v *uuid.UUID) *LabOrderLineCreate {
	if v != nil {
		_c.SetResultedBy(*v)
	}
	return _c
}

// SetResultedAt sets the "resulted_at" field.
func (_c *LabOrderLineCreate) SetResultedAt(v time.Time) *LabOrderLineCreate {
	_c.mutation.SetResultedAt(v)
	return _c
}

// SetNillableResultedAt sets the "resulted_at" field if the given value is not nil.
func (_c *LabOrderLineCreate) SetNillableResultedAt(v *time.Time) *LabOrderLineCreate {
	if v != nil {
		_c.SetResultedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LabOrderLineCreate) SetCreatedAt(v time.Time) *LabOrderLineCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LabOrderLineCreate) SetNillableCreatedAt(v *time.Time) *LabOrderLineCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LabOrderLineCreate) SetID(v uuid.UUID) *LabOrderLineCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *LabOrderLineCreate) SetNillableID(v *uuid.UUID) *LabOrderLineCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetLabOrder sets the "lab_order" edge to the LabOrder entity.
func (_c *LabOrderLineCreate) SetLabOrder(v *LabOrder) *LabOrderLineCreate {
	return _c.SetLabOrderID(v.ID)
}

// Mutation returns the LabOrderLineMutation object of the builder.
func (_c *LabOrderLineCreate) Mutation() *LabOrderLineMutation {
	return _c.mutation
}

// Save creates the LabOrderLine in the database.
func (_c *LabOrderLineCreate) Save(ctx context.Context) (*LabOrderLine, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LabOrderLineCreate) SaveX(ctx context.Context) *LabOrderLine {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LabOrderLineCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LabOrderLineCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LabOrderLineCreate) defaults() {
	if _, ok := _c.mutation.Price(); !ok {
		v := laborderline.DefaultPrice
		_c.mutation.SetPrice(v)
	}
	if _, ok := _c.mutation.Flag(); !ok {
		v := laborderline.DefaultFlag
		_c.mutation.SetFlag(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := laborderline.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := laborderline.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LabOrderLineCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "LabOrderLine.tenant_id"`)}
	}
	if _, ok := _c.mutation.LabOrderID(); !ok {
		return &ValidationError{Name: "lab_order_id", err: errors.New(`ent: missing required field "LabOrderLine.lab_order_id"`)}
	}
	if _, ok := _c.mutation.TestCode(); !ok {
		return &ValidationError{Name: "test_code", err: errors.New(`ent: missing required field "LabOrderLine.test_code"`)}
	}
	if v, ok := _c.mutation.TestCode(); ok {
		if err := laborderline.TestCodeValidator(v); err != nil {
			return &ValidationError{Name: "test_code", err: fmt.Errorf(`ent: validator failed for field "LabOrderLine.test_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TestName(); !ok {
		return &ValidationError{Name: "test_name", err: errors.New(`ent: missing required field "LabOrderLine.test_name"`)}
	}
	if v, ok := _c.mutation.TestName(); ok {
		if err := laborderline.TestNameValidator(v); err != nil {
			return &ValidationError{Name: "test_name", err: fmt.Errorf(`ent: validator failed for field "LabOrderLine.test_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "LabOrderLine.price"`)}
	}
	if _, ok := _c.mutation.Flag(); !ok {
		return &ValidationError{Name: "flag", err: errors.New(`ent: missing required field "LabOrderLine.flag"`)}
	}
	if v, ok := _c.mutation.Flag(); ok {
		if err := laborderline.FlagValidator(v); err != nil {
			return &ValidationError{Name: "flag", err: fmt.Errorf(`ent: validator failed for field "LabOrderLine.flag": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LabOrderLine.created_at"`)}
	}
	if len(_c.mutation.LabOrderIDs()) == 0 {
		return &ValidationError{Name: "lab_order", err: errors.New(`ent: missing required edge "LabOrderLine.lab_order"`)}
	}
	return nil
}

func (_c *LabOrderLineCreate) sqlSave(ctx context.Context) (*LabOrderLine, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LabOrderLineCreate) createSpec() (*LabOrderLine, *sqlgraph.CreateSpec) {
	var (
		_node = &LabOrderLine{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(laborderline.Table, sqlgraph.NewFieldSpec(laborderline.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(laborderline.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.TestCode(); ok {
		_spec.SetField(laborderline.FieldTestCode, field.TypeString, value)
		_node.TestCode = value
	}
	if value, ok := _c.mutation.TestName(); ok {
		_spec.SetField(laborderline.FieldTestName, field.TypeString, value)
		_node.TestName = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(laborderline.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.SpecimenType(); ok {
		_spec.SetField(laborderline.FieldSpecimenType, field.TypeString, value)
		_node.SpecimenType = value
	}
	if value, ok := _c.mutation.SpecimenCollectedAt(); ok {
		_spec.SetField(laborderline.FieldSpecimenCollectedAt, field.TypeTime, value)
		_node.SpecimenCollectedAt = &value
	}
	if value, ok := _c.mutation.SpecimenCollectedBy(); ok {
		_spec.SetField(laborderline.FieldSpecimenCollectedBy, field.TypeUUID, value)
		_node.SpecimenCollectedBy = &value
	}
	if value, ok := _c.mutation.SpecimenID(); ok {
		_spec.SetField(laborderline.FieldSpecimenID, field.TypeString, value)
		_node.SpecimenID = value
	}
	if value, ok := _c.mutation.ResultValue(); ok {
		_spec.SetField(laborderline.FieldResultValue, field.TypeString, value)
		_node.ResultValue = value
	}
	if value, ok := _c.mutation.Unit(); ok {
		_spec.SetField(laborderline.FieldUnit, field.TypeString, value)
		_node.Unit = value
	}
	if value, ok := _c.mutation.ReferenceRange(); ok {
		_spec.SetField(laborderline.FieldReferenceRange, field.TypeString, value)
		_node.ReferenceRange = value
	}
	if value, ok := _c.mutation.Flag(); ok {
		_spec.SetField(laborderline.FieldFlag, field.TypeEnum, value)
		_node.Flag = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(laborderline.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.ResultedBy(); ok {
		_spec.SetField(laborderline.FieldResultedBy, field.TypeUUID, value)
		_node.ResultedBy = &value
	}
	if value, ok := _c.mutation.ResultedAt(); ok {
		_spec.SetField(laborderline.FieldResultedAt, field.TypeTime, value)
		_node.ResultedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(laborderline.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.LabOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   laborderline.LabOrderTable,
			Columns: []string{laborderline.LabOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(laborder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LabOrderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LabOrderLine.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LabOrderLineUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *LabOrderLineCreate) OnConflict(opts ...sql.ConflictOption) *LabOrderLineUpsertOne {
	_c.conflict = opts
	return &LabOrderLineUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LabOrderLine.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LabOrderLineCreate) OnConflictColumns(columns ...string) *LabOrderLineUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LabOrderLineUpsertOne{
		create: _c,
	}
}

type (
	// LabOrderLineUpsertOne is the builder for "upsert"-ing
	//  one LabOrderLine node.
	LabOrderLineUpsertOne struct {
		create *LabOrderLineCreate
	}

	// LabOrderLineUpsert is the "OnConflict" setter.
	LabOrderLineUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *LabOrderLineUpsert) SetTenantID(v uuid.UUID) *LabOrderLineUpsert {
	u.Set(laborderline.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *LabOrderLineUpsert) UpdateTenantID() *LabOrderLineUpsert {
	u.SetExcluded(laborderline.FieldTenantID)
	return u
}

// SetLabOrderID sets the "lab_order_id" field.
func (u *LabOrderLineUpsert) SetLabOrderID(v uuid.UUID) *LabOrderLineUpsert {
	u.Set(laborderline.FieldLabOrderID, v)
	return u
}

// UpdateLabOrderID sets the "lab_order_id" field to the value that was provided on create.
func (u *LabOrderLineUpsert) UpdateLabOrderID() *LabOrderLineUpsert {
	u.SetExcluded(laborderline.FieldLabOrderID)
	return u
}

// SetTestCode sets the "test_code" field.
func (u *LabOrderLineUpsert) SetTestCode(v string) *LabOrderLineUpsert {
	u.Set(laborderline.FieldTestCode, v)
	return u
}

// UpdateTestCode sets the "test_code" field to the value that was provided on create.
func (u *LabOrderLineUpsert) UpdateTestCode() *LabOrderLineUpsert {
	u.SetExcluded(laborderline.FieldTestCode)
	return u
}

// SetTestName sets the "test_name" field.
func (u *LabOrderLineUpsert) SetTestName(v string) *LabOrderLineUpsert {
	u.Set(laborderline.FieldTestName, v)
	return u
}

// UpdateTestName sets the "test_name" field to the value that was provided on create.
func (u *LabOrderLineUpsert) UpdateTestName() *LabOrderLineUpsert {
	u.SetExcluded(laborderline.FieldTestName)
	return u
}

// SetPrice sets the "price" field.
func (u *LabOrderLineUpsert) SetPrice(v float64) *LabOrderLineUpsert {
	u.Set(laborderline.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *LabOrderLineUpsert) UpdatePrice() *LabOrderLineUpsert {
	u.SetExcluded(laborderline.FieldPrice)
	return u
}

// AddPrice adds v to the "price" field.
func (u *LabOrderLineUpsert) AddPrice(v float64) *LabOrderLineUpsert {
	u.Add(laborderline.FieldPrice, v)
	return u
}

// SetSpecimenType sets the "specimen_type" field.
func (u *LabOrderLineUpsert) SetSpecimenType(v string) *LabOrderLineUpsert {
	u.Set(laborderline.FieldSpecimenType, v)
	return u
}

// UpdateSpecimenType sets the "specimen_type" field to the value that was provided on create.
func (u *LabOrderLineUpsert) UpdateSpecimenType() *LabOrderLineUpsert {
	u.SetExcluded(laborderline.FieldSpecimenType)
	return u
}

// ClearSpecimenType clears the value of the "specimen_type" field.
func (u *LabOrderLineUpsert) ClearSpecimenType() *LabOrderLineUpsert {
	u.SetNull(laborderline.FieldSpecimenType)
	return u
}

// SetSpecimenCollectedAt sets the "specimen_collected_at" field.
func (u *LabOrderLineUpsert) SetSpecimenCollectedAt(v time.Time) *LabOrderLineUpsert {
	u.Set(laborderline.FieldSpecimenCollectedAt, v)
	return u
}

// UpdateSpecimenCollectedAt sets the "specimen_collected_at" field to the value that was provided on create.
func (u *LabOrderLineUpsert) UpdateSpecimenCollectedAt() *LabOrderLineUpsert {
	u.SetExcluded(laborderline.FieldSpecimenCollectedAt)
	return u
}

// ClearSpecimenCollectedAt clears the value of the "specimen_collected_at" field.
func (u *LabOrderLineUpsert) ClearSpecimenCollectedAt() *LabOrderLineUpsert {
	u.SetNull(laborderline.FieldSpecimenCollectedAt)
	return u
}

// SetSpecimenCollectedBy sets the "specimen_collected_by" field.
func (u *LabOrderLineUpsert) SetSpecimenCollectedBy(v uuid.UUID) *LabOrderLineUpsert {
	u.Set(laborderline.FieldSpecimenCollectedBy, v)
	return u
}

// UpdateSpecimenCollectedBy sets the "specimen_collected_by" field to the value that was provided on create.
func (u *LabOrderLineUpsert) UpdateSpecimenCollectedBy() *LabOrderLineUpsert {
	u.SetExcluded(laborderline.FieldSpecimenCollectedBy)
	return u
}

// ClearSpecimenCollectedBy clears the value of the "specimen_collected_by" field.
func (u *LabOrderLineUpsert) ClearSpecimenCollectedBy() *LabOrderLineUpsert {
	u.SetNull(laborderline.FieldSpecimenCollectedBy)
	return u
}

// SetSpecimenID sets the "specimen_id" field.
func (u *LabOrderLineUpsert) SetSpecimenID(v string) *LabOrderLineUpsert {
	u.Set(laborderline.FieldSpecimenID, v)
	return u
}

// UpdateSpecimenID sets the "specimen_id" field to the value that was provided on create.
func (u *LabOrderLineUpsert) UpdateSpecimenID() *LabOrderLineUpsert {
	u.SetExcluded(laborderline.FieldSpecimenID)
	return u
}

// ClearSpecimenID clears the value of the "specimen_id" field.
func (u *LabOrderLineUpsert) ClearSpecimenID() *LabOrderLineUpsert {
	u.SetNull(laborderline.FieldSpecimenID)
	return u
}

// SetResultValue sets the "result_value" field.
func (u *LabOrderLineUpsert) SetResultValue(v string) *LabOrderLineUpsert {
	u.Set(laborderline.FieldResultValue, v)
	return u
}

// UpdateResultValue sets the "result_value" field to the value that was provided on create.
func (u *LabOrderLineUpsert) UpdateResultValue() *LabOrderLineUpsert {
	u.SetExcluded(laborderline.FieldResultValue)
	return u
}

// ClearResultValue clears the value of the "result_value" field.
func (u *LabOrderLineUpsert) ClearResultValue() *LabOrderLineUpsert {
	u.SetNull(laborderline.FieldResultValue)
	return u
}

// SetUnit sets the "unit" field.
func (u *LabOrderLineUpsert) SetUnit(v string) *LabOrderLineUpsert {
	u.Set(laborderline.FieldUnit, v)
	return u
}

// UpdateUnit sets the "unit" field to the value that was provided on create.
func (u *LabOrderLineUpsert) UpdateUnit() *LabOrderLineUpsert {
	u.SetExcluded(laborderline.FieldUnit)
	return u
}

// ClearUnit clears the value of the "unit" field.
func (u *LabOrderLineUpsert) ClearUnit() *LabOrderLineUpsert {
	u.SetNull(laborderline.FieldUnit)
	return u
}

// SetReferenceRange sets the "reference_range" field.
func (u *LabOrderLineUpsert) SetReferenceRange(v string) *LabOrderLineUpsert {
	u.Set(laborderline.FieldReferenceRange, v)
	return u
}

// UpdateReferenceRange sets the "reference_range" field to the value that was provided on create.
func (u *LabOrderLineUpsert) UpdateReferenceRange() *LabOrderLineUpsert {
	u.SetExcluded(laborderline.FieldReferenceRange)
	return u
}

// ClearReferenceRange clears the value of the "reference_range" field.
func (u *LabOrderLineUpsert) ClearReferenceRange() *LabOrderLineUpsert {
	u.SetNull(laborderline.FieldReferenceRange)
	return u
}

// SetFlag sets the "flag" field.
func (u *LabOrderLineUpsert) SetFlag(v laborderline.Flag) *LabOrderLineUpsert {
	u.Set(laborderline.FieldFlag, v)
	return u
}

// UpdateFlag sets the "flag" field to the value that was provided on create.
func (u *LabOrderLineUpsert) UpdateFlag() *LabOrderLineUpsert {
	u.SetExcluded(laborderline.FieldFlag)
	return u
}

// SetNotes sets the "notes" field.
func (u *LabOrderLineUpsert) SetNotes(v string) *LabOrderLineUpsert {
	u.Set(laborderline.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *LabOrderLineUpsert) UpdateNotes() *LabOrderLineUpsert {
	u.SetExcluded(laborderline.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *LabOrderLineUpsert) ClearNotes() *LabOrderLineUpsert {
	u.SetNull(laborderline.FieldNotes)
	return u
}

// SetResultedBy sets the "resulted_by" field.
func (u *LabOrderLineUpsert) SetResultedBy(v uuid.UUID) *LabOrderLineUpsert {
	u.Set(laborderline.FieldResultedBy, v)
	return u
}

// UpdateResultedBy sets the "resulted_by" field to the value that was provided on create.
func (u *LabOrderLineUpsert) UpdateResultedBy() *LabOrderLineUpsert {
	u.SetExcluded(laborderline.FieldResultedBy)
	return u
}

// ClearResultedBy clears the value of the "resulted_by" field.
func (u *LabOrderLineUpsert) ClearResultedBy() *LabOrderLineUpsert {
	u.SetNull(laborderline.FieldResultedBy)
	return u
}

// SetResultedAt sets the "resulted_at" field.
func (u *LabOrderLineUpsert) SetResultedAt(v time.Time) *LabOrderLineUpsert {
	u.Set(laborderline.FieldResultedAt, v)
	return u
}

// UpdateResultedAt sets the "resulted_at" field to the value that was provided on create.
func (u *LabOrderLineUpsert) UpdateResultedAt() *LabOrderLineUpsert {
	u.SetExcluded(laborderline.FieldResultedAt)
	return u
}

// ClearResultedAt clears the value of the "resulted_at" field.
func (u *LabOrderLineUpsert) ClearResultedAt() *LabOrderLineUpsert {
	u.SetNull(laborderline.FieldResultedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.LabOrderLine.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(laborderline.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LabOrderLineUpsertOne) UpdateNewValues() *LabOrderLineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(laborderline.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(laborderline.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LabOrderLine.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LabOrderLineUpsertOne) Ignore() *LabOrderLineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LabOrderLineUpsertOne) DoNothing() *LabOrderLineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LabOrderLineCreate.OnConflict
// documentation for more info.
func (u *LabOrderLineUpsertOne) Update(set func(*LabOrderLineUpsert)) *LabOrderLineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LabOrderLineUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *LabOrderLineUpsertOne) SetTenantID(v uuid.UUID) *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *LabOrderLineUpsertOne) UpdateTenantID() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateTenantID()
	})
}

// SetLabOrderID sets the "lab_order_id" field.
func (u *LabOrderLineUpsertOne) SetLabOrderID(v uuid.UUID) *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetLabOrderID(v)
	})
}

// UpdateLabOrderID sets the "lab_order_id" field to the value that was provided on create.
func (u *LabOrderLineUpsertOne) UpdateLabOrderID() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateLabOrderID()
	})
}

// SetTestCode sets the "test_code" field.
func (u *LabOrderLineUpsertOne) SetTestCode(v string) *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetTestCode(v)
	})
}

// UpdateTestCode sets the "test_code" field to the value that was provided on create.
func (u *LabOrderLineUpsertOne) UpdateTestCode() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateTestCode()
	})
}

// SetTestName sets the "test_name" field.
func (u *LabOrderLineUpsertOne) SetTestName(v string) *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetTestName(v)
	})
}

// UpdateTestName sets the "test_name" field to the value that was provided on create.
func (u *LabOrderLineUpsertOne) UpdateTestName() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateTestName()
	})
}

// SetPrice sets the "price" field.
func (u *LabOrderLineUpsertOne) SetPrice(v float64) *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *LabOrderLineUpsertOne) AddPrice(v float64) *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *LabOrderLineUpsertOne) UpdatePrice() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdatePrice()
	})
}

// SetSpecimenType sets the "specimen_type" field.
func (u *LabOrderLineUpsertOne) SetSpecimenType(v string) *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetSpecimenType(v)
	})
}

// UpdateSpecimenType sets the "specimen_type" field to the value that was provided on create.
func (u *LabOrderLineUpsertOne) UpdateSpecimenType() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateSpecimenType()
	})
}

// ClearSpecimenType clears the value of the "specimen_type" field.
func (u *LabOrderLineUpsertOne) ClearSpecimenType() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearSpecimenType()
	})
}

// SetSpecimenCollectedAt sets the "specimen_collected_at" field.
func (u *LabOrderLineUpsertOne) SetSpecimenCollectedAt(v time.Time) *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetSpecimenCollectedAt(v)
	})
}

// UpdateSpecimenCollectedAt sets the "specimen_collected_at" field to the value that was provided on create.
func (u *LabOrderLineUpsertOne) UpdateSpecimenCollectedAt() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateSpecimenCollectedAt()
	})
}

// ClearSpecimenCollectedAt clears the value of the "specimen_collected_at" field.
func (u *LabOrderLineUpsertOne) ClearSpecimenCollectedAt() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearSpecimenCollectedAt()
	})
}

// SetSpecimenCollectedBy sets the "specimen_collected_by" field.
func (u *LabOrderLineUpsertOne) SetSpecimenCollectedBy(v uuid.UUID) *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetSpecimenCollectedBy(v)
	})
}

// UpdateSpecimenCollectedBy sets the "specimen_collected_by" field to the value that was provided on create.
func (u *LabOrderLineUpsertOne) UpdateSpecimenCollectedBy() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateSpecimenCollectedBy()
	})
}

// ClearSpecimenCollectedBy clears the value of the "specimen_collected_by" field.
func (u *LabOrderLineUpsertOne) ClearSpecimenCollectedBy() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearSpecimenCollectedBy()
	})
}

// SetSpecimenID sets the "specimen_id" field.
func (u *LabOrderLineUpsertOne) SetSpecimenID(v string) *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetSpecimenID(v)
	})
}

// UpdateSpecimenID sets the "specimen_id" field to the value that was provided on create.
func (u *LabOrderLineUpsertOne) UpdateSpecimenID() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateSpecimenID()
	})
}

// ClearSpecimenID clears the value of the "specimen_id" field.
func (u *LabOrderLineUpsertOne) ClearSpecimenID() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearSpecimenID()
	})
}

// SetResultValue sets the "result_value" field.
func (u *LabOrderLineUpsertOne) SetResultValue(v string) *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetResultValue(v)
	})
}

// UpdateResultValue sets the "result_value" field to the value that was provided on create.
func (u *LabOrderLineUpsertOne) UpdateResultValue() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateResultValue()
	})
}

// ClearResultValue clears the value of the "result_value" field.
func (u *LabOrderLineUpsertOne) ClearResultValue() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearResultValue()
	})
}

// SetUnit sets the "unit" field.
func (u *LabOrderLineUpsertOne) SetUnit(v string) *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetUnit(v)
	})
}

// UpdateUnit sets the "unit" field to the value that was provided on create.
func (u *LabOrderLineUpsertOne) UpdateUnit() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateUnit()
	})
}

// ClearUnit clears the value of the "unit" field.
func (u *LabOrderLineUpsertOne) ClearUnit() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearUnit()
	})
}

// SetReferenceRange sets the "reference_range" field.
func (u *LabOrderLineUpsertOne) SetReferenceRange(v string) *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetReferenceRange(v)
	})
}

// UpdateReferenceRange sets the "reference_range" field to the value that was provided on create.
func (u *LabOrderLineUpsertOne) UpdateReferenceRange() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateReferenceRange()
	})
}

// ClearReferenceRange clears the value of the "reference_range" field.
func (u *LabOrderLineUpsertOne) ClearReferenceRange() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearReferenceRange()
	})
}

// SetFlag sets the "flag" field.
func (u *LabOrderLineUpsertOne) SetFlag(v laborderline.Flag) *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetFlag(v)
	})
}

// UpdateFlag sets the "flag" field to the value that was provided on create.
func (u *LabOrderLineUpsertOne) UpdateFlag() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateFlag()
	})
}

// SetNotes sets the "notes" field.
func (u *LabOrderLineUpsertOne) SetNotes(v string) *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *LabOrderLineUpsertOne) UpdateNotes() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *LabOrderLineUpsertOne) ClearNotes() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearNotes()
	})
}

// SetResultedBy sets the "resulted_by" field.
func (u *LabOrderLineUpsertOne) SetResultedBy(v uuid.UUID) *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetResultedBy(v)
	})
}

// UpdateResultedBy sets the "resulted_by" field to the value that was provided on create.
func (u *LabOrderLineUpsertOne) UpdateResultedBy() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateResultedBy()
	})
}

// ClearResultedBy clears the value of the "resulted_by" field.
func (u *LabOrderLineUpsertOne) ClearResultedBy() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearResultedBy()
	})
}

// SetResultedAt sets the "resulted_at" field.
func (u *LabOrderLineUpsertOne) SetResultedAt(v time.Time) *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetResultedAt(v)
	})
}

// UpdateResultedAt sets the "resulted_at" field to the value that was provided on create.
func (u *LabOrderLineUpsertOne) UpdateResultedAt() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateResultedAt()
	})
}

// ClearResultedAt clears the value of the "resulted_at" field.
func (u *LabOrderLineUpsertOne) ClearResultedAt() *LabOrderLineUpsertOne {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearResultedAt()
	})
}

// Exec executes the query.
func (u *LabOrderLineUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LabOrderLineCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LabOrderLineUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LabOrderLineUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: LabOrderLineUpsertOne.ID is not supported by MySQL driver. Use LabOrderLineUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LabOrderLineUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LabOrderLineCreateBulk is the builder for creating many LabOrderLine entities in bulk.
type LabOrderLineCreateBulk struct {
	config
	err      error
	builders []*LabOrderLineCreate
	conflict []sql.ConflictOption
}

// Save creates the LabOrderLine entities in the database.
func (_c *LabOrderLineCreateBulk) Save(ctx context.Context) ([]*LabOrderLine, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LabOrderLine, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LabOrderLineMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LabOrderLineCreateBulk) SaveX(ctx context.Context) []*LabOrderLine {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LabOrderLineCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LabOrderLineCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LabOrderLine.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LabOrderLineUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *LabOrderLineCreateBulk) OnConflict(opts ...sql.ConflictOption) *LabOrderLineUpsertBulk {
	_c.conflict = opts
	return &LabOrderLineUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LabOrderLine.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LabOrderLineCreateBulk) OnConflictColumns(columns ...string) *LabOrderLineUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LabOrderLineUpsertBulk{
		create: _c,
	}
}

// LabOrderLineUpsertBulk is the builder for "upsert"-ing
// a bulk of LabOrderLine nodes.
type LabOrderLineUpsertBulk struct {
	create *LabOrderLineCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LabOrderLine.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(laborderline.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LabOrderLineUpsertBulk) UpdateNewValues() *LabOrderLineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(laborderline.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(laborderline.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LabOrderLine.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LabOrderLineUpsertBulk) Ignore() *LabOrderLineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LabOrderLineUpsertBulk) DoNothing() *LabOrderLineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LabOrderLineCreateBulk.OnConflict
// documentation for more info.
func (u *LabOrderLineUpsertBulk) Update(set func(*LabOrderLineUpsert)) *LabOrderLineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LabOrderLineUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *LabOrderLineUpsertBulk) SetTenantID(v uuid.UUID) *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *LabOrderLineUpsertBulk) UpdateTenantID() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateTenantID()
	})
}

// SetLabOrderID sets the "lab_order_id" field.
func (u *LabOrderLineUpsertBulk) SetLabOrderID(v uuid.UUID) *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetLabOrderID(v)
	})
}

// UpdateLabOrderID sets the "lab_order_id" field to the value that was provided on create.
func (u *LabOrderLineUpsertBulk) UpdateLabOrderID() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateLabOrderID()
	})
}

// SetTestCode sets the "test_code" field.
func (u *LabOrderLineUpsertBulk) SetTestCode(v string) *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetTestCode(v)
	})
}

// UpdateTestCode sets the "test_code" field to the value that was provided on create.
func (u *LabOrderLineUpsertBulk) UpdateTestCode() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateTestCode()
	})
}

// SetTestName sets the "test_name" field.
func (u *LabOrderLineUpsertBulk) SetTestName(v string) *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetTestName(v)
	})
}

// UpdateTestName sets the "test_name" field to the value that was provided on create.
func (u *LabOrderLineUpsertBulk) UpdateTestName() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateTestName()
	})
}

// SetPrice sets the "price" field.
func (u *LabOrderLineUpsertBulk) SetPrice(v float64) *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *LabOrderLineUpsertBulk) AddPrice(v float64) *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *LabOrderLineUpsertBulk) UpdatePrice() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdatePrice()
	})
}

// SetSpecimenType sets the "specimen_type" field.
func (u *LabOrderLineUpsertBulk) SetSpecimenType(v string) *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetSpecimenType(v)
	})
}

// UpdateSpecimenType sets the "specimen_type" field to the value that was provided on create.
func (u *LabOrderLineUpsertBulk) UpdateSpecimenType() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateSpecimenType()
	})
}

// ClearSpecimenType clears the value of the "specimen_type" field.
func (u *LabOrderLineUpsertBulk) ClearSpecimenType() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearSpecimenType()
	})
}

// SetSpecimenCollectedAt sets the "specimen_collected_at" field.
func (u *LabOrderLineUpsertBulk) SetSpecimenCollectedAt(v time.Time) *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetSpecimenCollectedAt(v)
	})
}

// UpdateSpecimenCollectedAt sets the "specimen_collected_at" field to the value that was provided on create.
func (u *LabOrderLineUpsertBulk) UpdateSpecimenCollectedAt() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateSpecimenCollectedAt()
	})
}

// ClearSpecimenCollectedAt clears the value of the "specimen_collected_at" field.
func (u *LabOrderLineUpsertBulk) ClearSpecimenCollectedAt() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearSpecimenCollectedAt()
	})
}

// SetSpecimenCollectedBy sets the "specimen_collected_by" field.
func (u *LabOrderLineUpsertBulk) SetSpecimenCollectedBy(v uuid.UUID) *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetSpecimenCollectedBy(v)
	})
}

// UpdateSpecimenCollectedBy sets the "specimen_collected_by" field to the value that was provided on create.
func (u *LabOrderLineUpsertBulk) UpdateSpecimenCollectedBy() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateSpecimenCollectedBy()
	})
}

// ClearSpecimenCollectedBy clears the value of the "specimen_collected_by" field.
func (u *LabOrderLineUpsertBulk) ClearSpecimenCollectedBy() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearSpecimenCollectedBy()
	})
}

// SetSpecimenID sets the "specimen_id" field.
func (u *LabOrderLineUpsertBulk) SetSpecimenID(v string) *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetSpecimenID(v)
	})
}

// UpdateSpecimenID sets the "specimen_id" field to the value that was provided on create.
func (u *LabOrderLineUpsertBulk) UpdateSpecimenID() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateSpecimenID()
	})
}

// ClearSpecimenID clears the value of the "specimen_id" field.
func (u *LabOrderLineUpsertBulk) ClearSpecimenID() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearSpecimenID()
	})
}

// SetResultValue sets the "result_value" field.
func (u *LabOrderLineUpsertBulk) SetResultValue(v string) *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetResultValue(v)
	})
}

// UpdateResultValue sets the "result_value" field to the value that was provided on create.
func (u *LabOrderLineUpsertBulk) UpdateResultValue() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateResultValue()
	})
}

// ClearResultValue clears the value of the "result_value" field.
func (u *LabOrderLineUpsertBulk) ClearResultValue() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearResultValue()
	})
}

// SetUnit sets the "unit" field.
func (u *LabOrderLineUpsertBulk) SetUnit(v string) *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetUnit(v)
	})
}

// UpdateUnit sets the "unit" field to the value that was provided on create.
func (u *LabOrderLineUpsertBulk) UpdateUnit() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateUnit()
	})
}

// ClearUnit clears the value of the "unit" field.
func (u *LabOrderLineUpsertBulk) ClearUnit() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearUnit()
	})
}

// SetReferenceRange sets the "reference_range" field.
func (u *LabOrderLineUpsertBulk) SetReferenceRange(v string) *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetReferenceRange(v)
	})
}

// UpdateReferenceRange sets the "reference_range" field to the value that was provided on create.
func (u *LabOrderLineUpsertBulk) UpdateReferenceRange() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateReferenceRange()
	})
}

// ClearReferenceRange clears the value of the "reference_range" field.
func (u *LabOrderLineUpsertBulk) ClearReferenceRange() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearReferenceRange()
	})
}

// SetFlag sets the "flag" field.
func (u *LabOrderLineUpsertBulk) SetFlag(v laborderline.Flag) *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetFlag(v)
	})
}

// UpdateFlag sets the "flag" field to the value that was provided on create.
func (u *LabOrderLineUpsertBulk) UpdateFlag() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateFlag()
	})
}

// SetNotes sets the "notes" field.
func (u *LabOrderLineUpsertBulk) SetNotes(v string) *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *LabOrderLineUpsertBulk) UpdateNotes() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *LabOrderLineUpsertBulk) ClearNotes() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearNotes()
	})
}

// SetResultedBy sets the "resulted_by" field.
func (u *LabOrderLineUpsertBulk) SetResultedBy(v uuid.UUID) *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetResultedBy(v)
	})
}

// UpdateResultedBy sets the "resulted_by" field to the value that was provided on create.
func (u *LabOrderLineUpsertBulk) UpdateResultedBy() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateResultedBy()
	})
}

// ClearResultedBy clears the value of the "resulted_by" field.
func (u *LabOrderLineUpsertBulk) ClearResultedBy() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearResultedBy()
	})
}

// SetResultedAt sets the "resulted_at" field.
func (u *LabOrderLineUpsertBulk) SetResultedAt(v time.Time) *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.SetResultedAt(v)
	})
}

// UpdateResultedAt sets the "resulted_at" field to the value that was provided on create.
func (u *LabOrderLineUpsertBulk) UpdateResultedAt() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.UpdateResultedAt()
	})
}

// ClearResultedAt clears the value of the "resulted_at" field.
func (u *LabOrderLineUpsertBulk) ClearResultedAt() *LabOrderLineUpsertBulk {
	return u.Update(func(s *LabOrderLineUpsert) {
		s.ClearResultedAt()
	})
}

// Exec executes the query.
func (u *LabOrderLineUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LabOrderLineCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LabOrderLineCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LabOrderLineUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
