// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/hospital-service/internal/ent/admission"
	"github.com/bengobox/hospital-service/internal/ent/medicationadministration"
	"github.com/bengobox/hospital-service/internal/ent/prescriptionline"
	"github.com/google/uuid"
)

// MedicationAdministration is the model entity for the MedicationAdministration schema.
type MedicationAdministration struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// AdmissionID holds the value of the "admission_id" field.
	AdmissionID uuid.UUID `json:"admission_id,omitempty"`
	// PrescriptionLineID holds the value of the "prescription_line_id" field.
	PrescriptionLineID uuid.UUID `json:"prescription_line_id,omitempty"`
	// When this dose was due — defaults to charting time for the common on-time case, settable for a late-logged dose
	ScheduledTime time.Time `json:"scheduled_time,omitempty"`
	// Set only when status=given — a refused/missed/held dose has no real administration time
	AdministeredAt *time.Time `json:"administered_at,omitempty"`
	// The charting nurse — set regardless of status, since a refusal/miss/hold is still an observed, attributable event
	AdministeredBy *uuid.UUID `json:"administered_by,omitempty"`
	// Status holds the value of the "status" field.
	Status medicationadministration.Status `json:"status,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MedicationAdministrationQuery when eager-loading is set.
	Edges        MedicationAdministrationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MedicationAdministrationEdges holds the relations/edges for other nodes in the graph.
type MedicationAdministrationEdges struct {
	// Admission holds the value of the admission edge.
	Admission *Admission `json:"admission,omitempty"`
	// PrescriptionLine holds the value of the prescription_line edge.
	PrescriptionLine *PrescriptionLine `json:"prescription_line,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AdmissionOrErr returns the Admission value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MedicationAdministrationEdges) AdmissionOrErr() (*Admission, error) {
	if e.Admission != nil {
		return e.Admission, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: admission.Label}
	}
	return nil, &NotLoadedError{edge: "admission"}
}

// PrescriptionLineOrErr returns the PrescriptionLine value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MedicationAdministrationEdges) PrescriptionLineOrErr() (*PrescriptionLine, error) {
	if e.PrescriptionLine != nil {
		return e.PrescriptionLine, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: prescriptionline.Label}
	}
	return nil, &NotLoadedError{edge: "prescription_line"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MedicationAdministration) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case medicationadministration.FieldAdministeredBy:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case medicationadministration.FieldStatus, medicationadministration.FieldNotes:
			values[i] = new(sql.NullString)
		case medicationadministration.FieldScheduledTime, medicationadministration.FieldAdministeredAt, medicationadministration.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case medicationadministration.FieldID, medicationadministration.FieldTenantID, medicationadministration.FieldAdmissionID, medicationadministration.FieldPrescriptionLineID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MedicationAdministration fields.
func (_m *MedicationAdministration) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case medicationadministration.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case medicationadministration.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case medicationadministration.FieldAdmissionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field admission_id", values[i])
			} else if value != nil {
				_m.AdmissionID = *value
			}
		case medicationadministration.FieldPrescriptionLineID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field prescription_line_id", values[i])
			} else if value != nil {
				_m.PrescriptionLineID = *value
			}
		case medicationadministration.FieldScheduledTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field scheduled_time", values[i])
			} else if value.Valid {
				_m.ScheduledTime = value.Time
			}
		case medicationadministration.FieldAdministeredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field administered_at", values[i])
			} else if value.Valid {
				_m.AdministeredAt = new(time.Time)
				*_m.AdministeredAt = value.Time
			}
		case medicationadministration.FieldAdministeredBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field administered_by", values[i])
			} else if value.Valid {
				_m.AdministeredBy = new(uuid.UUID)
				*_m.AdministeredBy = *value.S.(*uuid.UUID)
			}
		case medicationadministration.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = medicationadministration.Status(value.String)
			}
		case medicationadministration.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case medicationadministration.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MedicationAdministration.
// This includes values selected through modifiers, order, etc.
func (_m *MedicationAdministration) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAdmission queries the "admission" edge of the MedicationAdministration entity.
func (_m *MedicationAdministration) QueryAdmission() *AdmissionQuery {
	return NewMedicationAdministrationClient(_m.config).QueryAdmission(_m)
}

// QueryPrescriptionLine queries the "prescription_line" edge of the MedicationAdministration entity.
func (_m *MedicationAdministration) QueryPrescriptionLine() *PrescriptionLineQuery {
	return NewMedicationAdministrationClient(_m.config).QueryPrescriptionLine(_m)
}

// Update returns a builder for updating this MedicationAdministration.
// Note that you need to call MedicationAdministration.Unwrap() before calling this method if this MedicationAdministration
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MedicationAdministration) Update() *MedicationAdministrationUpdateOne {
	return NewMedicationAdministrationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MedicationAdministration entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MedicationAdministration) Unwrap() *MedicationAdministration {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MedicationAdministration is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MedicationAdministration) String() string {
	var builder strings.Builder
	builder.WriteString("MedicationAdministration(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("admission_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AdmissionID))
	builder.WriteString(", ")
	builder.WriteString("prescription_line_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrescriptionLineID))
	builder.WriteString(", ")
	builder.WriteString("scheduled_time=")
	builder.WriteString(_m.ScheduledTime.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.AdministeredAt; v != nil {
		builder.WriteString("administered_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.AdministeredBy; v != nil {
		builder.WriteString("administered_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MedicationAdministrations is a parsable slice of MedicationAdministration.
type MedicationAdministrations []*MedicationAdministration
