// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/hospital-service/internal/ent/operativenote"
	"github.com/bengobox/hospital-service/internal/ent/theatrebooking"
	"github.com/google/uuid"
)

// OperativeNoteCreate is the builder for creating a OperativeNote entity.
type OperativeNoteCreate struct {
	config
	mutation *OperativeNoteMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *OperativeNoteCreate) SetTenantID(v uuid.UUID) *OperativeNoteCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetTheatreBookingID sets the "theatre_booking_id" field.
func (_c *OperativeNoteCreate) SetTheatreBookingID(v uuid.UUID) *OperativeNoteCreate {
	_c.mutation.SetTheatreBookingID(v)
	return _c
}

// SetSurgeonID sets the "surgeon_id" field.
func (_c *OperativeNoteCreate) SetSurgeonID(v uuid.UUID) *OperativeNoteCreate {
	_c.mutation.SetSurgeonID(v)
	return _c
}

// SetNillableSurgeonID sets the "surgeon_id" field if the given value is not nil.
func (_c *OperativeNoteCreate) SetNillableSurgeonID(v *uuid.UUID) *OperativeNoteCreate {
	if v != nil {
		_c.SetSurgeonID(*v)
	}
	return _c
}

// SetProcedurePerformed sets the "procedure_performed" field.
func (_c *OperativeNoteCreate) SetProcedurePerformed(v string) *OperativeNoteCreate {
	_c.mutation.SetProcedurePerformed(v)
	return _c
}

// SetFindings sets the "findings" field.
func (_c *OperativeNoteCreate) SetFindings(v string) *OperativeNoteCreate {
	_c.mutation.SetFindings(v)
	return _c
}

// SetNillableFindings sets the "findings" field if the given value is not nil.
func (_c *OperativeNoteCreate) SetNillableFindings(v *string) *OperativeNoteCreate {
	if v != nil {
		_c.SetFindings(*v)
	}
	return _c
}

// SetComplications sets the "complications" field.
func (_c *OperativeNoteCreate) SetComplications(v string) *OperativeNoteCreate {
	_c.mutation.SetComplications(v)
	return _c
}

// SetNillableComplications sets the "complications" field if the given value is not nil.
func (_c *OperativeNoteCreate) SetNillableComplications(v *string) *OperativeNoteCreate {
	if v != nil {
		_c.SetComplications(*v)
	}
	return _c
}

// SetEstimatedBloodLossMl sets the "estimated_blood_loss_ml" field.
func (_c *OperativeNoteCreate) SetEstimatedBloodLossMl(v float64) *OperativeNoteCreate {
	_c.mutation.SetEstimatedBloodLossMl(v)
	return _c
}

// SetNillableEstimatedBloodLossMl sets the "estimated_blood_loss_ml" field if the given value is not nil.
func (_c *OperativeNoteCreate) SetNillableEstimatedBloodLossMl(v *float64) *OperativeNoteCreate {
	if v != nil {
		_c.SetEstimatedBloodLossMl(*v)
	}
	return _c
}

// SetImplantsUsed sets the "implants_used" field.
func (_c *OperativeNoteCreate) SetImplantsUsed(v string) *OperativeNoteCreate {
	_c.mutation.SetImplantsUsed(v)
	return _c
}

// SetNillableImplantsUsed sets the "implants_used" field if the given value is not nil.
func (_c *OperativeNoteCreate) SetNillableImplantsUsed(v *string) *OperativeNoteCreate {
	if v != nil {
		_c.SetImplantsUsed(*v)
	}
	return _c
}

// SetSpecimensSent sets the "specimens_sent" field.
func (_c *OperativeNoteCreate) SetSpecimensSent(v bool) *OperativeNoteCreate {
	_c.mutation.SetSpecimensSent(v)
	return _c
}

// SetNillableSpecimensSent sets the "specimens_sent" field if the given value is not nil.
func (_c *OperativeNoteCreate) SetNillableSpecimensSent(v *bool) *OperativeNoteCreate {
	if v != nil {
		_c.SetSpecimensSent(*v)
	}
	return _c
}

// SetSpecimensDescription sets the "specimens_description" field.
func (_c *OperativeNoteCreate) SetSpecimensDescription(v string) *OperativeNoteCreate {
	_c.mutation.SetSpecimensDescription(v)
	return _c
}

// SetNillableSpecimensDescription sets the "specimens_description" field if the given value is not nil.
func (_c *OperativeNoteCreate) SetNillableSpecimensDescription(v *string) *OperativeNoteCreate {
	if v != nil {
		_c.SetSpecimensDescription(*v)
	}
	return _c
}

// SetPostOpDiagnosis sets the "post_op_diagnosis" field.
func (_c *OperativeNoteCreate) SetPostOpDiagnosis(v string) *OperativeNoteCreate {
	_c.mutation.SetPostOpDiagnosis(v)
	return _c
}

// SetNillablePostOpDiagnosis sets the "post_op_diagnosis" field if the given value is not nil.
func (_c *OperativeNoteCreate) SetNillablePostOpDiagnosis(v *string) *OperativeNoteCreate {
	if v != nil {
		_c.SetPostOpDiagnosis(*v)
	}
	return _c
}

// SetAuthoredBy sets the "authored_by" field.
func (_c *OperativeNoteCreate) SetAuthoredBy(v uuid.UUID) *OperativeNoteCreate {
	_c.mutation.SetAuthoredBy(v)
	return _c
}

// SetNillableAuthoredBy sets the "authored_by" field if the given value is not nil.
func (_c *OperativeNoteCreate) SetNillableAuthoredBy(v *uuid.UUID) *OperativeNoteCreate {
	if v != nil {
		_c.SetAuthoredBy(*v)
	}
	return _c
}

// SetAuthoredAt sets the "authored_at" field.
func (_c *OperativeNoteCreate) SetAuthoredAt(v time.Time) *OperativeNoteCreate {
	_c.mutation.SetAuthoredAt(v)
	return _c
}

// SetNillableAuthoredAt sets the "authored_at" field if the given value is not nil.
func (_c *OperativeNoteCreate) SetNillableAuthoredAt(v *time.Time) *OperativeNoteCreate {
	if v != nil {
		_c.SetAuthoredAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OperativeNoteCreate) SetID(v uuid.UUID) *OperativeNoteCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OperativeNoteCreate) SetNillableID(v *uuid.UUID) *OperativeNoteCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTheatreBooking sets the "theatre_booking" edge to the TheatreBooking entity.
func (_c *OperativeNoteCreate) SetTheatreBooking(v *TheatreBooking) *OperativeNoteCreate {
	return _c.SetTheatreBookingID(v.ID)
}

// Mutation returns the OperativeNoteMutation object of the builder.
func (_c *OperativeNoteCreate) Mutation() *OperativeNoteMutation {
	return _c.mutation
}

// Save creates the OperativeNote in the database.
func (_c *OperativeNoteCreate) Save(ctx context.Context) (*OperativeNote, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OperativeNoteCreate) SaveX(ctx context.Context) *OperativeNote {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OperativeNoteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OperativeNoteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OperativeNoteCreate) defaults() {
	if _, ok := _c.mutation.SpecimensSent(); !ok {
		v := operativenote.DefaultSpecimensSent
		_c.mutation.SetSpecimensSent(v)
	}
	if _, ok := _c.mutation.AuthoredAt(); !ok {
		v := operativenote.DefaultAuthoredAt()
		_c.mutation.SetAuthoredAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := operativenote.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OperativeNoteCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "OperativeNote.tenant_id"`)}
	}
	if _, ok := _c.mutation.TheatreBookingID(); !ok {
		return &ValidationError{Name: "theatre_booking_id", err: errors.New(`ent: missing required field "OperativeNote.theatre_booking_id"`)}
	}
	if _, ok := _c.mutation.ProcedurePerformed(); !ok {
		return &ValidationError{Name: "procedure_performed", err: errors.New(`ent: missing required field "OperativeNote.procedure_performed"`)}
	}
	if v, ok := _c.mutation.ProcedurePerformed(); ok {
		if err := operativenote.ProcedurePerformedValidator(v); err != nil {
			return &ValidationError{Name: "procedure_performed", err: fmt.Errorf(`ent: validator failed for field "OperativeNote.procedure_performed": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SpecimensSent(); !ok {
		return &ValidationError{Name: "specimens_sent", err: errors.New(`ent: missing required field "OperativeNote.specimens_sent"`)}
	}
	if _, ok := _c.mutation.AuthoredAt(); !ok {
		return &ValidationError{Name: "authored_at", err: errors.New(`ent: missing required field "OperativeNote.authored_at"`)}
	}
	if len(_c.mutation.TheatreBookingIDs()) == 0 {
		return &ValidationError{Name: "theatre_booking", err: errors.New(`ent: missing required edge "OperativeNote.theatre_booking"`)}
	}
	return nil
}

func (_c *OperativeNoteCreate) sqlSave(ctx context.Context) (*OperativeNote, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OperativeNoteCreate) createSpec() (*OperativeNote, *sqlgraph.CreateSpec) {
	var (
		_node = &OperativeNote{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(operativenote.Table, sqlgraph.NewFieldSpec(operativenote.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(operativenote.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.SurgeonID(); ok {
		_spec.SetField(operativenote.FieldSurgeonID, field.TypeUUID, value)
		_node.SurgeonID = &value
	}
	if value, ok := _c.mutation.ProcedurePerformed(); ok {
		_spec.SetField(operativenote.FieldProcedurePerformed, field.TypeString, value)
		_node.ProcedurePerformed = value
	}
	if value, ok := _c.mutation.Findings(); ok {
		_spec.SetField(operativenote.FieldFindings, field.TypeString, value)
		_node.Findings = value
	}
	if value, ok := _c.mutation.Complications(); ok {
		_spec.SetField(operativenote.FieldComplications, field.TypeString, value)
		_node.Complications = value
	}
	if value, ok := _c.mutation.EstimatedBloodLossMl(); ok {
		_spec.SetField(operativenote.FieldEstimatedBloodLossMl, field.TypeFloat64, value)
		_node.EstimatedBloodLossMl = &value
	}
	if value, ok := _c.mutation.ImplantsUsed(); ok {
		_spec.SetField(operativenote.FieldImplantsUsed, field.TypeString, value)
		_node.ImplantsUsed = value
	}
	if value, ok := _c.mutation.SpecimensSent(); ok {
		_spec.SetField(operativenote.FieldSpecimensSent, field.TypeBool, value)
		_node.SpecimensSent = value
	}
	if value, ok := _c.mutation.SpecimensDescription(); ok {
		_spec.SetField(operativenote.FieldSpecimensDescription, field.TypeString, value)
		_node.SpecimensDescription = value
	}
	if value, ok := _c.mutation.PostOpDiagnosis(); ok {
		_spec.SetField(operativenote.FieldPostOpDiagnosis, field.TypeString, value)
		_node.PostOpDiagnosis = value
	}
	if value, ok := _c.mutation.AuthoredBy(); ok {
		_spec.SetField(operativenote.FieldAuthoredBy, field.TypeUUID, value)
		_node.AuthoredBy = &value
	}
	if value, ok := _c.mutation.AuthoredAt(); ok {
		_spec.SetField(operativenote.FieldAuthoredAt, field.TypeTime, value)
		_node.AuthoredAt = value
	}
	if nodes := _c.mutation.TheatreBookingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   operativenote.TheatreBookingTable,
			Columns: []string{operativenote.TheatreBookingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(theatrebooking.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TheatreBookingID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OperativeNote.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OperativeNoteUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *OperativeNoteCreate) OnConflict(opts ...sql.ConflictOption) *OperativeNoteUpsertOne {
	_c.conflict = opts
	return &OperativeNoteUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OperativeNote.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OperativeNoteCreate) OnConflictColumns(columns ...string) *OperativeNoteUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OperativeNoteUpsertOne{
		create: _c,
	}
}

type (
	// OperativeNoteUpsertOne is the builder for "upsert"-ing
	//  one OperativeNote node.
	OperativeNoteUpsertOne struct {
		create *OperativeNoteCreate
	}

	// OperativeNoteUpsert is the "OnConflict" setter.
	OperativeNoteUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *OperativeNoteUpsert) SetTenantID(v uuid.UUID) *OperativeNoteUpsert {
	u.Set(operativenote.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *OperativeNoteUpsert) UpdateTenantID() *OperativeNoteUpsert {
	u.SetExcluded(operativenote.FieldTenantID)
	return u
}

// SetTheatreBookingID sets the "theatre_booking_id" field.
func (u *OperativeNoteUpsert) SetTheatreBookingID(v uuid.UUID) *OperativeNoteUpsert {
	u.Set(operativenote.FieldTheatreBookingID, v)
	return u
}

// UpdateTheatreBookingID sets the "theatre_booking_id" field to the value that was provided on create.
func (u *OperativeNoteUpsert) UpdateTheatreBookingID() *OperativeNoteUpsert {
	u.SetExcluded(operativenote.FieldTheatreBookingID)
	return u
}

// SetSurgeonID sets the "surgeon_id" field.
func (u *OperativeNoteUpsert) SetSurgeonID(v uuid.UUID) *OperativeNoteUpsert {
	u.Set(operativenote.FieldSurgeonID, v)
	return u
}

// UpdateSurgeonID sets the "surgeon_id" field to the value that was provided on create.
func (u *OperativeNoteUpsert) UpdateSurgeonID() *OperativeNoteUpsert {
	u.SetExcluded(operativenote.FieldSurgeonID)
	return u
}

// ClearSurgeonID clears the value of the "surgeon_id" field.
func (u *OperativeNoteUpsert) ClearSurgeonID() *OperativeNoteUpsert {
	u.SetNull(operativenote.FieldSurgeonID)
	return u
}

// SetProcedurePerformed sets the "procedure_performed" field.
func (u *OperativeNoteUpsert) SetProcedurePerformed(v string) *OperativeNoteUpsert {
	u.Set(operativenote.FieldProcedurePerformed, v)
	return u
}

// UpdateProcedurePerformed sets the "procedure_performed" field to the value that was provided on create.
func (u *OperativeNoteUpsert) UpdateProcedurePerformed() *OperativeNoteUpsert {
	u.SetExcluded(operativenote.FieldProcedurePerformed)
	return u
}

// SetFindings sets the "findings" field.
func (u *OperativeNoteUpsert) SetFindings(v string) *OperativeNoteUpsert {
	u.Set(operativenote.FieldFindings, v)
	return u
}

// UpdateFindings sets the "findings" field to the value that was provided on create.
func (u *OperativeNoteUpsert) UpdateFindings() *OperativeNoteUpsert {
	u.SetExcluded(operativenote.FieldFindings)
	return u
}

// ClearFindings clears the value of the "findings" field.
func (u *OperativeNoteUpsert) ClearFindings() *OperativeNoteUpsert {
	u.SetNull(operativenote.FieldFindings)
	return u
}

// SetComplications sets the "complications" field.
func (u *OperativeNoteUpsert) SetComplications(v string) *OperativeNoteUpsert {
	u.Set(operativenote.FieldComplications, v)
	return u
}

// UpdateComplications sets the "complications" field to the value that was provided on create.
func (u *OperativeNoteUpsert) UpdateComplications() *OperativeNoteUpsert {
	u.SetExcluded(operativenote.FieldComplications)
	return u
}

// ClearComplications clears the value of the "complications" field.
func (u *OperativeNoteUpsert) ClearComplications() *OperativeNoteUpsert {
	u.SetNull(operativenote.FieldComplications)
	return u
}

// SetEstimatedBloodLossMl sets the "estimated_blood_loss_ml" field.
func (u *OperativeNoteUpsert) SetEstimatedBloodLossMl(v float64) *OperativeNoteUpsert {
	u.Set(operativenote.FieldEstimatedBloodLossMl, v)
	return u
}

// UpdateEstimatedBloodLossMl sets the "estimated_blood_loss_ml" field to the value that was provided on create.
func (u *OperativeNoteUpsert) UpdateEstimatedBloodLossMl() *OperativeNoteUpsert {
	u.SetExcluded(operativenote.FieldEstimatedBloodLossMl)
	return u
}

// AddEstimatedBloodLossMl adds v to the "estimated_blood_loss_ml" field.
func (u *OperativeNoteUpsert) AddEstimatedBloodLossMl(v float64) *OperativeNoteUpsert {
	u.Add(operativenote.FieldEstimatedBloodLossMl, v)
	return u
}

// ClearEstimatedBloodLossMl clears the value of the "estimated_blood_loss_ml" field.
func (u *OperativeNoteUpsert) ClearEstimatedBloodLossMl() *OperativeNoteUpsert {
	u.SetNull(operativenote.FieldEstimatedBloodLossMl)
	return u
}

// SetImplantsUsed sets the "implants_used" field.
func (u *OperativeNoteUpsert) SetImplantsUsed(v string) *OperativeNoteUpsert {
	u.Set(operativenote.FieldImplantsUsed, v)
	return u
}

// UpdateImplantsUsed sets the "implants_used" field to the value that was provided on create.
func (u *OperativeNoteUpsert) UpdateImplantsUsed() *OperativeNoteUpsert {
	u.SetExcluded(operativenote.FieldImplantsUsed)
	return u
}

// ClearImplantsUsed clears the value of the "implants_used" field.
func (u *OperativeNoteUpsert) ClearImplantsUsed() *OperativeNoteUpsert {
	u.SetNull(operativenote.FieldImplantsUsed)
	return u
}

// SetSpecimensSent sets the "specimens_sent" field.
func (u *OperativeNoteUpsert) SetSpecimensSent(v bool) *OperativeNoteUpsert {
	u.Set(operativenote.FieldSpecimensSent, v)
	return u
}

// UpdateSpecimensSent sets the "specimens_sent" field to the value that was provided on create.
func (u *OperativeNoteUpsert) UpdateSpecimensSent() *OperativeNoteUpsert {
	u.SetExcluded(operativenote.FieldSpecimensSent)
	return u
}

// SetSpecimensDescription sets the "specimens_description" field.
func (u *OperativeNoteUpsert) SetSpecimensDescription(v string) *OperativeNoteUpsert {
	u.Set(operativenote.FieldSpecimensDescription, v)
	return u
}

// UpdateSpecimensDescription sets the "specimens_description" field to the value that was provided on create.
func (u *OperativeNoteUpsert) UpdateSpecimensDescription() *OperativeNoteUpsert {
	u.SetExcluded(operativenote.FieldSpecimensDescription)
	return u
}

// ClearSpecimensDescription clears the value of the "specimens_description" field.
func (u *OperativeNoteUpsert) ClearSpecimensDescription() *OperativeNoteUpsert {
	u.SetNull(operativenote.FieldSpecimensDescription)
	return u
}

// SetPostOpDiagnosis sets the "post_op_diagnosis" field.
func (u *OperativeNoteUpsert) SetPostOpDiagnosis(v string) *OperativeNoteUpsert {
	u.Set(operativenote.FieldPostOpDiagnosis, v)
	return u
}

// UpdatePostOpDiagnosis sets the "post_op_diagnosis" field to the value that was provided on create.
func (u *OperativeNoteUpsert) UpdatePostOpDiagnosis() *OperativeNoteUpsert {
	u.SetExcluded(operativenote.FieldPostOpDiagnosis)
	return u
}

// ClearPostOpDiagnosis clears the value of the "post_op_diagnosis" field.
func (u *OperativeNoteUpsert) ClearPostOpDiagnosis() *OperativeNoteUpsert {
	u.SetNull(operativenote.FieldPostOpDiagnosis)
	return u
}

// SetAuthoredBy sets the "authored_by" field.
func (u *OperativeNoteUpsert) SetAuthoredBy(v uuid.UUID) *OperativeNoteUpsert {
	u.Set(operativenote.FieldAuthoredBy, v)
	return u
}

// UpdateAuthoredBy sets the "authored_by" field to the value that was provided on create.
func (u *OperativeNoteUpsert) UpdateAuthoredBy() *OperativeNoteUpsert {
	u.SetExcluded(operativenote.FieldAuthoredBy)
	return u
}

// ClearAuthoredBy clears the value of the "authored_by" field.
func (u *OperativeNoteUpsert) ClearAuthoredBy() *OperativeNoteUpsert {
	u.SetNull(operativenote.FieldAuthoredBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.OperativeNote.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(operativenote.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OperativeNoteUpsertOne) UpdateNewValues() *OperativeNoteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(operativenote.FieldID)
		}
		if _, exists := u.create.mutation.AuthoredAt(); exists {
			s.SetIgnore(operativenote.FieldAuthoredAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OperativeNote.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OperativeNoteUpsertOne) Ignore() *OperativeNoteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OperativeNoteUpsertOne) DoNothing() *OperativeNoteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OperativeNoteCreate.OnConflict
// documentation for more info.
func (u *OperativeNoteUpsertOne) Update(set func(*OperativeNoteUpsert)) *OperativeNoteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OperativeNoteUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *OperativeNoteUpsertOne) SetTenantID(v uuid.UUID) *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *OperativeNoteUpsertOne) UpdateTenantID() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateTenantID()
	})
}

// SetTheatreBookingID sets the "theatre_booking_id" field.
func (u *OperativeNoteUpsertOne) SetTheatreBookingID(v uuid.UUID) *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetTheatreBookingID(v)
	})
}

// UpdateTheatreBookingID sets the "theatre_booking_id" field to the value that was provided on create.
func (u *OperativeNoteUpsertOne) UpdateTheatreBookingID() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateTheatreBookingID()
	})
}

// SetSurgeonID sets the "surgeon_id" field.
func (u *OperativeNoteUpsertOne) SetSurgeonID(v uuid.UUID) *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetSurgeonID(v)
	})
}

// UpdateSurgeonID sets the "surgeon_id" field to the value that was provided on create.
func (u *OperativeNoteUpsertOne) UpdateSurgeonID() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateSurgeonID()
	})
}

// ClearSurgeonID clears the value of the "surgeon_id" field.
func (u *OperativeNoteUpsertOne) ClearSurgeonID() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.ClearSurgeonID()
	})
}

// SetProcedurePerformed sets the "procedure_performed" field.
func (u *OperativeNoteUpsertOne) SetProcedurePerformed(v string) *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetProcedurePerformed(v)
	})
}

// UpdateProcedurePerformed sets the "procedure_performed" field to the value that was provided on create.
func (u *OperativeNoteUpsertOne) UpdateProcedurePerformed() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateProcedurePerformed()
	})
}

// SetFindings sets the "findings" field.
func (u *OperativeNoteUpsertOne) SetFindings(v string) *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetFindings(v)
	})
}

// UpdateFindings sets the "findings" field to the value that was provided on create.
func (u *OperativeNoteUpsertOne) UpdateFindings() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateFindings()
	})
}

// ClearFindings clears the value of the "findings" field.
func (u *OperativeNoteUpsertOne) ClearFindings() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.ClearFindings()
	})
}

// SetComplications sets the "complications" field.
func (u *OperativeNoteUpsertOne) SetComplications(v string) *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetComplications(v)
	})
}

// UpdateComplications sets the "complications" field to the value that was provided on create.
func (u *OperativeNoteUpsertOne) UpdateComplications() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateComplications()
	})
}

// ClearComplications clears the value of the "complications" field.
func (u *OperativeNoteUpsertOne) ClearComplications() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.ClearComplications()
	})
}

// SetEstimatedBloodLossMl sets the "estimated_blood_loss_ml" field.
func (u *OperativeNoteUpsertOne) SetEstimatedBloodLossMl(v float64) *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetEstimatedBloodLossMl(v)
	})
}

// AddEstimatedBloodLossMl adds v to the "estimated_blood_loss_ml" field.
func (u *OperativeNoteUpsertOne) AddEstimatedBloodLossMl(v float64) *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.AddEstimatedBloodLossMl(v)
	})
}

// UpdateEstimatedBloodLossMl sets the "estimated_blood_loss_ml" field to the value that was provided on create.
func (u *OperativeNoteUpsertOne) UpdateEstimatedBloodLossMl() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateEstimatedBloodLossMl()
	})
}

// ClearEstimatedBloodLossMl clears the value of the "estimated_blood_loss_ml" field.
func (u *OperativeNoteUpsertOne) ClearEstimatedBloodLossMl() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.ClearEstimatedBloodLossMl()
	})
}

// SetImplantsUsed sets the "implants_used" field.
func (u *OperativeNoteUpsertOne) SetImplantsUsed(v string) *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetImplantsUsed(v)
	})
}

// UpdateImplantsUsed sets the "implants_used" field to the value that was provided on create.
func (u *OperativeNoteUpsertOne) UpdateImplantsUsed() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateImplantsUsed()
	})
}

// ClearImplantsUsed clears the value of the "implants_used" field.
func (u *OperativeNoteUpsertOne) ClearImplantsUsed() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.ClearImplantsUsed()
	})
}

// SetSpecimensSent sets the "specimens_sent" field.
func (u *OperativeNoteUpsertOne) SetSpecimensSent(v bool) *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetSpecimensSent(v)
	})
}

// UpdateSpecimensSent sets the "specimens_sent" field to the value that was provided on create.
func (u *OperativeNoteUpsertOne) UpdateSpecimensSent() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateSpecimensSent()
	})
}

// SetSpecimensDescription sets the "specimens_description" field.
func (u *OperativeNoteUpsertOne) SetSpecimensDescription(v string) *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetSpecimensDescription(v)
	})
}

// UpdateSpecimensDescription sets the "specimens_description" field to the value that was provided on create.
func (u *OperativeNoteUpsertOne) UpdateSpecimensDescription() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateSpecimensDescription()
	})
}

// ClearSpecimensDescription clears the value of the "specimens_description" field.
func (u *OperativeNoteUpsertOne) ClearSpecimensDescription() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.ClearSpecimensDescription()
	})
}

// SetPostOpDiagnosis sets the "post_op_diagnosis" field.
func (u *OperativeNoteUpsertOne) SetPostOpDiagnosis(v string) *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetPostOpDiagnosis(v)
	})
}

// UpdatePostOpDiagnosis sets the "post_op_diagnosis" field to the value that was provided on create.
func (u *OperativeNoteUpsertOne) UpdatePostOpDiagnosis() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdatePostOpDiagnosis()
	})
}

// ClearPostOpDiagnosis clears the value of the "post_op_diagnosis" field.
func (u *OperativeNoteUpsertOne) ClearPostOpDiagnosis() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.ClearPostOpDiagnosis()
	})
}

// SetAuthoredBy sets the "authored_by" field.
func (u *OperativeNoteUpsertOne) SetAuthoredBy(v uuid.UUID) *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetAuthoredBy(v)
	})
}

// UpdateAuthoredBy sets the "authored_by" field to the value that was provided on create.
func (u *OperativeNoteUpsertOne) UpdateAuthoredBy() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateAuthoredBy()
	})
}

// ClearAuthoredBy clears the value of the "authored_by" field.
func (u *OperativeNoteUpsertOne) ClearAuthoredBy() *OperativeNoteUpsertOne {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.ClearAuthoredBy()
	})
}

// Exec executes the query.
func (u *OperativeNoteUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OperativeNoteCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OperativeNoteUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OperativeNoteUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: OperativeNoteUpsertOne.ID is not supported by MySQL driver. Use OperativeNoteUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OperativeNoteUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OperativeNoteCreateBulk is the builder for creating many OperativeNote entities in bulk.
type OperativeNoteCreateBulk struct {
	config
	err      error
	builders []*OperativeNoteCreate
	conflict []sql.ConflictOption
}

// Save creates the OperativeNote entities in the database.
func (_c *OperativeNoteCreateBulk) Save(ctx context.Context) ([]*OperativeNote, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OperativeNote, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OperativeNoteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OperativeNoteCreateBulk) SaveX(ctx context.Context) []*OperativeNote {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OperativeNoteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OperativeNoteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OperativeNote.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OperativeNoteUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *OperativeNoteCreateBulk) OnConflict(opts ...sql.ConflictOption) *OperativeNoteUpsertBulk {
	_c.conflict = opts
	return &OperativeNoteUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OperativeNote.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OperativeNoteCreateBulk) OnConflictColumns(columns ...string) *OperativeNoteUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OperativeNoteUpsertBulk{
		create: _c,
	}
}

// OperativeNoteUpsertBulk is the builder for "upsert"-ing
// a bulk of OperativeNote nodes.
type OperativeNoteUpsertBulk struct {
	create *OperativeNoteCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OperativeNote.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(operativenote.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OperativeNoteUpsertBulk) UpdateNewValues() *OperativeNoteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(operativenote.FieldID)
			}
			if _, exists := b.mutation.AuthoredAt(); exists {
				s.SetIgnore(operativenote.FieldAuthoredAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OperativeNote.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OperativeNoteUpsertBulk) Ignore() *OperativeNoteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OperativeNoteUpsertBulk) DoNothing() *OperativeNoteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OperativeNoteCreateBulk.OnConflict
// documentation for more info.
func (u *OperativeNoteUpsertBulk) Update(set func(*OperativeNoteUpsert)) *OperativeNoteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OperativeNoteUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *OperativeNoteUpsertBulk) SetTenantID(v uuid.UUID) *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *OperativeNoteUpsertBulk) UpdateTenantID() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateTenantID()
	})
}

// SetTheatreBookingID sets the "theatre_booking_id" field.
func (u *OperativeNoteUpsertBulk) SetTheatreBookingID(v uuid.UUID) *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetTheatreBookingID(v)
	})
}

// UpdateTheatreBookingID sets the "theatre_booking_id" field to the value that was provided on create.
func (u *OperativeNoteUpsertBulk) UpdateTheatreBookingID() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateTheatreBookingID()
	})
}

// SetSurgeonID sets the "surgeon_id" field.
func (u *OperativeNoteUpsertBulk) SetSurgeonID(v uuid.UUID) *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetSurgeonID(v)
	})
}

// UpdateSurgeonID sets the "surgeon_id" field to the value that was provided on create.
func (u *OperativeNoteUpsertBulk) UpdateSurgeonID() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateSurgeonID()
	})
}

// ClearSurgeonID clears the value of the "surgeon_id" field.
func (u *OperativeNoteUpsertBulk) ClearSurgeonID() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.ClearSurgeonID()
	})
}

// SetProcedurePerformed sets the "procedure_performed" field.
func (u *OperativeNoteUpsertBulk) SetProcedurePerformed(v string) *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetProcedurePerformed(v)
	})
}

// UpdateProcedurePerformed sets the "procedure_performed" field to the value that was provided on create.
func (u *OperativeNoteUpsertBulk) UpdateProcedurePerformed() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateProcedurePerformed()
	})
}

// SetFindings sets the "findings" field.
func (u *OperativeNoteUpsertBulk) SetFindings(v string) *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetFindings(v)
	})
}

// UpdateFindings sets the "findings" field to the value that was provided on create.
func (u *OperativeNoteUpsertBulk) UpdateFindings() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateFindings()
	})
}

// ClearFindings clears the value of the "findings" field.
func (u *OperativeNoteUpsertBulk) ClearFindings() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.ClearFindings()
	})
}

// SetComplications sets the "complications" field.
func (u *OperativeNoteUpsertBulk) SetComplications(v string) *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetComplications(v)
	})
}

// UpdateComplications sets the "complications" field to the value that was provided on create.
func (u *OperativeNoteUpsertBulk) UpdateComplications() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateComplications()
	})
}

// ClearComplications clears the value of the "complications" field.
func (u *OperativeNoteUpsertBulk) ClearComplications() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.ClearComplications()
	})
}

// SetEstimatedBloodLossMl sets the "estimated_blood_loss_ml" field.
func (u *OperativeNoteUpsertBulk) SetEstimatedBloodLossMl(v float64) *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetEstimatedBloodLossMl(v)
	})
}

// AddEstimatedBloodLossMl adds v to the "estimated_blood_loss_ml" field.
func (u *OperativeNoteUpsertBulk) AddEstimatedBloodLossMl(v float64) *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.AddEstimatedBloodLossMl(v)
	})
}

// UpdateEstimatedBloodLossMl sets the "estimated_blood_loss_ml" field to the value that was provided on create.
func (u *OperativeNoteUpsertBulk) UpdateEstimatedBloodLossMl() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateEstimatedBloodLossMl()
	})
}

// ClearEstimatedBloodLossMl clears the value of the "estimated_blood_loss_ml" field.
func (u *OperativeNoteUpsertBulk) ClearEstimatedBloodLossMl() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.ClearEstimatedBloodLossMl()
	})
}

// SetImplantsUsed sets the "implants_used" field.
func (u *OperativeNoteUpsertBulk) SetImplantsUsed(v string) *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetImplantsUsed(v)
	})
}

// UpdateImplantsUsed sets the "implants_used" field to the value that was provided on create.
func (u *OperativeNoteUpsertBulk) UpdateImplantsUsed() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateImplantsUsed()
	})
}

// ClearImplantsUsed clears the value of the "implants_used" field.
func (u *OperativeNoteUpsertBulk) ClearImplantsUsed() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.ClearImplantsUsed()
	})
}

// SetSpecimensSent sets the "specimens_sent" field.
func (u *OperativeNoteUpsertBulk) SetSpecimensSent(v bool) *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetSpecimensSent(v)
	})
}

// UpdateSpecimensSent sets the "specimens_sent" field to the value that was provided on create.
func (u *OperativeNoteUpsertBulk) UpdateSpecimensSent() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateSpecimensSent()
	})
}

// SetSpecimensDescription sets the "specimens_description" field.
func (u *OperativeNoteUpsertBulk) SetSpecimensDescription(v string) *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetSpecimensDescription(v)
	})
}

// UpdateSpecimensDescription sets the "specimens_description" field to the value that was provided on create.
func (u *OperativeNoteUpsertBulk) UpdateSpecimensDescription() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateSpecimensDescription()
	})
}

// ClearSpecimensDescription clears the value of the "specimens_description" field.
func (u *OperativeNoteUpsertBulk) ClearSpecimensDescription() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.ClearSpecimensDescription()
	})
}

// SetPostOpDiagnosis sets the "post_op_diagnosis" field.
func (u *OperativeNoteUpsertBulk) SetPostOpDiagnosis(v string) *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetPostOpDiagnosis(v)
	})
}

// UpdatePostOpDiagnosis sets the "post_op_diagnosis" field to the value that was provided on create.
func (u *OperativeNoteUpsertBulk) UpdatePostOpDiagnosis() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdatePostOpDiagnosis()
	})
}

// ClearPostOpDiagnosis clears the value of the "post_op_diagnosis" field.
func (u *OperativeNoteUpsertBulk) ClearPostOpDiagnosis() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.ClearPostOpDiagnosis()
	})
}

// SetAuthoredBy sets the "authored_by" field.
func (u *OperativeNoteUpsertBulk) SetAuthoredBy(v uuid.UUID) *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.SetAuthoredBy(v)
	})
}

// UpdateAuthoredBy sets the "authored_by" field to the value that was provided on create.
func (u *OperativeNoteUpsertBulk) UpdateAuthoredBy() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.UpdateAuthoredBy()
	})
}

// ClearAuthoredBy clears the value of the "authored_by" field.
func (u *OperativeNoteUpsertBulk) ClearAuthoredBy() *OperativeNoteUpsertBulk {
	return u.Update(func(s *OperativeNoteUpsert) {
		s.ClearAuthoredBy()
	})
}

// Exec executes the query.
func (u *OperativeNoteUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OperativeNoteCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OperativeNoteCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OperativeNoteUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
