// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/hospital-service/internal/ent/billablecharge"
	"github.com/bengobox/hospital-service/internal/ent/patientaccount"
	"github.com/google/uuid"
)

// PatientAccountCreate is the builder for creating a PatientAccount entity.
type PatientAccountCreate struct {
	config
	mutation *PatientAccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *PatientAccountCreate) SetTenantID(v uuid.UUID) *PatientAccountCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetPatientID sets the "patient_id" field.
func (_c *PatientAccountCreate) SetPatientID(v uuid.UUID) *PatientAccountCreate {
	_c.mutation.SetPatientID(v)
	return _c
}

// SetVisitID sets the "visit_id" field.
func (_c *PatientAccountCreate) SetVisitID(v uuid.UUID) *PatientAccountCreate {
	_c.mutation.SetVisitID(v)
	return _c
}

// SetNillableVisitID sets the "visit_id" field if the given value is not nil.
func (_c *PatientAccountCreate) SetNillableVisitID(v *uuid.UUID) *PatientAccountCreate {
	if v != nil {
		_c.SetVisitID(*v)
	}
	return _c
}

// SetAdmissionID sets the "admission_id" field.
func (_c *PatientAccountCreate) SetAdmissionID(v uuid.UUID) *PatientAccountCreate {
	_c.mutation.SetAdmissionID(v)
	return _c
}

// SetNillableAdmissionID sets the "admission_id" field if the given value is not nil.
func (_c *PatientAccountCreate) SetNillableAdmissionID(v *uuid.UUID) *PatientAccountCreate {
	if v != nil {
		_c.SetAdmissionID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PatientAccountCreate) SetStatus(v patientaccount.Status) *PatientAccountCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PatientAccountCreate) SetNillableStatus(v *patientaccount.Status) *PatientAccountCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTotalCharged sets the "total_charged" field.
func (_c *PatientAccountCreate) SetTotalCharged(v float64) *PatientAccountCreate {
	_c.mutation.SetTotalCharged(v)
	return _c
}

// SetNillableTotalCharged sets the "total_charged" field if the given value is not nil.
func (_c *PatientAccountCreate) SetNillableTotalCharged(v *float64) *PatientAccountCreate {
	if v != nil {
		_c.SetTotalCharged(*v)
	}
	return _c
}

// SetTotalPaid sets the "total_paid" field.
func (_c *PatientAccountCreate) SetTotalPaid(v float64) *PatientAccountCreate {
	_c.mutation.SetTotalPaid(v)
	return _c
}

// SetNillableTotalPaid sets the "total_paid" field if the given value is not nil.
func (_c *PatientAccountCreate) SetNillableTotalPaid(v *float64) *PatientAccountCreate {
	if v != nil {
		_c.SetTotalPaid(*v)
	}
	return _c
}

// SetBalance sets the "balance" field.
func (_c *PatientAccountCreate) SetBalance(v float64) *PatientAccountCreate {
	_c.mutation.SetBalance(v)
	return _c
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_c *PatientAccountCreate) SetNillableBalance(v *float64) *PatientAccountCreate {
	if v != nil {
		_c.SetBalance(*v)
	}
	return _c
}

// SetSettlementRequiredBefore sets the "settlement_required_before" field.
func (_c *PatientAccountCreate) SetSettlementRequiredBefore(v patientaccount.SettlementRequiredBefore) *PatientAccountCreate {
	_c.mutation.SetSettlementRequiredBefore(v)
	return _c
}

// SetNillableSettlementRequiredBefore sets the "settlement_required_before" field if the given value is not nil.
func (_c *PatientAccountCreate) SetNillableSettlementRequiredBefore(v *patientaccount.SettlementRequiredBefore) *PatientAccountCreate {
	if v != nil {
		_c.SetSettlementRequiredBefore(*v)
	}
	return _c
}

// SetNextOfKinID sets the "next_of_kin_id" field.
func (_c *PatientAccountCreate) SetNextOfKinID(v uuid.UUID) *PatientAccountCreate {
	_c.mutation.SetNextOfKinID(v)
	return _c
}

// SetNillableNextOfKinID sets the "next_of_kin_id" field if the given value is not nil.
func (_c *PatientAccountCreate) SetNillableNextOfKinID(v *uuid.UUID) *PatientAccountCreate {
	if v != nil {
		_c.SetNextOfKinID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PatientAccountCreate) SetCreatedAt(v time.Time) *PatientAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PatientAccountCreate) SetNillableCreatedAt(v *time.Time) *PatientAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PatientAccountCreate) SetUpdatedAt(v time.Time) *PatientAccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PatientAccountCreate) SetNillableUpdatedAt(v *time.Time) *PatientAccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PatientAccountCreate) SetID(v uuid.UUID) *PatientAccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PatientAccountCreate) SetNillableID(v *uuid.UUID) *PatientAccountCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddChargeIDs adds the "charges" edge to the BillableCharge entity by IDs.
func (_c *PatientAccountCreate) AddChargeIDs(ids ...uuid.UUID) *PatientAccountCreate {
	_c.mutation.AddChargeIDs(ids...)
	return _c
}

// AddCharges adds the "charges" edges to the BillableCharge entity.
func (_c *PatientAccountCreate) AddCharges(v ...*BillableCharge) *PatientAccountCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChargeIDs(ids...)
}

// Mutation returns the PatientAccountMutation object of the builder.
func (_c *PatientAccountCreate) Mutation() *PatientAccountMutation {
	return _c.mutation
}

// Save creates the PatientAccount in the database.
func (_c *PatientAccountCreate) Save(ctx context.Context) (*PatientAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PatientAccountCreate) SaveX(ctx context.Context) *PatientAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PatientAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PatientAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PatientAccountCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := patientaccount.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TotalCharged(); !ok {
		v := patientaccount.DefaultTotalCharged
		_c.mutation.SetTotalCharged(v)
	}
	if _, ok := _c.mutation.TotalPaid(); !ok {
		v := patientaccount.DefaultTotalPaid
		_c.mutation.SetTotalPaid(v)
	}
	if _, ok := _c.mutation.Balance(); !ok {
		v := patientaccount.DefaultBalance
		_c.mutation.SetBalance(v)
	}
	if _, ok := _c.mutation.SettlementRequiredBefore(); !ok {
		v := patientaccount.DefaultSettlementRequiredBefore
		_c.mutation.SetSettlementRequiredBefore(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := patientaccount.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := patientaccount.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := patientaccount.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PatientAccountCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "PatientAccount.tenant_id"`)}
	}
	if _, ok := _c.mutation.PatientID(); !ok {
		return &ValidationError{Name: "patient_id", err: errors.New(`ent: missing required field "PatientAccount.patient_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PatientAccount.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := patientaccount.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PatientAccount.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalCharged(); !ok {
		return &ValidationError{Name: "total_charged", err: errors.New(`ent: missing required field "PatientAccount.total_charged"`)}
	}
	if _, ok := _c.mutation.TotalPaid(); !ok {
		return &ValidationError{Name: "total_paid", err: errors.New(`ent: missing required field "PatientAccount.total_paid"`)}
	}
	if _, ok := _c.mutation.Balance(); !ok {
		return &ValidationError{Name: "balance", err: errors.New(`ent: missing required field "PatientAccount.balance"`)}
	}
	if _, ok := _c.mutation.SettlementRequiredBefore(); !ok {
		return &ValidationError{Name: "settlement_required_before", err: errors.New(`ent: missing required field "PatientAccount.settlement_required_before"`)}
	}
	if v, ok := _c.mutation.SettlementRequiredBefore(); ok {
		if err := patientaccount.SettlementRequiredBeforeValidator(v); err != nil {
			return &ValidationError{Name: "settlement_required_before", err: fmt.Errorf(`ent: validator failed for field "PatientAccount.settlement_required_before": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PatientAccount.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PatientAccount.updated_at"`)}
	}
	return nil
}

func (_c *PatientAccountCreate) sqlSave(ctx context.Context) (*PatientAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PatientAccountCreate) createSpec() (*PatientAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &PatientAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(patientaccount.Table, sqlgraph.NewFieldSpec(patientaccount.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(patientaccount.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.PatientID(); ok {
		_spec.SetField(patientaccount.FieldPatientID, field.TypeUUID, value)
		_node.PatientID = value
	}
	if value, ok := _c.mutation.VisitID(); ok {
		_spec.SetField(patientaccount.FieldVisitID, field.TypeUUID, value)
		_node.VisitID = &value
	}
	if value, ok := _c.mutation.AdmissionID(); ok {
		_spec.SetField(patientaccount.FieldAdmissionID, field.TypeUUID, value)
		_node.AdmissionID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(patientaccount.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TotalCharged(); ok {
		_spec.SetField(patientaccount.FieldTotalCharged, field.TypeFloat64, value)
		_node.TotalCharged = value
	}
	if value, ok := _c.mutation.TotalPaid(); ok {
		_spec.SetField(patientaccount.FieldTotalPaid, field.TypeFloat64, value)
		_node.TotalPaid = value
	}
	if value, ok := _c.mutation.Balance(); ok {
		_spec.SetField(patientaccount.FieldBalance, field.TypeFloat64, value)
		_node.Balance = value
	}
	if value, ok := _c.mutation.SettlementRequiredBefore(); ok {
		_spec.SetField(patientaccount.FieldSettlementRequiredBefore, field.TypeEnum, value)
		_node.SettlementRequiredBefore = value
	}
	if value, ok := _c.mutation.NextOfKinID(); ok {
		_spec.SetField(patientaccount.FieldNextOfKinID, field.TypeUUID, value)
		_node.NextOfKinID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(patientaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(patientaccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ChargesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   patientaccount.ChargesTable,
			Columns: []string{patientaccount.ChargesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(billablecharge.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PatientAccount.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PatientAccountUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *PatientAccountCreate) OnConflict(opts ...sql.ConflictOption) *PatientAccountUpsertOne {
	_c.conflict = opts
	return &PatientAccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PatientAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PatientAccountCreate) OnConflictColumns(columns ...string) *PatientAccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PatientAccountUpsertOne{
		create: _c,
	}
}

type (
	// PatientAccountUpsertOne is the builder for "upsert"-ing
	//  one PatientAccount node.
	PatientAccountUpsertOne struct {
		create *PatientAccountCreate
	}

	// PatientAccountUpsert is the "OnConflict" setter.
	PatientAccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *PatientAccountUpsert) SetTenantID(v uuid.UUID) *PatientAccountUpsert {
	u.Set(patientaccount.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *PatientAccountUpsert) UpdateTenantID() *PatientAccountUpsert {
	u.SetExcluded(patientaccount.FieldTenantID)
	return u
}

// SetPatientID sets the "patient_id" field.
func (u *PatientAccountUpsert) SetPatientID(v uuid.UUID) *PatientAccountUpsert {
	u.Set(patientaccount.FieldPatientID, v)
	return u
}

// UpdatePatientID sets the "patient_id" field to the value that was provided on create.
func (u *PatientAccountUpsert) UpdatePatientID() *PatientAccountUpsert {
	u.SetExcluded(patientaccount.FieldPatientID)
	return u
}

// SetVisitID sets the "visit_id" field.
func (u *PatientAccountUpsert) SetVisitID(v uuid.UUID) *PatientAccountUpsert {
	u.Set(patientaccount.FieldVisitID, v)
	return u
}

// UpdateVisitID sets the "visit_id" field to the value that was provided on create.
func (u *PatientAccountUpsert) UpdateVisitID() *PatientAccountUpsert {
	u.SetExcluded(patientaccount.FieldVisitID)
	return u
}

// ClearVisitID clears the value of the "visit_id" field.
func (u *PatientAccountUpsert) ClearVisitID() *PatientAccountUpsert {
	u.SetNull(patientaccount.FieldVisitID)
	return u
}

// SetAdmissionID sets the "admission_id" field.
func (u *PatientAccountUpsert) SetAdmissionID(v uuid.UUID) *PatientAccountUpsert {
	u.Set(patientaccount.FieldAdmissionID, v)
	return u
}

// UpdateAdmissionID sets the "admission_id" field to the value that was provided on create.
func (u *PatientAccountUpsert) UpdateAdmissionID() *PatientAccountUpsert {
	u.SetExcluded(patientaccount.FieldAdmissionID)
	return u
}

// ClearAdmissionID clears the value of the "admission_id" field.
func (u *PatientAccountUpsert) ClearAdmissionID() *PatientAccountUpsert {
	u.SetNull(patientaccount.FieldAdmissionID)
	return u
}

// SetStatus sets the "status" field.
func (u *PatientAccountUpsert) SetStatus(v patientaccount.Status) *PatientAccountUpsert {
	u.Set(patientaccount.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PatientAccountUpsert) UpdateStatus() *PatientAccountUpsert {
	u.SetExcluded(patientaccount.FieldStatus)
	return u
}

// SetTotalCharged sets the "total_charged" field.
func (u *PatientAccountUpsert) SetTotalCharged(v float64) *PatientAccountUpsert {
	u.Set(patientaccount.FieldTotalCharged, v)
	return u
}

// UpdateTotalCharged sets the "total_charged" field to the value that was provided on create.
func (u *PatientAccountUpsert) UpdateTotalCharged() *PatientAccountUpsert {
	u.SetExcluded(patientaccount.FieldTotalCharged)
	return u
}

// AddTotalCharged adds v to the "total_charged" field.
func (u *PatientAccountUpsert) AddTotalCharged(v float64) *PatientAccountUpsert {
	u.Add(patientaccount.FieldTotalCharged, v)
	return u
}

// SetTotalPaid sets the "total_paid" field.
func (u *PatientAccountUpsert) SetTotalPaid(v float64) *PatientAccountUpsert {
	u.Set(patientaccount.FieldTotalPaid, v)
	return u
}

// UpdateTotalPaid sets the "total_paid" field to the value that was provided on create.
func (u *PatientAccountUpsert) UpdateTotalPaid() *PatientAccountUpsert {
	u.SetExcluded(patientaccount.FieldTotalPaid)
	return u
}

// AddTotalPaid adds v to the "total_paid" field.
func (u *PatientAccountUpsert) AddTotalPaid(v float64) *PatientAccountUpsert {
	u.Add(patientaccount.FieldTotalPaid, v)
	return u
}

// SetBalance sets the "balance" field.
func (u *PatientAccountUpsert) SetBalance(v float64) *PatientAccountUpsert {
	u.Set(patientaccount.FieldBalance, v)
	return u
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *PatientAccountUpsert) UpdateBalance() *PatientAccountUpsert {
	u.SetExcluded(patientaccount.FieldBalance)
	return u
}

// AddBalance adds v to the "balance" field.
func (u *PatientAccountUpsert) AddBalance(v float64) *PatientAccountUpsert {
	u.Add(patientaccount.FieldBalance, v)
	return u
}

// SetSettlementRequiredBefore sets the "settlement_required_before" field.
func (u *PatientAccountUpsert) SetSettlementRequiredBefore(v patientaccount.SettlementRequiredBefore) *PatientAccountUpsert {
	u.Set(patientaccount.FieldSettlementRequiredBefore, v)
	return u
}

// UpdateSettlementRequiredBefore sets the "settlement_required_before" field to the value that was provided on create.
func (u *PatientAccountUpsert) UpdateSettlementRequiredBefore() *PatientAccountUpsert {
	u.SetExcluded(patientaccount.FieldSettlementRequiredBefore)
	return u
}

// SetNextOfKinID sets the "next_of_kin_id" field.
func (u *PatientAccountUpsert) SetNextOfKinID(v uuid.UUID) *PatientAccountUpsert {
	u.Set(patientaccount.FieldNextOfKinID, v)
	return u
}

// UpdateNextOfKinID sets the "next_of_kin_id" field to the value that was provided on create.
func (u *PatientAccountUpsert) UpdateNextOfKinID() *PatientAccountUpsert {
	u.SetExcluded(patientaccount.FieldNextOfKinID)
	return u
}

// ClearNextOfKinID clears the value of the "next_of_kin_id" field.
func (u *PatientAccountUpsert) ClearNextOfKinID() *PatientAccountUpsert {
	u.SetNull(patientaccount.FieldNextOfKinID)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PatientAccountUpsert) SetUpdatedAt(v time.Time) *PatientAccountUpsert {
	u.Set(patientaccount.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PatientAccountUpsert) UpdateUpdatedAt() *PatientAccountUpsert {
	u.SetExcluded(patientaccount.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PatientAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(patientaccount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PatientAccountUpsertOne) UpdateNewValues() *PatientAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(patientaccount.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(patientaccount.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PatientAccount.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PatientAccountUpsertOne) Ignore() *PatientAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PatientAccountUpsertOne) DoNothing() *PatientAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PatientAccountCreate.OnConflict
// documentation for more info.
func (u *PatientAccountUpsertOne) Update(set func(*PatientAccountUpsert)) *PatientAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PatientAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *PatientAccountUpsertOne) SetTenantID(v uuid.UUID) *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *PatientAccountUpsertOne) UpdateTenantID() *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateTenantID()
	})
}

// SetPatientID sets the "patient_id" field.
func (u *PatientAccountUpsertOne) SetPatientID(v uuid.UUID) *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetPatientID(v)
	})
}

// UpdatePatientID sets the "patient_id" field to the value that was provided on create.
func (u *PatientAccountUpsertOne) UpdatePatientID() *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdatePatientID()
	})
}

// SetVisitID sets the "visit_id" field.
func (u *PatientAccountUpsertOne) SetVisitID(v uuid.UUID) *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetVisitID(v)
	})
}

// UpdateVisitID sets the "visit_id" field to the value that was provided on create.
func (u *PatientAccountUpsertOne) UpdateVisitID() *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateVisitID()
	})
}

// ClearVisitID clears the value of the "visit_id" field.
func (u *PatientAccountUpsertOne) ClearVisitID() *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.ClearVisitID()
	})
}

// SetAdmissionID sets the "admission_id" field.
func (u *PatientAccountUpsertOne) SetAdmissionID(v uuid.UUID) *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetAdmissionID(v)
	})
}

// UpdateAdmissionID sets the "admission_id" field to the value that was provided on create.
func (u *PatientAccountUpsertOne) UpdateAdmissionID() *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateAdmissionID()
	})
}

// ClearAdmissionID clears the value of the "admission_id" field.
func (u *PatientAccountUpsertOne) ClearAdmissionID() *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.ClearAdmissionID()
	})
}

// SetStatus sets the "status" field.
func (u *PatientAccountUpsertOne) SetStatus(v patientaccount.Status) *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PatientAccountUpsertOne) UpdateStatus() *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateStatus()
	})
}

// SetTotalCharged sets the "total_charged" field.
func (u *PatientAccountUpsertOne) SetTotalCharged(v float64) *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetTotalCharged(v)
	})
}

// AddTotalCharged adds v to the "total_charged" field.
func (u *PatientAccountUpsertOne) AddTotalCharged(v float64) *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.AddTotalCharged(v)
	})
}

// UpdateTotalCharged sets the "total_charged" field to the value that was provided on create.
func (u *PatientAccountUpsertOne) UpdateTotalCharged() *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateTotalCharged()
	})
}

// SetTotalPaid sets the "total_paid" field.
func (u *PatientAccountUpsertOne) SetTotalPaid(v float64) *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetTotalPaid(v)
	})
}

// AddTotalPaid adds v to the "total_paid" field.
func (u *PatientAccountUpsertOne) AddTotalPaid(v float64) *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.AddTotalPaid(v)
	})
}

// UpdateTotalPaid sets the "total_paid" field to the value that was provided on create.
func (u *PatientAccountUpsertOne) UpdateTotalPaid() *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateTotalPaid()
	})
}

// SetBalance sets the "balance" field.
func (u *PatientAccountUpsertOne) SetBalance(v float64) *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *PatientAccountUpsertOne) AddBalance(v float64) *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *PatientAccountUpsertOne) UpdateBalance() *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateBalance()
	})
}

// SetSettlementRequiredBefore sets the "settlement_required_before" field.
func (u *PatientAccountUpsertOne) SetSettlementRequiredBefore(v patientaccount.SettlementRequiredBefore) *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetSettlementRequiredBefore(v)
	})
}

// UpdateSettlementRequiredBefore sets the "settlement_required_before" field to the value that was provided on create.
func (u *PatientAccountUpsertOne) UpdateSettlementRequiredBefore() *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateSettlementRequiredBefore()
	})
}

// SetNextOfKinID sets the "next_of_kin_id" field.
func (u *PatientAccountUpsertOne) SetNextOfKinID(v uuid.UUID) *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetNextOfKinID(v)
	})
}

// UpdateNextOfKinID sets the "next_of_kin_id" field to the value that was provided on create.
func (u *PatientAccountUpsertOne) UpdateNextOfKinID() *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateNextOfKinID()
	})
}

// ClearNextOfKinID clears the value of the "next_of_kin_id" field.
func (u *PatientAccountUpsertOne) ClearNextOfKinID() *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.ClearNextOfKinID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PatientAccountUpsertOne) SetUpdatedAt(v time.Time) *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PatientAccountUpsertOne) UpdateUpdatedAt() *PatientAccountUpsertOne {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PatientAccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PatientAccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PatientAccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PatientAccountUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PatientAccountUpsertOne.ID is not supported by MySQL driver. Use PatientAccountUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PatientAccountUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PatientAccountCreateBulk is the builder for creating many PatientAccount entities in bulk.
type PatientAccountCreateBulk struct {
	config
	err      error
	builders []*PatientAccountCreate
	conflict []sql.ConflictOption
}

// Save creates the PatientAccount entities in the database.
func (_c *PatientAccountCreateBulk) Save(ctx context.Context) ([]*PatientAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PatientAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PatientAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PatientAccountCreateBulk) SaveX(ctx context.Context) []*PatientAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PatientAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PatientAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PatientAccount.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PatientAccountUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *PatientAccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *PatientAccountUpsertBulk {
	_c.conflict = opts
	return &PatientAccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PatientAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PatientAccountCreateBulk) OnConflictColumns(columns ...string) *PatientAccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PatientAccountUpsertBulk{
		create: _c,
	}
}

// PatientAccountUpsertBulk is the builder for "upsert"-ing
// a bulk of PatientAccount nodes.
type PatientAccountUpsertBulk struct {
	create *PatientAccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PatientAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(patientaccount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PatientAccountUpsertBulk) UpdateNewValues() *PatientAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(patientaccount.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(patientaccount.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PatientAccount.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PatientAccountUpsertBulk) Ignore() *PatientAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PatientAccountUpsertBulk) DoNothing() *PatientAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PatientAccountCreateBulk.OnConflict
// documentation for more info.
func (u *PatientAccountUpsertBulk) Update(set func(*PatientAccountUpsert)) *PatientAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PatientAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *PatientAccountUpsertBulk) SetTenantID(v uuid.UUID) *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *PatientAccountUpsertBulk) UpdateTenantID() *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateTenantID()
	})
}

// SetPatientID sets the "patient_id" field.
func (u *PatientAccountUpsertBulk) SetPatientID(v uuid.UUID) *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetPatientID(v)
	})
}

// UpdatePatientID sets the "patient_id" field to the value that was provided on create.
func (u *PatientAccountUpsertBulk) UpdatePatientID() *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdatePatientID()
	})
}

// SetVisitID sets the "visit_id" field.
func (u *PatientAccountUpsertBulk) SetVisitID(v uuid.UUID) *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetVisitID(v)
	})
}

// UpdateVisitID sets the "visit_id" field to the value that was provided on create.
func (u *PatientAccountUpsertBulk) UpdateVisitID() *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateVisitID()
	})
}

// ClearVisitID clears the value of the "visit_id" field.
func (u *PatientAccountUpsertBulk) ClearVisitID() *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.ClearVisitID()
	})
}

// SetAdmissionID sets the "admission_id" field.
func (u *PatientAccountUpsertBulk) SetAdmissionID(v uuid.UUID) *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetAdmissionID(v)
	})
}

// UpdateAdmissionID sets the "admission_id" field to the value that was provided on create.
func (u *PatientAccountUpsertBulk) UpdateAdmissionID() *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateAdmissionID()
	})
}

// ClearAdmissionID clears the value of the "admission_id" field.
func (u *PatientAccountUpsertBulk) ClearAdmissionID() *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.ClearAdmissionID()
	})
}

// SetStatus sets the "status" field.
func (u *PatientAccountUpsertBulk) SetStatus(v patientaccount.Status) *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PatientAccountUpsertBulk) UpdateStatus() *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateStatus()
	})
}

// SetTotalCharged sets the "total_charged" field.
func (u *PatientAccountUpsertBulk) SetTotalCharged(v float64) *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetTotalCharged(v)
	})
}

// AddTotalCharged adds v to the "total_charged" field.
func (u *PatientAccountUpsertBulk) AddTotalCharged(v float64) *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.AddTotalCharged(v)
	})
}

// UpdateTotalCharged sets the "total_charged" field to the value that was provided on create.
func (u *PatientAccountUpsertBulk) UpdateTotalCharged() *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateTotalCharged()
	})
}

// SetTotalPaid sets the "total_paid" field.
func (u *PatientAccountUpsertBulk) SetTotalPaid(v float64) *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetTotalPaid(v)
	})
}

// AddTotalPaid adds v to the "total_paid" field.
func (u *PatientAccountUpsertBulk) AddTotalPaid(v float64) *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.AddTotalPaid(v)
	})
}

// UpdateTotalPaid sets the "total_paid" field to the value that was provided on create.
func (u *PatientAccountUpsertBulk) UpdateTotalPaid() *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateTotalPaid()
	})
}

// SetBalance sets the "balance" field.
func (u *PatientAccountUpsertBulk) SetBalance(v float64) *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *PatientAccountUpsertBulk) AddBalance(v float64) *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *PatientAccountUpsertBulk) UpdateBalance() *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateBalance()
	})
}

// SetSettlementRequiredBefore sets the "settlement_required_before" field.
func (u *PatientAccountUpsertBulk) SetSettlementRequiredBefore(v patientaccount.SettlementRequiredBefore) *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetSettlementRequiredBefore(v)
	})
}

// UpdateSettlementRequiredBefore sets the "settlement_required_before" field to the value that was provided on create.
func (u *PatientAccountUpsertBulk) UpdateSettlementRequiredBefore() *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateSettlementRequiredBefore()
	})
}

// SetNextOfKinID sets the "next_of_kin_id" field.
func (u *PatientAccountUpsertBulk) SetNextOfKinID(v uuid.UUID) *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetNextOfKinID(v)
	})
}

// UpdateNextOfKinID sets the "next_of_kin_id" field to the value that was provided on create.
func (u *PatientAccountUpsertBulk) UpdateNextOfKinID() *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateNextOfKinID()
	})
}

// ClearNextOfKinID clears the value of the "next_of_kin_id" field.
func (u *PatientAccountUpsertBulk) ClearNextOfKinID() *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.ClearNextOfKinID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PatientAccountUpsertBulk) SetUpdatedAt(v time.Time) *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PatientAccountUpsertBulk) UpdateUpdatedAt() *PatientAccountUpsertBulk {
	return u.Update(func(s *PatientAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PatientAccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PatientAccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PatientAccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PatientAccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
