// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/hospital-service/internal/ent/predicate"
	"github.com/bengobox/hospital-service/internal/ent/theatrebooking"
	"github.com/google/uuid"
)

// TheatreBookingUpdate is the builder for updating TheatreBooking entities.
type TheatreBookingUpdate struct {
	config
	hooks    []Hook
	mutation *TheatreBookingMutation
}

// Where appends a list predicates to the TheatreBookingUpdate builder.
func (_u *TheatreBookingUpdate) Where(ps ...predicate.TheatreBooking) *TheatreBookingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *TheatreBookingUpdate) SetTenantID(v uuid.UUID) *TheatreBookingUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TheatreBookingUpdate) SetNillableTenantID(v *uuid.UUID) *TheatreBookingUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetOutletID sets the "outlet_id" field.
func (_u *TheatreBookingUpdate) SetOutletID(v uuid.UUID) *TheatreBookingUpdate {
	_u.mutation.SetOutletID(v)
	return _u
}

// SetNillableOutletID sets the "outlet_id" field if the given value is not nil.
func (_u *TheatreBookingUpdate) SetNillableOutletID(v *uuid.UUID) *TheatreBookingUpdate {
	if v != nil {
		_u.SetOutletID(*v)
	}
	return _u
}

// SetPatientVisitID sets the "patient_visit_id" field.
func (_u *TheatreBookingUpdate) SetPatientVisitID(v uuid.UUID) *TheatreBookingUpdate {
	_u.mutation.SetPatientVisitID(v)
	return _u
}

// SetNillablePatientVisitID sets the "patient_visit_id" field if the given value is not nil.
func (_u *TheatreBookingUpdate) SetNillablePatientVisitID(v *uuid.UUID) *TheatreBookingUpdate {
	if v != nil {
		_u.SetPatientVisitID(*v)
	}
	return _u
}

// SetPatientID sets the "patient_id" field.
func (_u *TheatreBookingUpdate) SetPatientID(v uuid.UUID) *TheatreBookingUpdate {
	_u.mutation.SetPatientID(v)
	return _u
}

// SetNillablePatientID sets the "patient_id" field if the given value is not nil.
func (_u *TheatreBookingUpdate) SetNillablePatientID(v *uuid.UUID) *TheatreBookingUpdate {
	if v != nil {
		_u.SetPatientID(*v)
	}
	return _u
}

// SetTheatreRoom sets the "theatre_room" field.
func (_u *TheatreBookingUpdate) SetTheatreRoom(v string) *TheatreBookingUpdate {
	_u.mutation.SetTheatreRoom(v)
	return _u
}

// SetNillableTheatreRoom sets the "theatre_room" field if the given value is not nil.
func (_u *TheatreBookingUpdate) SetNillableTheatreRoom(v *string) *TheatreBookingUpdate {
	if v != nil {
		_u.SetTheatreRoom(*v)
	}
	return _u
}

// SetSurgeryType sets the "surgery_type" field.
func (_u *TheatreBookingUpdate) SetSurgeryType(v string) *TheatreBookingUpdate {
	_u.mutation.SetSurgeryType(v)
	return _u
}

// SetNillableSurgeryType sets the "surgery_type" field if the given value is not nil.
func (_u *TheatreBookingUpdate) SetNillableSurgeryType(v *string) *TheatreBookingUpdate {
	if v != nil {
		_u.SetSurgeryType(*v)
	}
	return _u
}

// SetSurgeonID sets the "surgeon_id" field.
func (_u *TheatreBookingUpdate) SetSurgeonID(v uuid.UUID) *TheatreBookingUpdate {
	_u.mutation.SetSurgeonID(v)
	return _u
}

// SetNillableSurgeonID sets the "surgeon_id" field if the given value is not nil.
func (_u *TheatreBookingUpdate) SetNillableSurgeonID(v *uuid.UUID) *TheatreBookingUpdate {
	if v != nil {
		_u.SetSurgeonID(*v)
	}
	return _u
}

// ClearSurgeonID clears the value of the "surgeon_id" field.
func (_u *TheatreBookingUpdate) ClearSurgeonID() *TheatreBookingUpdate {
	_u.mutation.ClearSurgeonID()
	return _u
}

// SetScheduledAt sets the "scheduled_at" field.
func (_u *TheatreBookingUpdate) SetScheduledAt(v time.Time) *TheatreBookingUpdate {
	_u.mutation.SetScheduledAt(v)
	return _u
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_u *TheatreBookingUpdate) SetNillableScheduledAt(v *time.Time) *TheatreBookingUpdate {
	if v != nil {
		_u.SetScheduledAt(*v)
	}
	return _u
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_u *TheatreBookingUpdate) SetDurationMinutes(v int) *TheatreBookingUpdate {
	_u.mutation.ResetDurationMinutes()
	_u.mutation.SetDurationMinutes(v)
	return _u
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_u *TheatreBookingUpdate) SetNillableDurationMinutes(v *int) *TheatreBookingUpdate {
	if v != nil {
		_u.SetDurationMinutes(*v)
	}
	return _u
}

// AddDurationMinutes adds value to the "duration_minutes" field.
func (_u *TheatreBookingUpdate) AddDurationMinutes(v int) *TheatreBookingUpdate {
	_u.mutation.AddDurationMinutes(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TheatreBookingUpdate) SetStatus(v theatrebooking.Status) *TheatreBookingUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TheatreBookingUpdate) SetNillableStatus(v *theatrebooking.Status) *TheatreBookingUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetChecklist sets the "checklist" field.
func (_u *TheatreBookingUpdate) SetChecklist(v map[string]bool) *TheatreBookingUpdate {
	_u.mutation.SetChecklist(v)
	return _u
}

// ClearChecklist clears the value of the "checklist" field.
func (_u *TheatreBookingUpdate) ClearChecklist() *TheatreBookingUpdate {
	_u.mutation.ClearChecklist()
	return _u
}

// SetFeeAmount sets the "fee_amount" field.
func (_u *TheatreBookingUpdate) SetFeeAmount(v float64) *TheatreBookingUpdate {
	_u.mutation.ResetFeeAmount()
	_u.mutation.SetFeeAmount(v)
	return _u
}

// SetNillableFeeAmount sets the "fee_amount" field if the given value is not nil.
func (_u *TheatreBookingUpdate) SetNillableFeeAmount(v *float64) *TheatreBookingUpdate {
	if v != nil {
		_u.SetFeeAmount(*v)
	}
	return _u
}

// AddFeeAmount adds value to the "fee_amount" field.
func (_u *TheatreBookingUpdate) AddFeeAmount(v float64) *TheatreBookingUpdate {
	_u.mutation.AddFeeAmount(v)
	return _u
}

// ClearFeeAmount clears the value of the "fee_amount" field.
func (_u *TheatreBookingUpdate) ClearFeeAmount() *TheatreBookingUpdate {
	_u.mutation.ClearFeeAmount()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TheatreBookingUpdate) SetCreatedBy(v uuid.UUID) *TheatreBookingUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TheatreBookingUpdate) SetNillableCreatedBy(v *uuid.UUID) *TheatreBookingUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *TheatreBookingUpdate) ClearCreatedBy() *TheatreBookingUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *TheatreBookingUpdate) SetStartedAt(v time.Time) *TheatreBookingUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *TheatreBookingUpdate) SetNillableStartedAt(v *time.Time) *TheatreBookingUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *TheatreBookingUpdate) ClearStartedAt() *TheatreBookingUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *TheatreBookingUpdate) SetCompletedAt(v time.Time) *TheatreBookingUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *TheatreBookingUpdate) SetNillableCompletedAt(v *time.Time) *TheatreBookingUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *TheatreBookingUpdate) ClearCompletedAt() *TheatreBookingUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TheatreBookingUpdate) SetUpdatedAt(v time.Time) *TheatreBookingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TheatreBookingMutation object of the builder.
func (_u *TheatreBookingUpdate) Mutation() *TheatreBookingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TheatreBookingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TheatreBookingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TheatreBookingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TheatreBookingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TheatreBookingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := theatrebooking.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TheatreBookingUpdate) check() error {
	if v, ok := _u.mutation.TheatreRoom(); ok {
		if err := theatrebooking.TheatreRoomValidator(v); err != nil {
			return &ValidationError{Name: "theatre_room", err: fmt.Errorf(`ent: validator failed for field "TheatreBooking.theatre_room": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SurgeryType(); ok {
		if err := theatrebooking.SurgeryTypeValidator(v); err != nil {
			return &ValidationError{Name: "surgery_type", err: fmt.Errorf(`ent: validator failed for field "TheatreBooking.surgery_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := theatrebooking.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TheatreBooking.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TheatreBookingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(theatrebooking.Table, theatrebooking.Columns, sqlgraph.NewFieldSpec(theatrebooking.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(theatrebooking.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.OutletID(); ok {
		_spec.SetField(theatrebooking.FieldOutletID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.PatientVisitID(); ok {
		_spec.SetField(theatrebooking.FieldPatientVisitID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.PatientID(); ok {
		_spec.SetField(theatrebooking.FieldPatientID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.TheatreRoom(); ok {
		_spec.SetField(theatrebooking.FieldTheatreRoom, field.TypeString, value)
	}
	if value, ok := _u.mutation.SurgeryType(); ok {
		_spec.SetField(theatrebooking.FieldSurgeryType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SurgeonID(); ok {
		_spec.SetField(theatrebooking.FieldSurgeonID, field.TypeUUID, value)
	}
	if _u.mutation.SurgeonIDCleared() {
		_spec.ClearField(theatrebooking.FieldSurgeonID, field.TypeUUID)
	}
	if value, ok := _u.mutation.ScheduledAt(); ok {
		_spec.SetField(theatrebooking.FieldScheduledAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DurationMinutes(); ok {
		_spec.SetField(theatrebooking.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMinutes(); ok {
		_spec.AddField(theatrebooking.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(theatrebooking.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Checklist(); ok {
		_spec.SetField(theatrebooking.FieldChecklist, field.TypeJSON, value)
	}
	if _u.mutation.ChecklistCleared() {
		_spec.ClearField(theatrebooking.FieldChecklist, field.TypeJSON)
	}
	if value, ok := _u.mutation.FeeAmount(); ok {
		_spec.SetField(theatrebooking.FieldFeeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeeAmount(); ok {
		_spec.AddField(theatrebooking.FieldFeeAmount, field.TypeFloat64, value)
	}
	if _u.mutation.FeeAmountCleared() {
		_spec.ClearField(theatrebooking.FieldFeeAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(theatrebooking.FieldCreatedBy, field.TypeUUID, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(theatrebooking.FieldCreatedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(theatrebooking.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(theatrebooking.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(theatrebooking.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(theatrebooking.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(theatrebooking.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{theatrebooking.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TheatreBookingUpdateOne is the builder for updating a single TheatreBooking entity.
type TheatreBookingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TheatreBookingMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *TheatreBookingUpdateOne) SetTenantID(v uuid.UUID) *TheatreBookingUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TheatreBookingUpdateOne) SetNillableTenantID(v *uuid.UUID) *TheatreBookingUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetOutletID sets the "outlet_id" field.
func (_u *TheatreBookingUpdateOne) SetOutletID(v uuid.UUID) *TheatreBookingUpdateOne {
	_u.mutation.SetOutletID(v)
	return _u
}

// SetNillableOutletID sets the "outlet_id" field if the given value is not nil.
func (_u *TheatreBookingUpdateOne) SetNillableOutletID(v *uuid.UUID) *TheatreBookingUpdateOne {
	if v != nil {
		_u.SetOutletID(*v)
	}
	return _u
}

// SetPatientVisitID sets the "patient_visit_id" field.
func (_u *TheatreBookingUpdateOne) SetPatientVisitID(v uuid.UUID) *TheatreBookingUpdateOne {
	_u.mutation.SetPatientVisitID(v)
	return _u
}

// SetNillablePatientVisitID sets the "patient_visit_id" field if the given value is not nil.
func (_u *TheatreBookingUpdateOne) SetNillablePatientVisitID(v *uuid.UUID) *TheatreBookingUpdateOne {
	if v != nil {
		_u.SetPatientVisitID(*v)
	}
	return _u
}

// SetPatientID sets the "patient_id" field.
func (_u *TheatreBookingUpdateOne) SetPatientID(v uuid.UUID) *TheatreBookingUpdateOne {
	_u.mutation.SetPatientID(v)
	return _u
}

// SetNillablePatientID sets the "patient_id" field if the given value is not nil.
func (_u *TheatreBookingUpdateOne) SetNillablePatientID(v *uuid.UUID) *TheatreBookingUpdateOne {
	if v != nil {
		_u.SetPatientID(*v)
	}
	return _u
}

// SetTheatreRoom sets the "theatre_room" field.
func (_u *TheatreBookingUpdateOne) SetTheatreRoom(v string) *TheatreBookingUpdateOne {
	_u.mutation.SetTheatreRoom(v)
	return _u
}

// SetNillableTheatreRoom sets the "theatre_room" field if the given value is not nil.
func (_u *TheatreBookingUpdateOne) SetNillableTheatreRoom(v *string) *TheatreBookingUpdateOne {
	if v != nil {
		_u.SetTheatreRoom(*v)
	}
	return _u
}

// SetSurgeryType sets the "surgery_type" field.
func (_u *TheatreBookingUpdateOne) SetSurgeryType(v string) *TheatreBookingUpdateOne {
	_u.mutation.SetSurgeryType(v)
	return _u
}

// SetNillableSurgeryType sets the "surgery_type" field if the given value is not nil.
func (_u *TheatreBookingUpdateOne) SetNillableSurgeryType(v *string) *TheatreBookingUpdateOne {
	if v != nil {
		_u.SetSurgeryType(*v)
	}
	return _u
}

// SetSurgeonID sets the "surgeon_id" field.
func (_u *TheatreBookingUpdateOne) SetSurgeonID(v uuid.UUID) *TheatreBookingUpdateOne {
	_u.mutation.SetSurgeonID(v)
	return _u
}

// SetNillableSurgeonID sets the "surgeon_id" field if the given value is not nil.
func (_u *TheatreBookingUpdateOne) SetNillableSurgeonID(v *uuid.UUID) *TheatreBookingUpdateOne {
	if v != nil {
		_u.SetSurgeonID(*v)
	}
	return _u
}

// ClearSurgeonID clears the value of the "surgeon_id" field.
func (_u *TheatreBookingUpdateOne) ClearSurgeonID() *TheatreBookingUpdateOne {
	_u.mutation.ClearSurgeonID()
	return _u
}

// SetScheduledAt sets the "scheduled_at" field.
func (_u *TheatreBookingUpdateOne) SetScheduledAt(v time.Time) *TheatreBookingUpdateOne {
	_u.mutation.SetScheduledAt(v)
	return _u
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_u *TheatreBookingUpdateOne) SetNillableScheduledAt(v *time.Time) *TheatreBookingUpdateOne {
	if v != nil {
		_u.SetScheduledAt(*v)
	}
	return _u
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_u *TheatreBookingUpdateOne) SetDurationMinutes(v int) *TheatreBookingUpdateOne {
	_u.mutation.ResetDurationMinutes()
	_u.mutation.SetDurationMinutes(v)
	return _u
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_u *TheatreBookingUpdateOne) SetNillableDurationMinutes(v *int) *TheatreBookingUpdateOne {
	if v != nil {
		_u.SetDurationMinutes(*v)
	}
	return _u
}

// AddDurationMinutes adds value to the "duration_minutes" field.
func (_u *TheatreBookingUpdateOne) AddDurationMinutes(v int) *TheatreBookingUpdateOne {
	_u.mutation.AddDurationMinutes(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TheatreBookingUpdateOne) SetStatus(v theatrebooking.Status) *TheatreBookingUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TheatreBookingUpdateOne) SetNillableStatus(v *theatrebooking.Status) *TheatreBookingUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetChecklist sets the "checklist" field.
func (_u *TheatreBookingUpdateOne) SetChecklist(v map[string]bool) *TheatreBookingUpdateOne {
	_u.mutation.SetChecklist(v)
	return _u
}

// ClearChecklist clears the value of the "checklist" field.
func (_u *TheatreBookingUpdateOne) ClearChecklist() *TheatreBookingUpdateOne {
	_u.mutation.ClearChecklist()
	return _u
}

// SetFeeAmount sets the "fee_amount" field.
func (_u *TheatreBookingUpdateOne) SetFeeAmount(v float64) *TheatreBookingUpdateOne {
	_u.mutation.ResetFeeAmount()
	_u.mutation.SetFeeAmount(v)
	return _u
}

// SetNillableFeeAmount sets the "fee_amount" field if the given value is not nil.
func (_u *TheatreBookingUpdateOne) SetNillableFeeAmount(v *float64) *TheatreBookingUpdateOne {
	if v != nil {
		_u.SetFeeAmount(*v)
	}
	return _u
}

// AddFeeAmount adds value to the "fee_amount" field.
func (_u *TheatreBookingUpdateOne) AddFeeAmount(v float64) *TheatreBookingUpdateOne {
	_u.mutation.AddFeeAmount(v)
	return _u
}

// ClearFeeAmount clears the value of the "fee_amount" field.
func (_u *TheatreBookingUpdateOne) ClearFeeAmount() *TheatreBookingUpdateOne {
	_u.mutation.ClearFeeAmount()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TheatreBookingUpdateOne) SetCreatedBy(v uuid.UUID) *TheatreBookingUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TheatreBookingUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *TheatreBookingUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *TheatreBookingUpdateOne) ClearCreatedBy() *TheatreBookingUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *TheatreBookingUpdateOne) SetStartedAt(v time.Time) *TheatreBookingUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *TheatreBookingUpdateOne) SetNillableStartedAt(v *time.Time) *TheatreBookingUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *TheatreBookingUpdateOne) ClearStartedAt() *TheatreBookingUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *TheatreBookingUpdateOne) SetCompletedAt(v time.Time) *TheatreBookingUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *TheatreBookingUpdateOne) SetNillableCompletedAt(v *time.Time) *TheatreBookingUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *TheatreBookingUpdateOne) ClearCompletedAt() *TheatreBookingUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TheatreBookingUpdateOne) SetUpdatedAt(v time.Time) *TheatreBookingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TheatreBookingMutation object of the builder.
func (_u *TheatreBookingUpdateOne) Mutation() *TheatreBookingMutation {
	return _u.mutation
}

// Where appends a list predicates to the TheatreBookingUpdate builder.
func (_u *TheatreBookingUpdateOne) Where(ps ...predicate.TheatreBooking) *TheatreBookingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TheatreBookingUpdateOne) Select(field string, fields ...string) *TheatreBookingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TheatreBooking entity.
func (_u *TheatreBookingUpdateOne) Save(ctx context.Context) (*TheatreBooking, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TheatreBookingUpdateOne) SaveX(ctx context.Context) *TheatreBooking {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TheatreBookingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TheatreBookingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TheatreBookingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := theatrebooking.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TheatreBookingUpdateOne) check() error {
	if v, ok := _u.mutation.TheatreRoom(); ok {
		if err := theatrebooking.TheatreRoomValidator(v); err != nil {
			return &ValidationError{Name: "theatre_room", err: fmt.Errorf(`ent: validator failed for field "TheatreBooking.theatre_room": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SurgeryType(); ok {
		if err := theatrebooking.SurgeryTypeValidator(v); err != nil {
			return &ValidationError{Name: "surgery_type", err: fmt.Errorf(`ent: validator failed for field "TheatreBooking.surgery_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := theatrebooking.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TheatreBooking.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TheatreBookingUpdateOne) sqlSave(ctx context.Context) (_node *TheatreBooking, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(theatrebooking.Table, theatrebooking.Columns, sqlgraph.NewFieldSpec(theatrebooking.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TheatreBooking.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, theatrebooking.FieldID)
		for _, f := range fields {
			if !theatrebooking.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != theatrebooking.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(theatrebooking.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.OutletID(); ok {
		_spec.SetField(theatrebooking.FieldOutletID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.PatientVisitID(); ok {
		_spec.SetField(theatrebooking.FieldPatientVisitID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.PatientID(); ok {
		_spec.SetField(theatrebooking.FieldPatientID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.TheatreRoom(); ok {
		_spec.SetField(theatrebooking.FieldTheatreRoom, field.TypeString, value)
	}
	if value, ok := _u.mutation.SurgeryType(); ok {
		_spec.SetField(theatrebooking.FieldSurgeryType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SurgeonID(); ok {
		_spec.SetField(theatrebooking.FieldSurgeonID, field.TypeUUID, value)
	}
	if _u.mutation.SurgeonIDCleared() {
		_spec.ClearField(theatrebooking.FieldSurgeonID, field.TypeUUID)
	}
	if value, ok := _u.mutation.ScheduledAt(); ok {
		_spec.SetField(theatrebooking.FieldScheduledAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DurationMinutes(); ok {
		_spec.SetField(theatrebooking.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMinutes(); ok {
		_spec.AddField(theatrebooking.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(theatrebooking.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Checklist(); ok {
		_spec.SetField(theatrebooking.FieldChecklist, field.TypeJSON, value)
	}
	if _u.mutation.ChecklistCleared() {
		_spec.ClearField(theatrebooking.FieldChecklist, field.TypeJSON)
	}
	if value, ok := _u.mutation.FeeAmount(); ok {
		_spec.SetField(theatrebooking.FieldFeeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeeAmount(); ok {
		_spec.AddField(theatrebooking.FieldFeeAmount, field.TypeFloat64, value)
	}
	if _u.mutation.FeeAmountCleared() {
		_spec.ClearField(theatrebooking.FieldFeeAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(theatrebooking.FieldCreatedBy, field.TypeUUID, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(theatrebooking.FieldCreatedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(theatrebooking.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(theatrebooking.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(theatrebooking.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(theatrebooking.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(theatrebooking.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &TheatreBooking{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{theatrebooking.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
