// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/hospital-service/internal/ent/predicate"
	"github.com/bengobox/hospital-service/internal/ent/wardroundnote"
)

// WardRoundNoteDelete is the builder for deleting a WardRoundNote entity.
type WardRoundNoteDelete struct {
	config
	hooks    []Hook
	mutation *WardRoundNoteMutation
}

// Where appends a list predicates to the WardRoundNoteDelete builder.
func (_d *WardRoundNoteDelete) Where(ps ...predicate.WardRoundNote) *WardRoundNoteDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *WardRoundNoteDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WardRoundNoteDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *WardRoundNoteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(wardroundnote.Table, sqlgraph.NewFieldSpec(wardroundnote.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// WardRoundNoteDeleteOne is the builder for deleting a single WardRoundNote entity.
type WardRoundNoteDeleteOne struct {
	_d *WardRoundNoteDelete
}

// Where appends a list predicates to the WardRoundNoteDelete builder.
func (_d *WardRoundNoteDeleteOne) Where(ps ...predicate.WardRoundNote) *WardRoundNoteDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *WardRoundNoteDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{wardroundnote.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WardRoundNoteDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
