// Code generated by ent, DO NOT EDIT.

package billableitemcatalog

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the billableitemcatalog type in the database.
	Label = "billable_item_catalog"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldDepartment holds the string denoting the department field in the database.
	FieldDepartment = "department"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldAppliesTo holds the string denoting the applies_to field in the database.
	FieldAppliesTo = "applies_to"
	// FieldRequiresPrepayment holds the string denoting the requires_prepayment field in the database.
	FieldRequiresPrepayment = "requires_prepayment"
	// FieldCollectionMode holds the string denoting the collection_mode field in the database.
	FieldCollectionMode = "collection_mode"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the billableitemcatalog in the database.
	Table = "billable_item_catalogs"
)

// Columns holds all SQL columns for billableitemcatalog fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldDepartment,
	FieldCode,
	FieldName,
	FieldPrice,
	FieldAppliesTo,
	FieldRequiresPrepayment,
	FieldCollectionMode,
	FieldIsActive,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultRequiresPrepayment holds the default value on creation for the "requires_prepayment" field.
	DefaultRequiresPrepayment bool
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Department defines the type for the "department" enum field.
type Department string

// Department values.
const (
	DepartmentRecords      Department = "records"
	DepartmentTriage       Department = "triage"
	DepartmentConsultation Department = "consultation"
	DepartmentLab          Department = "lab"
	DepartmentPharmacy     Department = "pharmacy"
	DepartmentTheatre      Department = "theatre"
	DepartmentInpatient    Department = "inpatient"
	DepartmentMortuary     Department = "mortuary"
)

func (d Department) String() string {
	return string(d)
}

// DepartmentValidator is a validator for the "department" field enum values. It is called by the builders before save.
func DepartmentValidator(d Department) error {
	switch d {
	case DepartmentRecords, DepartmentTriage, DepartmentConsultation, DepartmentLab, DepartmentPharmacy, DepartmentTheatre, DepartmentInpatient, DepartmentMortuary:
		return nil
	default:
		return fmt.Errorf("billableitemcatalog: invalid enum value for department field: %q", d)
	}
}

// AppliesTo defines the type for the "applies_to" enum field.
type AppliesTo string

// AppliesToAll is the default value of the AppliesTo enum.
const DefaultAppliesTo = AppliesToAll

// AppliesTo values.
const (
	AppliesToFirstVisit  AppliesTo = "first_visit"
	AppliesToReturnVisit AppliesTo = "return_visit"
	AppliesToAll         AppliesTo = "all"
)

func (at AppliesTo) String() string {
	return string(at)
}

// AppliesToValidator is a validator for the "applies_to" field enum values. It is called by the builders before save.
func AppliesToValidator(at AppliesTo) error {
	switch at {
	case AppliesToFirstVisit, AppliesToReturnVisit, AppliesToAll:
		return nil
	default:
		return fmt.Errorf("billableitemcatalog: invalid enum value for applies_to field: %q", at)
	}
}

// CollectionMode defines the type for the "collection_mode" enum field.
type CollectionMode string

// CollectionModeBillingQueue is the default value of the CollectionMode enum.
const DefaultCollectionMode = CollectionModeBillingQueue

// CollectionMode values.
const (
	CollectionModeDirect       CollectionMode = "direct"
	CollectionModeBillingQueue CollectionMode = "billing_queue"
	CollectionModeEither       CollectionMode = "either"
)

func (cm CollectionMode) String() string {
	return string(cm)
}

// CollectionModeValidator is a validator for the "collection_mode" field enum values. It is called by the builders before save.
func CollectionModeValidator(cm CollectionMode) error {
	switch cm {
	case CollectionModeDirect, CollectionModeBillingQueue, CollectionModeEither:
		return nil
	default:
		return fmt.Errorf("billableitemcatalog: invalid enum value for collection_mode field: %q", cm)
	}
}

// OrderOption defines the ordering options for the BillableItemCatalog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByDepartment orders the results by the department field.
func ByDepartment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepartment, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByAppliesTo orders the results by the applies_to field.
func ByAppliesTo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppliesTo, opts...).ToFunc()
}

// ByRequiresPrepayment orders the results by the requires_prepayment field.
func ByRequiresPrepayment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequiresPrepayment, opts...).ToFunc()
}

// ByCollectionMode orders the results by the collection_mode field.
func ByCollectionMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectionMode, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
