// Code generated by ent, DO NOT EDIT.

package ward

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the ward type in the database.
	Label = "ward"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldOutletID holds the string denoting the outlet_id field in the database.
	FieldOutletID = "outlet_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldWardType holds the string denoting the ward_type field in the database.
	FieldWardType = "ward_type"
	// FieldCapacity holds the string denoting the capacity field in the database.
	FieldCapacity = "capacity"
	// FieldBillableItemCode holds the string denoting the billable_item_code field in the database.
	FieldBillableItemCode = "billable_item_code"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeBeds holds the string denoting the beds edge name in mutations.
	EdgeBeds = "beds"
	// Table holds the table name of the ward in the database.
	Table = "wards"
	// BedsTable is the table that holds the beds relation/edge.
	BedsTable = "beds"
	// BedsInverseTable is the table name for the Bed entity.
	// It exists in this package in order to avoid circular dependency with the "bed" package.
	BedsInverseTable = "beds"
	// BedsColumn is the table column denoting the beds relation/edge.
	BedsColumn = "ward_id"
)

// Columns holds all SQL columns for ward fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldOutletID,
	FieldName,
	FieldWardType,
	FieldCapacity,
	FieldBillableItemCode,
	FieldIsActive,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCapacity holds the default value on creation for the "capacity" field.
	DefaultCapacity int
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// WardType defines the type for the "ward_type" enum field.
type WardType string

// WardType values.
const (
	WardTypeGeneral     WardType = "general"
	WardTypePrivate     WardType = "private"
	WardTypeSemiPrivate WardType = "semi_private"
	WardTypeIsolation   WardType = "isolation"
	WardTypeIcu         WardType = "icu"
)

func (wt WardType) String() string {
	return string(wt)
}

// WardTypeValidator is a validator for the "ward_type" field enum values. It is called by the builders before save.
func WardTypeValidator(wt WardType) error {
	switch wt {
	case WardTypeGeneral, WardTypePrivate, WardTypeSemiPrivate, WardTypeIsolation, WardTypeIcu:
		return nil
	default:
		return fmt.Errorf("ward: invalid enum value for ward_type field: %q", wt)
	}
}

// OrderOption defines the ordering options for the Ward queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByOutletID orders the results by the outlet_id field.
func ByOutletID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutletID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByWardType orders the results by the ward_type field.
func ByWardType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWardType, opts...).ToFunc()
}

// ByCapacity orders the results by the capacity field.
func ByCapacity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapacity, opts...).ToFunc()
}

// ByBillableItemCode orders the results by the billable_item_code field.
func ByBillableItemCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillableItemCode, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByBedsCount orders the results by beds count.
func ByBedsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBedsStep(), opts...)
	}
}

// ByBeds orders the results by beds terms.
func ByBeds(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBedsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newBedsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BedsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BedsTable, BedsColumn),
	)
}
