// Code generated by ent, DO NOT EDIT.

package ward

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/hospital-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldEQ(FieldTenantID, v))
}

// OutletID applies equality check predicate on the "outlet_id" field. It's identical to OutletIDEQ.
func OutletID(v uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldEQ(FieldOutletID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Ward {
	return predicate.Ward(sql.FieldEQ(FieldName, v))
}

// Capacity applies equality check predicate on the "capacity" field. It's identical to CapacityEQ.
func Capacity(v int) predicate.Ward {
	return predicate.Ward(sql.FieldEQ(FieldCapacity, v))
}

// BillableItemCode applies equality check predicate on the "billable_item_code" field. It's identical to BillableItemCodeEQ.
func BillableItemCode(v string) predicate.Ward {
	return predicate.Ward(sql.FieldEQ(FieldBillableItemCode, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Ward {
	return predicate.Ward(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Ward {
	return predicate.Ward(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Ward {
	return predicate.Ward(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldLTE(FieldTenantID, v))
}

// OutletIDEQ applies the EQ predicate on the "outlet_id" field.
func OutletIDEQ(v uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldEQ(FieldOutletID, v))
}

// OutletIDNEQ applies the NEQ predicate on the "outlet_id" field.
func OutletIDNEQ(v uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldNEQ(FieldOutletID, v))
}

// OutletIDIn applies the In predicate on the "outlet_id" field.
func OutletIDIn(vs ...uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldIn(FieldOutletID, vs...))
}

// OutletIDNotIn applies the NotIn predicate on the "outlet_id" field.
func OutletIDNotIn(vs ...uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldNotIn(FieldOutletID, vs...))
}

// OutletIDGT applies the GT predicate on the "outlet_id" field.
func OutletIDGT(v uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldGT(FieldOutletID, v))
}

// OutletIDGTE applies the GTE predicate on the "outlet_id" field.
func OutletIDGTE(v uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldGTE(FieldOutletID, v))
}

// OutletIDLT applies the LT predicate on the "outlet_id" field.
func OutletIDLT(v uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldLT(FieldOutletID, v))
}

// OutletIDLTE applies the LTE predicate on the "outlet_id" field.
func OutletIDLTE(v uuid.UUID) predicate.Ward {
	return predicate.Ward(sql.FieldLTE(FieldOutletID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Ward {
	return predicate.Ward(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Ward {
	return predicate.Ward(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Ward {
	return predicate.Ward(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Ward {
	return predicate.Ward(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Ward {
	return predicate.Ward(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Ward {
	return predicate.Ward(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Ward {
	return predicate.Ward(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Ward {
	return predicate.Ward(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Ward {
	return predicate.Ward(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Ward {
	return predicate.Ward(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Ward {
	return predicate.Ward(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Ward {
	return predicate.Ward(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Ward {
	return predicate.Ward(sql.FieldContainsFold(FieldName, v))
}

// WardTypeEQ applies the EQ predicate on the "ward_type" field.
func WardTypeEQ(v WardType) predicate.Ward {
	return predicate.Ward(sql.FieldEQ(FieldWardType, v))
}

// WardTypeNEQ applies the NEQ predicate on the "ward_type" field.
func WardTypeNEQ(v WardType) predicate.Ward {
	return predicate.Ward(sql.FieldNEQ(FieldWardType, v))
}

// WardTypeIn applies the In predicate on the "ward_type" field.
func WardTypeIn(vs ...WardType) predicate.Ward {
	return predicate.Ward(sql.FieldIn(FieldWardType, vs...))
}

// WardTypeNotIn applies the NotIn predicate on the "ward_type" field.
func WardTypeNotIn(vs ...WardType) predicate.Ward {
	return predicate.Ward(sql.FieldNotIn(FieldWardType, vs...))
}

// WardTypeIsNil applies the IsNil predicate on the "ward_type" field.
func WardTypeIsNil() predicate.Ward {
	return predicate.Ward(sql.FieldIsNull(FieldWardType))
}

// WardTypeNotNil applies the NotNil predicate on the "ward_type" field.
func WardTypeNotNil() predicate.Ward {
	return predicate.Ward(sql.FieldNotNull(FieldWardType))
}

// CapacityEQ applies the EQ predicate on the "capacity" field.
func CapacityEQ(v int) predicate.Ward {
	return predicate.Ward(sql.FieldEQ(FieldCapacity, v))
}

// CapacityNEQ applies the NEQ predicate on the "capacity" field.
func CapacityNEQ(v int) predicate.Ward {
	return predicate.Ward(sql.FieldNEQ(FieldCapacity, v))
}

// CapacityIn applies the In predicate on the "capacity" field.
func CapacityIn(vs ...int) predicate.Ward {
	return predicate.Ward(sql.FieldIn(FieldCapacity, vs...))
}

// CapacityNotIn applies the NotIn predicate on the "capacity" field.
func CapacityNotIn(vs ...int) predicate.Ward {
	return predicate.Ward(sql.FieldNotIn(FieldCapacity, vs...))
}

// CapacityGT applies the GT predicate on the "capacity" field.
func CapacityGT(v int) predicate.Ward {
	return predicate.Ward(sql.FieldGT(FieldCapacity, v))
}

// CapacityGTE applies the GTE predicate on the "capacity" field.
func CapacityGTE(v int) predicate.Ward {
	return predicate.Ward(sql.FieldGTE(FieldCapacity, v))
}

// CapacityLT applies the LT predicate on the "capacity" field.
func CapacityLT(v int) predicate.Ward {
	return predicate.Ward(sql.FieldLT(FieldCapacity, v))
}

// CapacityLTE applies the LTE predicate on the "capacity" field.
func CapacityLTE(v int) predicate.Ward {
	return predicate.Ward(sql.FieldLTE(FieldCapacity, v))
}

// BillableItemCodeEQ applies the EQ predicate on the "billable_item_code" field.
func BillableItemCodeEQ(v string) predicate.Ward {
	return predicate.Ward(sql.FieldEQ(FieldBillableItemCode, v))
}

// BillableItemCodeNEQ applies the NEQ predicate on the "billable_item_code" field.
func BillableItemCodeNEQ(v string) predicate.Ward {
	return predicate.Ward(sql.FieldNEQ(FieldBillableItemCode, v))
}

// BillableItemCodeIn applies the In predicate on the "billable_item_code" field.
func BillableItemCodeIn(vs ...string) predicate.Ward {
	return predicate.Ward(sql.FieldIn(FieldBillableItemCode, vs...))
}

// BillableItemCodeNotIn applies the NotIn predicate on the "billable_item_code" field.
func BillableItemCodeNotIn(vs ...string) predicate.Ward {
	return predicate.Ward(sql.FieldNotIn(FieldBillableItemCode, vs...))
}

// BillableItemCodeGT applies the GT predicate on the "billable_item_code" field.
func BillableItemCodeGT(v string) predicate.Ward {
	return predicate.Ward(sql.FieldGT(FieldBillableItemCode, v))
}

// BillableItemCodeGTE applies the GTE predicate on the "billable_item_code" field.
func BillableItemCodeGTE(v string) predicate.Ward {
	return predicate.Ward(sql.FieldGTE(FieldBillableItemCode, v))
}

// BillableItemCodeLT applies the LT predicate on the "billable_item_code" field.
func BillableItemCodeLT(v string) predicate.Ward {
	return predicate.Ward(sql.FieldLT(FieldBillableItemCode, v))
}

// BillableItemCodeLTE applies the LTE predicate on the "billable_item_code" field.
func BillableItemCodeLTE(v string) predicate.Ward {
	return predicate.Ward(sql.FieldLTE(FieldBillableItemCode, v))
}

// BillableItemCodeContains applies the Contains predicate on the "billable_item_code" field.
func BillableItemCodeContains(v string) predicate.Ward {
	return predicate.Ward(sql.FieldContains(FieldBillableItemCode, v))
}

// BillableItemCodeHasPrefix applies the HasPrefix predicate on the "billable_item_code" field.
func BillableItemCodeHasPrefix(v string) predicate.Ward {
	return predicate.Ward(sql.FieldHasPrefix(FieldBillableItemCode, v))
}

// BillableItemCodeHasSuffix applies the HasSuffix predicate on the "billable_item_code" field.
func BillableItemCodeHasSuffix(v string) predicate.Ward {
	return predicate.Ward(sql.FieldHasSuffix(FieldBillableItemCode, v))
}

// BillableItemCodeIsNil applies the IsNil predicate on the "billable_item_code" field.
func BillableItemCodeIsNil() predicate.Ward {
	return predicate.Ward(sql.FieldIsNull(FieldBillableItemCode))
}

// BillableItemCodeNotNil applies the NotNil predicate on the "billable_item_code" field.
func BillableItemCodeNotNil() predicate.Ward {
	return predicate.Ward(sql.FieldNotNull(FieldBillableItemCode))
}

// BillableItemCodeEqualFold applies the EqualFold predicate on the "billable_item_code" field.
func BillableItemCodeEqualFold(v string) predicate.Ward {
	return predicate.Ward(sql.FieldEqualFold(FieldBillableItemCode, v))
}

// BillableItemCodeContainsFold applies the ContainsFold predicate on the "billable_item_code" field.
func BillableItemCodeContainsFold(v string) predicate.Ward {
	return predicate.Ward(sql.FieldContainsFold(FieldBillableItemCode, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Ward {
	return predicate.Ward(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Ward {
	return predicate.Ward(sql.FieldNEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Ward {
	return predicate.Ward(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Ward {
	return predicate.Ward(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Ward {
	return predicate.Ward(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Ward {
	return predicate.Ward(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Ward {
	return predicate.Ward(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Ward {
	return predicate.Ward(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Ward {
	return predicate.Ward(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Ward {
	return predicate.Ward(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Ward {
	return predicate.Ward(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Ward {
	return predicate.Ward(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Ward {
	return predicate.Ward(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Ward {
	return predicate.Ward(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Ward {
	return predicate.Ward(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Ward {
	return predicate.Ward(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Ward {
	return predicate.Ward(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Ward {
	return predicate.Ward(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasBeds applies the HasEdge predicate on the "beds" edge.
func HasBeds() predicate.Ward {
	return predicate.Ward(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BedsTable, BedsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBedsWith applies the HasEdge predicate on the "beds" edge with a given conditions (other predicates).
func HasBedsWith(preds ...predicate.Bed) predicate.Ward {
	return predicate.Ward(func(s *sql.Selector) {
		step := newBedsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Ward) predicate.Ward {
	return predicate.Ward(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Ward) predicate.Ward {
	return predicate.Ward(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Ward) predicate.Ward {
	return predicate.Ward(sql.NotPredicates(p))
}
