// Code generated by ent, DO NOT EDIT.

package theatrestaffassignment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/hospital-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldEQ(FieldTenantID, v))
}

// TheatreBookingID applies equality check predicate on the "theatre_booking_id" field. It's identical to TheatreBookingIDEQ.
func TheatreBookingID(v uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldEQ(FieldTheatreBookingID, v))
}

// StaffUserID applies equality check predicate on the "staff_user_id" field. It's identical to StaffUserIDEQ.
func StaffUserID(v uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldEQ(FieldStaffUserID, v))
}

// AssignedAt applies equality check predicate on the "assigned_at" field. It's identical to AssignedAtEQ.
func AssignedAt(v time.Time) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldEQ(FieldAssignedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldLTE(FieldTenantID, v))
}

// TheatreBookingIDEQ applies the EQ predicate on the "theatre_booking_id" field.
func TheatreBookingIDEQ(v uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldEQ(FieldTheatreBookingID, v))
}

// TheatreBookingIDNEQ applies the NEQ predicate on the "theatre_booking_id" field.
func TheatreBookingIDNEQ(v uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldNEQ(FieldTheatreBookingID, v))
}

// TheatreBookingIDIn applies the In predicate on the "theatre_booking_id" field.
func TheatreBookingIDIn(vs ...uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldIn(FieldTheatreBookingID, vs...))
}

// TheatreBookingIDNotIn applies the NotIn predicate on the "theatre_booking_id" field.
func TheatreBookingIDNotIn(vs ...uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldNotIn(FieldTheatreBookingID, vs...))
}

// StaffUserIDEQ applies the EQ predicate on the "staff_user_id" field.
func StaffUserIDEQ(v uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldEQ(FieldStaffUserID, v))
}

// StaffUserIDNEQ applies the NEQ predicate on the "staff_user_id" field.
func StaffUserIDNEQ(v uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldNEQ(FieldStaffUserID, v))
}

// StaffUserIDIn applies the In predicate on the "staff_user_id" field.
func StaffUserIDIn(vs ...uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldIn(FieldStaffUserID, vs...))
}

// StaffUserIDNotIn applies the NotIn predicate on the "staff_user_id" field.
func StaffUserIDNotIn(vs ...uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldNotIn(FieldStaffUserID, vs...))
}

// StaffUserIDGT applies the GT predicate on the "staff_user_id" field.
func StaffUserIDGT(v uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldGT(FieldStaffUserID, v))
}

// StaffUserIDGTE applies the GTE predicate on the "staff_user_id" field.
func StaffUserIDGTE(v uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldGTE(FieldStaffUserID, v))
}

// StaffUserIDLT applies the LT predicate on the "staff_user_id" field.
func StaffUserIDLT(v uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldLT(FieldStaffUserID, v))
}

// StaffUserIDLTE applies the LTE predicate on the "staff_user_id" field.
func StaffUserIDLTE(v uuid.UUID) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldLTE(FieldStaffUserID, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v Role) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v Role) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...Role) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...Role) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldNotIn(FieldRole, vs...))
}

// AssignedAtEQ applies the EQ predicate on the "assigned_at" field.
func AssignedAtEQ(v time.Time) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldEQ(FieldAssignedAt, v))
}

// AssignedAtNEQ applies the NEQ predicate on the "assigned_at" field.
func AssignedAtNEQ(v time.Time) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldNEQ(FieldAssignedAt, v))
}

// AssignedAtIn applies the In predicate on the "assigned_at" field.
func AssignedAtIn(vs ...time.Time) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldIn(FieldAssignedAt, vs...))
}

// AssignedAtNotIn applies the NotIn predicate on the "assigned_at" field.
func AssignedAtNotIn(vs ...time.Time) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldNotIn(FieldAssignedAt, vs...))
}

// AssignedAtGT applies the GT predicate on the "assigned_at" field.
func AssignedAtGT(v time.Time) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldGT(FieldAssignedAt, v))
}

// AssignedAtGTE applies the GTE predicate on the "assigned_at" field.
func AssignedAtGTE(v time.Time) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldGTE(FieldAssignedAt, v))
}

// AssignedAtLT applies the LT predicate on the "assigned_at" field.
func AssignedAtLT(v time.Time) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldLT(FieldAssignedAt, v))
}

// AssignedAtLTE applies the LTE predicate on the "assigned_at" field.
func AssignedAtLTE(v time.Time) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.FieldLTE(FieldAssignedAt, v))
}

// HasTheatreBooking applies the HasEdge predicate on the "theatre_booking" edge.
func HasTheatreBooking() predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TheatreBookingTable, TheatreBookingColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTheatreBookingWith applies the HasEdge predicate on the "theatre_booking" edge with a given conditions (other predicates).
func HasTheatreBookingWith(preds ...predicate.TheatreBooking) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(func(s *sql.Selector) {
		step := newTheatreBookingStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TheatreStaffAssignment) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TheatreStaffAssignment) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TheatreStaffAssignment) predicate.TheatreStaffAssignment {
	return predicate.TheatreStaffAssignment(sql.NotPredicates(p))
}
