// Code generated by ent, DO NOT EDIT.

package operativenote

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/hospital-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldTenantID, v))
}

// TheatreBookingID applies equality check predicate on the "theatre_booking_id" field. It's identical to TheatreBookingIDEQ.
func TheatreBookingID(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldTheatreBookingID, v))
}

// SurgeonID applies equality check predicate on the "surgeon_id" field. It's identical to SurgeonIDEQ.
func SurgeonID(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldSurgeonID, v))
}

// ProcedurePerformed applies equality check predicate on the "procedure_performed" field. It's identical to ProcedurePerformedEQ.
func ProcedurePerformed(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldProcedurePerformed, v))
}

// Findings applies equality check predicate on the "findings" field. It's identical to FindingsEQ.
func Findings(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldFindings, v))
}

// Complications applies equality check predicate on the "complications" field. It's identical to ComplicationsEQ.
func Complications(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldComplications, v))
}

// EstimatedBloodLossMl applies equality check predicate on the "estimated_blood_loss_ml" field. It's identical to EstimatedBloodLossMlEQ.
func EstimatedBloodLossMl(v float64) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldEstimatedBloodLossMl, v))
}

// ImplantsUsed applies equality check predicate on the "implants_used" field. It's identical to ImplantsUsedEQ.
func ImplantsUsed(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldImplantsUsed, v))
}

// SpecimensSent applies equality check predicate on the "specimens_sent" field. It's identical to SpecimensSentEQ.
func SpecimensSent(v bool) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldSpecimensSent, v))
}

// SpecimensDescription applies equality check predicate on the "specimens_description" field. It's identical to SpecimensDescriptionEQ.
func SpecimensDescription(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldSpecimensDescription, v))
}

// PostOpDiagnosis applies equality check predicate on the "post_op_diagnosis" field. It's identical to PostOpDiagnosisEQ.
func PostOpDiagnosis(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldPostOpDiagnosis, v))
}

// AuthoredBy applies equality check predicate on the "authored_by" field. It's identical to AuthoredByEQ.
func AuthoredBy(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldAuthoredBy, v))
}

// AuthoredAt applies equality check predicate on the "authored_at" field. It's identical to AuthoredAtEQ.
func AuthoredAt(v time.Time) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldAuthoredAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLTE(FieldTenantID, v))
}

// TheatreBookingIDEQ applies the EQ predicate on the "theatre_booking_id" field.
func TheatreBookingIDEQ(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldTheatreBookingID, v))
}

// TheatreBookingIDNEQ applies the NEQ predicate on the "theatre_booking_id" field.
func TheatreBookingIDNEQ(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNEQ(FieldTheatreBookingID, v))
}

// TheatreBookingIDIn applies the In predicate on the "theatre_booking_id" field.
func TheatreBookingIDIn(vs ...uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIn(FieldTheatreBookingID, vs...))
}

// TheatreBookingIDNotIn applies the NotIn predicate on the "theatre_booking_id" field.
func TheatreBookingIDNotIn(vs ...uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotIn(FieldTheatreBookingID, vs...))
}

// SurgeonIDEQ applies the EQ predicate on the "surgeon_id" field.
func SurgeonIDEQ(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldSurgeonID, v))
}

// SurgeonIDNEQ applies the NEQ predicate on the "surgeon_id" field.
func SurgeonIDNEQ(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNEQ(FieldSurgeonID, v))
}

// SurgeonIDIn applies the In predicate on the "surgeon_id" field.
func SurgeonIDIn(vs ...uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIn(FieldSurgeonID, vs...))
}

// SurgeonIDNotIn applies the NotIn predicate on the "surgeon_id" field.
func SurgeonIDNotIn(vs ...uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotIn(FieldSurgeonID, vs...))
}

// SurgeonIDGT applies the GT predicate on the "surgeon_id" field.
func SurgeonIDGT(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGT(FieldSurgeonID, v))
}

// SurgeonIDGTE applies the GTE predicate on the "surgeon_id" field.
func SurgeonIDGTE(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGTE(FieldSurgeonID, v))
}

// SurgeonIDLT applies the LT predicate on the "surgeon_id" field.
func SurgeonIDLT(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLT(FieldSurgeonID, v))
}

// SurgeonIDLTE applies the LTE predicate on the "surgeon_id" field.
func SurgeonIDLTE(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLTE(FieldSurgeonID, v))
}

// SurgeonIDIsNil applies the IsNil predicate on the "surgeon_id" field.
func SurgeonIDIsNil() predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIsNull(FieldSurgeonID))
}

// SurgeonIDNotNil applies the NotNil predicate on the "surgeon_id" field.
func SurgeonIDNotNil() predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotNull(FieldSurgeonID))
}

// ProcedurePerformedEQ applies the EQ predicate on the "procedure_performed" field.
func ProcedurePerformedEQ(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldProcedurePerformed, v))
}

// ProcedurePerformedNEQ applies the NEQ predicate on the "procedure_performed" field.
func ProcedurePerformedNEQ(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNEQ(FieldProcedurePerformed, v))
}

// ProcedurePerformedIn applies the In predicate on the "procedure_performed" field.
func ProcedurePerformedIn(vs ...string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIn(FieldProcedurePerformed, vs...))
}

// ProcedurePerformedNotIn applies the NotIn predicate on the "procedure_performed" field.
func ProcedurePerformedNotIn(vs ...string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotIn(FieldProcedurePerformed, vs...))
}

// ProcedurePerformedGT applies the GT predicate on the "procedure_performed" field.
func ProcedurePerformedGT(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGT(FieldProcedurePerformed, v))
}

// ProcedurePerformedGTE applies the GTE predicate on the "procedure_performed" field.
func ProcedurePerformedGTE(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGTE(FieldProcedurePerformed, v))
}

// ProcedurePerformedLT applies the LT predicate on the "procedure_performed" field.
func ProcedurePerformedLT(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLT(FieldProcedurePerformed, v))
}

// ProcedurePerformedLTE applies the LTE predicate on the "procedure_performed" field.
func ProcedurePerformedLTE(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLTE(FieldProcedurePerformed, v))
}

// ProcedurePerformedContains applies the Contains predicate on the "procedure_performed" field.
func ProcedurePerformedContains(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldContains(FieldProcedurePerformed, v))
}

// ProcedurePerformedHasPrefix applies the HasPrefix predicate on the "procedure_performed" field.
func ProcedurePerformedHasPrefix(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldHasPrefix(FieldProcedurePerformed, v))
}

// ProcedurePerformedHasSuffix applies the HasSuffix predicate on the "procedure_performed" field.
func ProcedurePerformedHasSuffix(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldHasSuffix(FieldProcedurePerformed, v))
}

// ProcedurePerformedEqualFold applies the EqualFold predicate on the "procedure_performed" field.
func ProcedurePerformedEqualFold(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEqualFold(FieldProcedurePerformed, v))
}

// ProcedurePerformedContainsFold applies the ContainsFold predicate on the "procedure_performed" field.
func ProcedurePerformedContainsFold(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldContainsFold(FieldProcedurePerformed, v))
}

// FindingsEQ applies the EQ predicate on the "findings" field.
func FindingsEQ(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldFindings, v))
}

// FindingsNEQ applies the NEQ predicate on the "findings" field.
func FindingsNEQ(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNEQ(FieldFindings, v))
}

// FindingsIn applies the In predicate on the "findings" field.
func FindingsIn(vs ...string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIn(FieldFindings, vs...))
}

// FindingsNotIn applies the NotIn predicate on the "findings" field.
func FindingsNotIn(vs ...string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotIn(FieldFindings, vs...))
}

// FindingsGT applies the GT predicate on the "findings" field.
func FindingsGT(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGT(FieldFindings, v))
}

// FindingsGTE applies the GTE predicate on the "findings" field.
func FindingsGTE(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGTE(FieldFindings, v))
}

// FindingsLT applies the LT predicate on the "findings" field.
func FindingsLT(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLT(FieldFindings, v))
}

// FindingsLTE applies the LTE predicate on the "findings" field.
func FindingsLTE(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLTE(FieldFindings, v))
}

// FindingsContains applies the Contains predicate on the "findings" field.
func FindingsContains(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldContains(FieldFindings, v))
}

// FindingsHasPrefix applies the HasPrefix predicate on the "findings" field.
func FindingsHasPrefix(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldHasPrefix(FieldFindings, v))
}

// FindingsHasSuffix applies the HasSuffix predicate on the "findings" field.
func FindingsHasSuffix(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldHasSuffix(FieldFindings, v))
}

// FindingsIsNil applies the IsNil predicate on the "findings" field.
func FindingsIsNil() predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIsNull(FieldFindings))
}

// FindingsNotNil applies the NotNil predicate on the "findings" field.
func FindingsNotNil() predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotNull(FieldFindings))
}

// FindingsEqualFold applies the EqualFold predicate on the "findings" field.
func FindingsEqualFold(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEqualFold(FieldFindings, v))
}

// FindingsContainsFold applies the ContainsFold predicate on the "findings" field.
func FindingsContainsFold(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldContainsFold(FieldFindings, v))
}

// ComplicationsEQ applies the EQ predicate on the "complications" field.
func ComplicationsEQ(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldComplications, v))
}

// ComplicationsNEQ applies the NEQ predicate on the "complications" field.
func ComplicationsNEQ(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNEQ(FieldComplications, v))
}

// ComplicationsIn applies the In predicate on the "complications" field.
func ComplicationsIn(vs ...string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIn(FieldComplications, vs...))
}

// ComplicationsNotIn applies the NotIn predicate on the "complications" field.
func ComplicationsNotIn(vs ...string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotIn(FieldComplications, vs...))
}

// ComplicationsGT applies the GT predicate on the "complications" field.
func ComplicationsGT(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGT(FieldComplications, v))
}

// ComplicationsGTE applies the GTE predicate on the "complications" field.
func ComplicationsGTE(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGTE(FieldComplications, v))
}

// ComplicationsLT applies the LT predicate on the "complications" field.
func ComplicationsLT(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLT(FieldComplications, v))
}

// ComplicationsLTE applies the LTE predicate on the "complications" field.
func ComplicationsLTE(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLTE(FieldComplications, v))
}

// ComplicationsContains applies the Contains predicate on the "complications" field.
func ComplicationsContains(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldContains(FieldComplications, v))
}

// ComplicationsHasPrefix applies the HasPrefix predicate on the "complications" field.
func ComplicationsHasPrefix(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldHasPrefix(FieldComplications, v))
}

// ComplicationsHasSuffix applies the HasSuffix predicate on the "complications" field.
func ComplicationsHasSuffix(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldHasSuffix(FieldComplications, v))
}

// ComplicationsIsNil applies the IsNil predicate on the "complications" field.
func ComplicationsIsNil() predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIsNull(FieldComplications))
}

// ComplicationsNotNil applies the NotNil predicate on the "complications" field.
func ComplicationsNotNil() predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotNull(FieldComplications))
}

// ComplicationsEqualFold applies the EqualFold predicate on the "complications" field.
func ComplicationsEqualFold(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEqualFold(FieldComplications, v))
}

// ComplicationsContainsFold applies the ContainsFold predicate on the "complications" field.
func ComplicationsContainsFold(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldContainsFold(FieldComplications, v))
}

// EstimatedBloodLossMlEQ applies the EQ predicate on the "estimated_blood_loss_ml" field.
func EstimatedBloodLossMlEQ(v float64) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldEstimatedBloodLossMl, v))
}

// EstimatedBloodLossMlNEQ applies the NEQ predicate on the "estimated_blood_loss_ml" field.
func EstimatedBloodLossMlNEQ(v float64) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNEQ(FieldEstimatedBloodLossMl, v))
}

// EstimatedBloodLossMlIn applies the In predicate on the "estimated_blood_loss_ml" field.
func EstimatedBloodLossMlIn(vs ...float64) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIn(FieldEstimatedBloodLossMl, vs...))
}

// EstimatedBloodLossMlNotIn applies the NotIn predicate on the "estimated_blood_loss_ml" field.
func EstimatedBloodLossMlNotIn(vs ...float64) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotIn(FieldEstimatedBloodLossMl, vs...))
}

// EstimatedBloodLossMlGT applies the GT predicate on the "estimated_blood_loss_ml" field.
func EstimatedBloodLossMlGT(v float64) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGT(FieldEstimatedBloodLossMl, v))
}

// EstimatedBloodLossMlGTE applies the GTE predicate on the "estimated_blood_loss_ml" field.
func EstimatedBloodLossMlGTE(v float64) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGTE(FieldEstimatedBloodLossMl, v))
}

// EstimatedBloodLossMlLT applies the LT predicate on the "estimated_blood_loss_ml" field.
func EstimatedBloodLossMlLT(v float64) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLT(FieldEstimatedBloodLossMl, v))
}

// EstimatedBloodLossMlLTE applies the LTE predicate on the "estimated_blood_loss_ml" field.
func EstimatedBloodLossMlLTE(v float64) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLTE(FieldEstimatedBloodLossMl, v))
}

// EstimatedBloodLossMlIsNil applies the IsNil predicate on the "estimated_blood_loss_ml" field.
func EstimatedBloodLossMlIsNil() predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIsNull(FieldEstimatedBloodLossMl))
}

// EstimatedBloodLossMlNotNil applies the NotNil predicate on the "estimated_blood_loss_ml" field.
func EstimatedBloodLossMlNotNil() predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotNull(FieldEstimatedBloodLossMl))
}

// ImplantsUsedEQ applies the EQ predicate on the "implants_used" field.
func ImplantsUsedEQ(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldImplantsUsed, v))
}

// ImplantsUsedNEQ applies the NEQ predicate on the "implants_used" field.
func ImplantsUsedNEQ(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNEQ(FieldImplantsUsed, v))
}

// ImplantsUsedIn applies the In predicate on the "implants_used" field.
func ImplantsUsedIn(vs ...string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIn(FieldImplantsUsed, vs...))
}

// ImplantsUsedNotIn applies the NotIn predicate on the "implants_used" field.
func ImplantsUsedNotIn(vs ...string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotIn(FieldImplantsUsed, vs...))
}

// ImplantsUsedGT applies the GT predicate on the "implants_used" field.
func ImplantsUsedGT(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGT(FieldImplantsUsed, v))
}

// ImplantsUsedGTE applies the GTE predicate on the "implants_used" field.
func ImplantsUsedGTE(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGTE(FieldImplantsUsed, v))
}

// ImplantsUsedLT applies the LT predicate on the "implants_used" field.
func ImplantsUsedLT(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLT(FieldImplantsUsed, v))
}

// ImplantsUsedLTE applies the LTE predicate on the "implants_used" field.
func ImplantsUsedLTE(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLTE(FieldImplantsUsed, v))
}

// ImplantsUsedContains applies the Contains predicate on the "implants_used" field.
func ImplantsUsedContains(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldContains(FieldImplantsUsed, v))
}

// ImplantsUsedHasPrefix applies the HasPrefix predicate on the "implants_used" field.
func ImplantsUsedHasPrefix(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldHasPrefix(FieldImplantsUsed, v))
}

// ImplantsUsedHasSuffix applies the HasSuffix predicate on the "implants_used" field.
func ImplantsUsedHasSuffix(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldHasSuffix(FieldImplantsUsed, v))
}

// ImplantsUsedIsNil applies the IsNil predicate on the "implants_used" field.
func ImplantsUsedIsNil() predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIsNull(FieldImplantsUsed))
}

// ImplantsUsedNotNil applies the NotNil predicate on the "implants_used" field.
func ImplantsUsedNotNil() predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotNull(FieldImplantsUsed))
}

// ImplantsUsedEqualFold applies the EqualFold predicate on the "implants_used" field.
func ImplantsUsedEqualFold(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEqualFold(FieldImplantsUsed, v))
}

// ImplantsUsedContainsFold applies the ContainsFold predicate on the "implants_used" field.
func ImplantsUsedContainsFold(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldContainsFold(FieldImplantsUsed, v))
}

// SpecimensSentEQ applies the EQ predicate on the "specimens_sent" field.
func SpecimensSentEQ(v bool) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldSpecimensSent, v))
}

// SpecimensSentNEQ applies the NEQ predicate on the "specimens_sent" field.
func SpecimensSentNEQ(v bool) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNEQ(FieldSpecimensSent, v))
}

// SpecimensDescriptionEQ applies the EQ predicate on the "specimens_description" field.
func SpecimensDescriptionEQ(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldSpecimensDescription, v))
}

// SpecimensDescriptionNEQ applies the NEQ predicate on the "specimens_description" field.
func SpecimensDescriptionNEQ(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNEQ(FieldSpecimensDescription, v))
}

// SpecimensDescriptionIn applies the In predicate on the "specimens_description" field.
func SpecimensDescriptionIn(vs ...string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIn(FieldSpecimensDescription, vs...))
}

// SpecimensDescriptionNotIn applies the NotIn predicate on the "specimens_description" field.
func SpecimensDescriptionNotIn(vs ...string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotIn(FieldSpecimensDescription, vs...))
}

// SpecimensDescriptionGT applies the GT predicate on the "specimens_description" field.
func SpecimensDescriptionGT(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGT(FieldSpecimensDescription, v))
}

// SpecimensDescriptionGTE applies the GTE predicate on the "specimens_description" field.
func SpecimensDescriptionGTE(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGTE(FieldSpecimensDescription, v))
}

// SpecimensDescriptionLT applies the LT predicate on the "specimens_description" field.
func SpecimensDescriptionLT(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLT(FieldSpecimensDescription, v))
}

// SpecimensDescriptionLTE applies the LTE predicate on the "specimens_description" field.
func SpecimensDescriptionLTE(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLTE(FieldSpecimensDescription, v))
}

// SpecimensDescriptionContains applies the Contains predicate on the "specimens_description" field.
func SpecimensDescriptionContains(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldContains(FieldSpecimensDescription, v))
}

// SpecimensDescriptionHasPrefix applies the HasPrefix predicate on the "specimens_description" field.
func SpecimensDescriptionHasPrefix(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldHasPrefix(FieldSpecimensDescription, v))
}

// SpecimensDescriptionHasSuffix applies the HasSuffix predicate on the "specimens_description" field.
func SpecimensDescriptionHasSuffix(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldHasSuffix(FieldSpecimensDescription, v))
}

// SpecimensDescriptionIsNil applies the IsNil predicate on the "specimens_description" field.
func SpecimensDescriptionIsNil() predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIsNull(FieldSpecimensDescription))
}

// SpecimensDescriptionNotNil applies the NotNil predicate on the "specimens_description" field.
func SpecimensDescriptionNotNil() predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotNull(FieldSpecimensDescription))
}

// SpecimensDescriptionEqualFold applies the EqualFold predicate on the "specimens_description" field.
func SpecimensDescriptionEqualFold(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEqualFold(FieldSpecimensDescription, v))
}

// SpecimensDescriptionContainsFold applies the ContainsFold predicate on the "specimens_description" field.
func SpecimensDescriptionContainsFold(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldContainsFold(FieldSpecimensDescription, v))
}

// PostOpDiagnosisEQ applies the EQ predicate on the "post_op_diagnosis" field.
func PostOpDiagnosisEQ(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldPostOpDiagnosis, v))
}

// PostOpDiagnosisNEQ applies the NEQ predicate on the "post_op_diagnosis" field.
func PostOpDiagnosisNEQ(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNEQ(FieldPostOpDiagnosis, v))
}

// PostOpDiagnosisIn applies the In predicate on the "post_op_diagnosis" field.
func PostOpDiagnosisIn(vs ...string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIn(FieldPostOpDiagnosis, vs...))
}

// PostOpDiagnosisNotIn applies the NotIn predicate on the "post_op_diagnosis" field.
func PostOpDiagnosisNotIn(vs ...string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotIn(FieldPostOpDiagnosis, vs...))
}

// PostOpDiagnosisGT applies the GT predicate on the "post_op_diagnosis" field.
func PostOpDiagnosisGT(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGT(FieldPostOpDiagnosis, v))
}

// PostOpDiagnosisGTE applies the GTE predicate on the "post_op_diagnosis" field.
func PostOpDiagnosisGTE(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGTE(FieldPostOpDiagnosis, v))
}

// PostOpDiagnosisLT applies the LT predicate on the "post_op_diagnosis" field.
func PostOpDiagnosisLT(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLT(FieldPostOpDiagnosis, v))
}

// PostOpDiagnosisLTE applies the LTE predicate on the "post_op_diagnosis" field.
func PostOpDiagnosisLTE(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLTE(FieldPostOpDiagnosis, v))
}

// PostOpDiagnosisContains applies the Contains predicate on the "post_op_diagnosis" field.
func PostOpDiagnosisContains(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldContains(FieldPostOpDiagnosis, v))
}

// PostOpDiagnosisHasPrefix applies the HasPrefix predicate on the "post_op_diagnosis" field.
func PostOpDiagnosisHasPrefix(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldHasPrefix(FieldPostOpDiagnosis, v))
}

// PostOpDiagnosisHasSuffix applies the HasSuffix predicate on the "post_op_diagnosis" field.
func PostOpDiagnosisHasSuffix(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldHasSuffix(FieldPostOpDiagnosis, v))
}

// PostOpDiagnosisIsNil applies the IsNil predicate on the "post_op_diagnosis" field.
func PostOpDiagnosisIsNil() predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIsNull(FieldPostOpDiagnosis))
}

// PostOpDiagnosisNotNil applies the NotNil predicate on the "post_op_diagnosis" field.
func PostOpDiagnosisNotNil() predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotNull(FieldPostOpDiagnosis))
}

// PostOpDiagnosisEqualFold applies the EqualFold predicate on the "post_op_diagnosis" field.
func PostOpDiagnosisEqualFold(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEqualFold(FieldPostOpDiagnosis, v))
}

// PostOpDiagnosisContainsFold applies the ContainsFold predicate on the "post_op_diagnosis" field.
func PostOpDiagnosisContainsFold(v string) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldContainsFold(FieldPostOpDiagnosis, v))
}

// AuthoredByEQ applies the EQ predicate on the "authored_by" field.
func AuthoredByEQ(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldAuthoredBy, v))
}

// AuthoredByNEQ applies the NEQ predicate on the "authored_by" field.
func AuthoredByNEQ(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNEQ(FieldAuthoredBy, v))
}

// AuthoredByIn applies the In predicate on the "authored_by" field.
func AuthoredByIn(vs ...uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIn(FieldAuthoredBy, vs...))
}

// AuthoredByNotIn applies the NotIn predicate on the "authored_by" field.
func AuthoredByNotIn(vs ...uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotIn(FieldAuthoredBy, vs...))
}

// AuthoredByGT applies the GT predicate on the "authored_by" field.
func AuthoredByGT(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGT(FieldAuthoredBy, v))
}

// AuthoredByGTE applies the GTE predicate on the "authored_by" field.
func AuthoredByGTE(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGTE(FieldAuthoredBy, v))
}

// AuthoredByLT applies the LT predicate on the "authored_by" field.
func AuthoredByLT(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLT(FieldAuthoredBy, v))
}

// AuthoredByLTE applies the LTE predicate on the "authored_by" field.
func AuthoredByLTE(v uuid.UUID) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLTE(FieldAuthoredBy, v))
}

// AuthoredByIsNil applies the IsNil predicate on the "authored_by" field.
func AuthoredByIsNil() predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIsNull(FieldAuthoredBy))
}

// AuthoredByNotNil applies the NotNil predicate on the "authored_by" field.
func AuthoredByNotNil() predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotNull(FieldAuthoredBy))
}

// AuthoredAtEQ applies the EQ predicate on the "authored_at" field.
func AuthoredAtEQ(v time.Time) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldEQ(FieldAuthoredAt, v))
}

// AuthoredAtNEQ applies the NEQ predicate on the "authored_at" field.
func AuthoredAtNEQ(v time.Time) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNEQ(FieldAuthoredAt, v))
}

// AuthoredAtIn applies the In predicate on the "authored_at" field.
func AuthoredAtIn(vs ...time.Time) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldIn(FieldAuthoredAt, vs...))
}

// AuthoredAtNotIn applies the NotIn predicate on the "authored_at" field.
func AuthoredAtNotIn(vs ...time.Time) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldNotIn(FieldAuthoredAt, vs...))
}

// AuthoredAtGT applies the GT predicate on the "authored_at" field.
func AuthoredAtGT(v time.Time) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGT(FieldAuthoredAt, v))
}

// AuthoredAtGTE applies the GTE predicate on the "authored_at" field.
func AuthoredAtGTE(v time.Time) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldGTE(FieldAuthoredAt, v))
}

// AuthoredAtLT applies the LT predicate on the "authored_at" field.
func AuthoredAtLT(v time.Time) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLT(FieldAuthoredAt, v))
}

// AuthoredAtLTE applies the LTE predicate on the "authored_at" field.
func AuthoredAtLTE(v time.Time) predicate.OperativeNote {
	return predicate.OperativeNote(sql.FieldLTE(FieldAuthoredAt, v))
}

// HasTheatreBooking applies the HasEdge predicate on the "theatre_booking" edge.
func HasTheatreBooking() predicate.OperativeNote {
	return predicate.OperativeNote(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, TheatreBookingTable, TheatreBookingColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTheatreBookingWith applies the HasEdge predicate on the "theatre_booking" edge with a given conditions (other predicates).
func HasTheatreBookingWith(preds ...predicate.TheatreBooking) predicate.OperativeNote {
	return predicate.OperativeNote(func(s *sql.Selector) {
		step := newTheatreBookingStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OperativeNote) predicate.OperativeNote {
	return predicate.OperativeNote(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OperativeNote) predicate.OperativeNote {
	return predicate.OperativeNote(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OperativeNote) predicate.OperativeNote {
	return predicate.OperativeNote(sql.NotPredicates(p))
}
